/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTravelRouteImport } from './routes/_app/travel'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppRecipesRouteImport } from './routes/_app/recipes'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppCountersRouteImport } from './routes/_app/counters'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTravelRoute = AppTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppCountersRoute = AppCountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/activity': typeof AppActivityRoute
  '/counters': typeof AppCountersRoute
  '/investments': typeof AppInvestmentsRoute
  '/recipes': typeof AppRecipesRoute
  '/tasks': typeof AppTasksRoute
  '/transactions': typeof AppTransactionsRoute
  '/travel': typeof AppTravelRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AppAccountsRoute
  '/activity': typeof AppActivityRoute
  '/counters': typeof AppCountersRoute
  '/investments': typeof AppInvestmentsRoute
  '/recipes': typeof AppRecipesRoute
  '/tasks': typeof AppTasksRoute
  '/transactions': typeof AppTransactionsRoute
  '/travel': typeof AppTravelRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/counters': typeof AppCountersRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/recipes': typeof AppRecipesRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/travel': typeof AppTravelRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/activity'
    | '/counters'
    | '/investments'
    | '/recipes'
    | '/tasks'
    | '/transactions'
    | '/travel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/activity'
    | '/counters'
    | '/investments'
    | '/recipes'
    | '/tasks'
    | '/transactions'
    | '/travel'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/accounts'
    | '/_app/activity'
    | '/_app/counters'
    | '/_app/investments'
    | '/_app/recipes'
    | '/_app/tasks'
    | '/_app/transactions'
    | '/_app/travel'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/travel': {
      id: '/_app/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof AppTravelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/counters': {
      id: '/_app/counters'
      path: '/counters'
      fullPath: '/counters'
      preLoaderRoute: typeof AppCountersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppActivityRoute: typeof AppActivityRoute
  AppCountersRoute: typeof AppCountersRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppTravelRoute: typeof AppTravelRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppActivityRoute: AppActivityRoute,
  AppCountersRoute: AppCountersRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppTasksRoute: AppTasksRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppTravelRoute: AppTravelRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
