// This file is auto-generated by @hey-api/openapi-ts

export const Body_import_transactions_v1_transactions_import_postSchema = {
  properties: {
    file: {
      type: "string",
      format: "binary",
      title: "File",
    },
  },
  type: "object",
  required: ["file"],
  title: "Body_import_transactions_v1_transactions_import_post",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const ImportResponseSchema = {
  properties: {
    created: {
      type: "integer",
      title: "Created",
      description: "Number of new transactions imported.",
    },
    skipped: {
      type: "integer",
      title: "Skipped",
      description: "Number of duplicate transactions skipped.",
    },
  },
  type: "object",
  required: ["created", "skipped"],
  title: "ImportResponse",
} as const;

export const PaginationSchema = {
  properties: {
    total_count: {
      type: "integer",
      title: "Total Count",
    },
    max_page: {
      type: "integer",
      title: "Max Page",
    },
  },
  type: "object",
  required: ["total_count", "max_page"],
  title: "Pagination",
} as const;

export const TransactionDirectionSchema = {
  type: "string",
  enum: ["debit", "credit"],
  title: "TransactionDirection",
} as const;

export const TransactionListResponseSchema = {
  properties: {
    items: {
      items: {
        $ref: "#/components/schemas/TransactionSchema",
      },
      type: "array",
      title: "Items",
    },
    pagination: {
      $ref: "#/components/schemas/Pagination",
    },
  },
  type: "object",
  required: ["items", "pagination"],
  title: "TransactionListResponse",
} as const;

export const TransactionSchemaSchema = {
  properties: {
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation timestamp of the object.",
    },
    modified_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Modified At",
      description: "Last modification timestamp of the object.",
    },
    id: {
      type: "string",
      format: "uuid4",
      title: "Id",
      description: "The ID of the object.",
    },
    amount: {
      type: "integer",
      title: "Amount",
      description: "Amount in minor units (cents).",
    },
    currency: {
      type: "string",
      title: "Currency",
    },
    transaction_date: {
      type: "string",
      format: "date",
      title: "Transaction Date",
    },
    direction: {
      $ref: "#/components/schemas/TransactionDirection",
    },
    dedup_hash: {
      type: "string",
      title: "Dedup Hash",
    },
    bank_account_id: {
      type: "string",
      format: "uuid4",
      title: "Bank Account Id",
    },
    raw_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid4",
        },
        {
          type: "null",
        },
      ],
      title: "Raw Id",
    },
  },
  type: "object",
  required: [
    "created_at",
    "modified_at",
    "id",
    "amount",
    "currency",
    "transaction_date",
    "direction",
    "dedup_hash",
    "bank_account_id",
    "raw_id",
  ],
  title: "TransactionSchema",
} as const;

export const TransactionSortPropertySchema = {
  type: "string",
  enum: [
    "created_at",
    "-created_at",
    "transaction_date",
    "-transaction_date",
    "amount",
    "-amount",
  ],
  title: "TransactionSortProperty",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
