// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const UnsubscribeResponseSchema = {
  properties: {
    success: {
      type: "boolean",
      title: "Success",
    },
    message: {
      type: "string",
      title: "Message",
    },
  },
  type: "object",
  required: ["success", "message"],
  title: "UnsubscribeResponse",
} as const;

export const UserEmailResponseSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
  },
  type: "object",
  required: ["email"],
  title: "UserEmailResponse",
} as const;

export const UserInfoSchema = {
  properties: {
    sub: {
      type: "string",
      title: "Sub",
    },
    email: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    picture: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Picture",
    },
    roles: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Roles",
      default: [],
    },
  },
  type: "object",
  required: ["sub"],
  title: "UserInfo",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
