// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import { listTransactionsV1TransactionsGetResponseTransformer } from "./transformers.gen";
import type {
  HealthzHealthzGetData,
  HealthzHealthzGetResponses,
  ImportTransactionsV1TransactionsImportPostData,
  ImportTransactionsV1TransactionsImportPostErrors,
  ImportTransactionsV1TransactionsImportPostResponses,
  ListTransactionsV1TransactionsGetData,
  ListTransactionsV1TransactionsGetErrors,
  ListTransactionsV1TransactionsGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Healthz
 */
export const healthzHealthzGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthzHealthzGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthzHealthzGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/healthz", ...options });

/**
 * List Transactions
 *
 * List transactions.
 */
export const listTransactionsV1TransactionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTransactionsV1TransactionsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTransactionsV1TransactionsGetResponses,
    ListTransactionsV1TransactionsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listTransactionsV1TransactionsGetResponseTransformer,
    url: "/v1/transactions",
    ...options,
  });

/**
 * Import Transactions from CSV
 *
 * Import transactions from a bank CSV export.
 *
 * Duplicate transactions (by dedup hash) are automatically skipped.
 */
export const importTransactionsV1TransactionsImportPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ImportTransactionsV1TransactionsImportPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    ImportTransactionsV1TransactionsImportPostResponses,
    ImportTransactionsV1TransactionsImportPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/v1/transactions/import",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
