// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client/index.js";
import {
  completeTaskV1TasksTaskIdCompletePostResponseTransformer,
  createBankAccountV1BankAccountsPostResponseTransformer,
  createExerciseV1WorkoutsExercisesPostResponseTransformer,
  createPlaceV1PlacesPostResponseTransformer,
  createSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponseTransformer,
  createSecurityV1InvestmentsSecuritiesPostResponseTransformer,
  createTaskV1TasksPostResponseTransformer,
  createTradeV1InvestmentsTradesPostResponseTransformer,
  createWorkoutSetV1WorkoutsWorkoutIdSetsPostResponseTransformer,
  createWorkoutV1WorkoutsPostResponseTransformer,
  getBankAccountV1BankAccountsBankAccountIdGetResponseTransformer,
  getCalendarV1JournalCalendarGetResponseTransformer,
  getEntryV1JournalEntryDateGetResponseTransformer,
  getExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponseTransformer,
  getWeatherForecastV1WeatherGetResponseTransformer,
  getWorkoutV1WorkoutsWorkoutIdGetResponseTransformer,
  listBankAccountsV1BankAccountsGetResponseTransformer,
  listCategoriesV1CategoriesGetResponseTransformer,
  listEntriesV1JournalGetResponseTransformer,
  listExercisesV1WorkoutsExercisesGetResponseTransformer,
  listPlacesV1PlacesGetResponseTransformer,
  listRecentExercisesV1WorkoutsExercisesRecentGetResponseTransformer,
  listSecuritiesV1InvestmentsSecuritiesGetResponseTransformer,
  listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponseTransformer,
  listTasksV1TasksGetResponseTransformer,
  listTradesV1InvestmentsTradesGetResponseTransformer,
  listTransactionsV1TransactionsGetResponseTransformer,
  listWorkoutsV1WorkoutsGetResponseTransformer,
  reopenTaskV1TasksTaskIdReopenPostResponseTransformer,
  updateBankAccountV1BankAccountsBankAccountIdPatchResponseTransformer,
  updatePlaceV1PlacesPlaceIdPatchResponseTransformer,
  updateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponseTransformer,
  updateTaskV1TasksTaskIdPatchResponseTransformer,
  updateTradeV1InvestmentsTradesTradeIdPatchResponseTransformer,
  updateTransactionV1TransactionsTransactionIdPatchResponseTransformer,
  updateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponseTransformer,
  updateWorkoutV1WorkoutsWorkoutIdPatchResponseTransformer,
  upsertEntryV1JournalEntryDatePutResponseTransformer,
} from "./transformers.gen.js";
import type {
  BulkUpdateTransactionsV1TransactionsBulkPatchData,
  BulkUpdateTransactionsV1TransactionsBulkPatchErrors,
  BulkUpdateTransactionsV1TransactionsBulkPatchResponses,
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostData,
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostErrors,
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponses,
  CompleteTaskV1TasksTaskIdCompletePostData,
  CompleteTaskV1TasksTaskIdCompletePostErrors,
  CompleteTaskV1TasksTaskIdCompletePostResponses,
  CreateBankAccountV1BankAccountsPostData,
  CreateBankAccountV1BankAccountsPostErrors,
  CreateBankAccountV1BankAccountsPostResponses,
  CreateExerciseV1WorkoutsExercisesPostData,
  CreateExerciseV1WorkoutsExercisesPostErrors,
  CreateExerciseV1WorkoutsExercisesPostResponses,
  CreatePlaceV1PlacesPostData,
  CreatePlaceV1PlacesPostErrors,
  CreatePlaceV1PlacesPostResponses,
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostData,
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostErrors,
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponses,
  CreateSecurityV1InvestmentsSecuritiesPostData,
  CreateSecurityV1InvestmentsSecuritiesPostErrors,
  CreateSecurityV1InvestmentsSecuritiesPostResponses,
  CreateTaskV1TasksPostData,
  CreateTaskV1TasksPostErrors,
  CreateTaskV1TasksPostResponses,
  CreateTradeV1InvestmentsTradesPostData,
  CreateTradeV1InvestmentsTradesPostErrors,
  CreateTradeV1InvestmentsTradesPostResponses,
  CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostData,
  CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostErrors,
  CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostResponses,
  CreateWorkoutV1WorkoutsPostData,
  CreateWorkoutV1WorkoutsPostErrors,
  CreateWorkoutV1WorkoutsPostResponses,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteData,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses,
  DeleteEntryV1JournalEntryDateDeleteData,
  DeleteEntryV1JournalEntryDateDeleteErrors,
  DeleteEntryV1JournalEntryDateDeleteResponses,
  DeletePlaceV1PlacesPlaceIdDeleteData,
  DeletePlaceV1PlacesPlaceIdDeleteErrors,
  DeletePlaceV1PlacesPlaceIdDeleteResponses,
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteData,
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteErrors,
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponses,
  DeleteTaskV1TasksTaskIdDeleteData,
  DeleteTaskV1TasksTaskIdDeleteErrors,
  DeleteTaskV1TasksTaskIdDeleteResponses,
  DeleteTradeV1InvestmentsTradesTradeIdDeleteData,
  DeleteTradeV1InvestmentsTradesTradeIdDeleteErrors,
  DeleteTradeV1InvestmentsTradesTradeIdDeleteResponses,
  DeleteTransactionsV1TransactionsDeleteData,
  DeleteTransactionsV1TransactionsDeleteErrors,
  DeleteTransactionsV1TransactionsDeleteResponses,
  DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteData,
  DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteErrors,
  DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteResponses,
  DeleteWorkoutV1WorkoutsWorkoutIdDeleteData,
  DeleteWorkoutV1WorkoutsWorkoutIdDeleteErrors,
  DeleteWorkoutV1WorkoutsWorkoutIdDeleteResponses,
  GetActivitySummaryV1ActivitySummaryGetData,
  GetActivitySummaryV1ActivitySummaryGetErrors,
  GetActivitySummaryV1ActivitySummaryGetResponses,
  GetBankAccountV1BankAccountsBankAccountIdGetData,
  GetBankAccountV1BankAccountsBankAccountIdGetErrors,
  GetBankAccountV1BankAccountsBankAccountIdGetResponses,
  GetCalendarV1JournalCalendarGetData,
  GetCalendarV1JournalCalendarGetErrors,
  GetCalendarV1JournalCalendarGetResponses,
  GetEntryV1JournalEntryDateGetData,
  GetEntryV1JournalEntryDateGetErrors,
  GetEntryV1JournalEntryDateGetResponses,
  GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetData,
  GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetErrors,
  GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponses,
  GetHoldingsV1InvestmentsHoldingsGetData,
  GetHoldingsV1InvestmentsHoldingsGetResponses,
  GetKlarnaTransactionsV1KlarnaTransactionsGetData,
  GetKlarnaTransactionsV1KlarnaTransactionsGetErrors,
  GetKlarnaTransactionsV1KlarnaTransactionsGetResponses,
  GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetData,
  GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetErrors,
  GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetResponses,
  GetStreakV1JournalStreakGetData,
  GetStreakV1JournalStreakGetResponses,
  GetWeatherForecastV1WeatherGetData,
  GetWeatherForecastV1WeatherGetErrors,
  GetWeatherForecastV1WeatherGetResponses,
  GetWorkoutV1WorkoutsWorkoutIdGetData,
  GetWorkoutV1WorkoutsWorkoutIdGetErrors,
  GetWorkoutV1WorkoutsWorkoutIdGetResponses,
  HealthzHealthzGetData,
  HealthzHealthzGetResponses,
  ImportKlarnaTransactionsV1KlarnaImportPostData,
  ImportKlarnaTransactionsV1KlarnaImportPostErrors,
  ImportKlarnaTransactionsV1KlarnaImportPostResponses,
  ImportTransactionsV1TransactionsImportPostData,
  ImportTransactionsV1TransactionsImportPostErrors,
  ImportTransactionsV1TransactionsImportPostResponses,
  IngestActivityBatchV1ActivityBatchPostData,
  IngestActivityBatchV1ActivityBatchPostErrors,
  IngestActivityBatchV1ActivityBatchPostResponses,
  ListActivitySourcesV1ActivitySourcesGetData,
  ListActivitySourcesV1ActivitySourcesGetResponses,
  ListAreasV1TasksAreasGetData,
  ListAreasV1TasksAreasGetResponses,
  ListBankAccountsV1BankAccountsGetData,
  ListBankAccountsV1BankAccountsGetErrors,
  ListBankAccountsV1BankAccountsGetResponses,
  ListCategoriesV1CategoriesGetData,
  ListCategoriesV1CategoriesGetErrors,
  ListCategoriesV1CategoriesGetResponses,
  ListEntriesV1JournalGetData,
  ListEntriesV1JournalGetErrors,
  ListEntriesV1JournalGetResponses,
  ListExercisesV1WorkoutsExercisesGetData,
  ListExercisesV1WorkoutsExercisesGetErrors,
  ListExercisesV1WorkoutsExercisesGetResponses,
  ListPlacesV1PlacesGetData,
  ListPlacesV1PlacesGetErrors,
  ListPlacesV1PlacesGetResponses,
  ListProjectsV1TasksProjectsGetData,
  ListProjectsV1TasksProjectsGetResponses,
  ListRecentExercisesV1WorkoutsExercisesRecentGetData,
  ListRecentExercisesV1WorkoutsExercisesRecentGetErrors,
  ListRecentExercisesV1WorkoutsExercisesRecentGetResponses,
  ListSecuritiesV1InvestmentsSecuritiesGetData,
  ListSecuritiesV1InvestmentsSecuritiesGetErrors,
  ListSecuritiesV1InvestmentsSecuritiesGetResponses,
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData,
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetErrors,
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponses,
  ListTasksV1TasksGetData,
  ListTasksV1TasksGetErrors,
  ListTasksV1TasksGetResponses,
  ListTradesV1InvestmentsTradesGetData,
  ListTradesV1InvestmentsTradesGetErrors,
  ListTradesV1InvestmentsTradesGetResponses,
  ListTransactionsV1TransactionsGetData,
  ListTransactionsV1TransactionsGetErrors,
  ListTransactionsV1TransactionsGetResponses,
  ListWorkoutsV1WorkoutsGetData,
  ListWorkoutsV1WorkoutsGetErrors,
  ListWorkoutsV1WorkoutsGetResponses,
  MonthlyFlowV1TransactionsMonthlyFlowGetData,
  MonthlyFlowV1TransactionsMonthlyFlowGetErrors,
  MonthlyFlowV1TransactionsMonthlyFlowGetResponses,
  ReopenTaskV1TasksTaskIdReopenPostData,
  ReopenTaskV1TasksTaskIdReopenPostErrors,
  ReopenTaskV1TasksTaskIdReopenPostResponses,
  ReorderTasksV1TasksReorderPatchData,
  ReorderTasksV1TasksReorderPatchErrors,
  ReorderTasksV1TasksReorderPatchResponses,
  SearchGooglePlacesV1PlacesSearchGetData,
  SearchGooglePlacesV1PlacesSearchGetErrors,
  SearchGooglePlacesV1PlacesSearchGetResponses,
  SpendingByCategoryV1TransactionsSpendingByCategoryGetData,
  SpendingByCategoryV1TransactionsSpendingByCategoryGetErrors,
  SpendingByCategoryV1TransactionsSpendingByCategoryGetResponses,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchData,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses,
  UpdatePlaceV1PlacesPlaceIdPatchData,
  UpdatePlaceV1PlacesPlaceIdPatchErrors,
  UpdatePlaceV1PlacesPlaceIdPatchResponses,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchData,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchErrors,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponses,
  UpdateTaskV1TasksTaskIdPatchData,
  UpdateTaskV1TasksTaskIdPatchErrors,
  UpdateTaskV1TasksTaskIdPatchResponses,
  UpdateTradeV1InvestmentsTradesTradeIdPatchData,
  UpdateTradeV1InvestmentsTradesTradeIdPatchErrors,
  UpdateTradeV1InvestmentsTradesTradeIdPatchResponses,
  UpdateTransactionV1TransactionsTransactionIdPatchData,
  UpdateTransactionV1TransactionsTransactionIdPatchErrors,
  UpdateTransactionV1TransactionsTransactionIdPatchResponses,
  UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchData,
  UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchErrors,
  UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponses,
  UpdateWorkoutV1WorkoutsWorkoutIdPatchData,
  UpdateWorkoutV1WorkoutsWorkoutIdPatchErrors,
  UpdateWorkoutV1WorkoutsWorkoutIdPatchResponses,
  UpsertEntryV1JournalEntryDatePutData,
  UpsertEntryV1JournalEntryDatePutErrors,
  UpsertEntryV1JournalEntryDatePutResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Healthz
 */
export const healthzHealthzGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthzHealthzGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthzHealthzGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/healthz", ...options });

/**
 * Ingest Activity Events
 */
export const ingestActivityBatchV1ActivityBatchPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<IngestActivityBatchV1ActivityBatchPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    IngestActivityBatchV1ActivityBatchPostResponses,
    IngestActivityBatchV1ActivityBatchPostErrors,
    ThrowOnError
  >({
    url: "/v1/activity/batch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Activity Sources
 */
export const listActivitySourcesV1ActivitySourcesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListActivitySourcesV1ActivitySourcesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListActivitySourcesV1ActivitySourcesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/activity/sources", ...options });

/**
 * Get Activity Summary
 */
export const getActivitySummaryV1ActivitySummaryGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetActivitySummaryV1ActivitySummaryGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetActivitySummaryV1ActivitySummaryGetResponses,
    GetActivitySummaryV1ActivitySummaryGetErrors,
    ThrowOnError
  >({ url: "/v1/activity/summary", ...options });

/**
 * List Bank Accounts
 *
 * List all bank accounts.
 */
export const listBankAccountsV1BankAccountsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListBankAccountsV1BankAccountsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListBankAccountsV1BankAccountsGetResponses,
    ListBankAccountsV1BankAccountsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listBankAccountsV1BankAccountsGetResponseTransformer,
    url: "/v1/bank-accounts",
    ...options,
  });

/**
 * Create Bank Account
 *
 * Create a new bank account.
 */
export const createBankAccountV1BankAccountsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateBankAccountV1BankAccountsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateBankAccountV1BankAccountsPostResponses,
    CreateBankAccountV1BankAccountsPostErrors,
    ThrowOnError
  >({
    responseTransformer: createBankAccountV1BankAccountsPostResponseTransformer,
    url: "/v1/bank-accounts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Bank Account
 *
 * Delete a bank account and all its transactions.
 */
export const deleteBankAccountV1BankAccountsBankAccountIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteBankAccountV1BankAccountsBankAccountIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses,
    DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/bank-accounts/{bank_account_id}", ...options });

/**
 * Get Bank Account
 *
 * Get a bank account by ID.
 */
export const getBankAccountV1BankAccountsBankAccountIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetBankAccountV1BankAccountsBankAccountIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetBankAccountV1BankAccountsBankAccountIdGetResponses,
    GetBankAccountV1BankAccountsBankAccountIdGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getBankAccountV1BankAccountsBankAccountIdGetResponseTransformer,
    url: "/v1/bank-accounts/{bank_account_id}",
    ...options,
  });

/**
 * Update Bank Account
 *
 * Update a bank account.
 */
export const updateBankAccountV1BankAccountsBankAccountIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateBankAccountV1BankAccountsBankAccountIdPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses,
    UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateBankAccountV1BankAccountsBankAccountIdPatchResponseTransformer,
    url: "/v1/bank-accounts/{bank_account_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Categories
 *
 * List all categories.
 */
export const listCategoriesV1CategoriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCategoriesV1CategoriesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListCategoriesV1CategoriesGetResponses,
    ListCategoriesV1CategoriesGetErrors,
    ThrowOnError
  >({
    responseTransformer: listCategoriesV1CategoriesGetResponseTransformer,
    url: "/v1/categories",
    ...options,
  });

/**
 * List Securities
 */
export const listSecuritiesV1InvestmentsSecuritiesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListSecuritiesV1InvestmentsSecuritiesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSecuritiesV1InvestmentsSecuritiesGetResponses,
    ListSecuritiesV1InvestmentsSecuritiesGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      listSecuritiesV1InvestmentsSecuritiesGetResponseTransformer,
    url: "/v1/investments/securities",
    ...options,
  });

/**
 * Create Security
 */
export const createSecurityV1InvestmentsSecuritiesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSecurityV1InvestmentsSecuritiesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSecurityV1InvestmentsSecuritiesPostResponses,
    CreateSecurityV1InvestmentsSecuritiesPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      createSecurityV1InvestmentsSecuritiesPostResponseTransformer,
    url: "/v1/investments/securities",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Security
 */
export const deleteSecurityV1InvestmentsSecuritiesSecurityIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponses,
    DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/investments/securities/{security_id}", ...options });

/**
 * Update Security
 */
export const updateSecurityV1InvestmentsSecuritiesSecurityIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponses,
    UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponseTransformer,
    url: "/v1/investments/securities/{security_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Trades
 */
export const listTradesV1InvestmentsTradesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTradesV1InvestmentsTradesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTradesV1InvestmentsTradesGetResponses,
    ListTradesV1InvestmentsTradesGetErrors,
    ThrowOnError
  >({
    responseTransformer: listTradesV1InvestmentsTradesGetResponseTransformer,
    url: "/v1/investments/trades",
    ...options,
  });

/**
 * Create Trade
 */
export const createTradeV1InvestmentsTradesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTradeV1InvestmentsTradesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateTradeV1InvestmentsTradesPostResponses,
    CreateTradeV1InvestmentsTradesPostErrors,
    ThrowOnError
  >({
    responseTransformer: createTradeV1InvestmentsTradesPostResponseTransformer,
    url: "/v1/investments/trades",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Trade
 */
export const deleteTradeV1InvestmentsTradesTradeIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteTradeV1InvestmentsTradesTradeIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteTradeV1InvestmentsTradesTradeIdDeleteResponses,
    DeleteTradeV1InvestmentsTradesTradeIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/investments/trades/{trade_id}", ...options });

/**
 * Update Trade
 */
export const updateTradeV1InvestmentsTradesTradeIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTradeV1InvestmentsTradesTradeIdPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateTradeV1InvestmentsTradesTradeIdPatchResponses,
    UpdateTradeV1InvestmentsTradesTradeIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateTradeV1InvestmentsTradesTradeIdPatchResponseTransformer,
    url: "/v1/investments/trades/{trade_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Security Prices
 */
export const listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponses,
    ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponseTransformer,
    url: "/v1/investments/securities/{security_id}/prices",
    ...options,
  });

/**
 * Add Security Price
 */
export const createSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponses,
    CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      createSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponseTransformer,
    url: "/v1/investments/securities/{security_id}/prices",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Holdings
 */
export const getHoldingsV1InvestmentsHoldingsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetHoldingsV1InvestmentsHoldingsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetHoldingsV1InvestmentsHoldingsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/investments/holdings", ...options });

/**
 * List Journal Entries
 */
export const listEntriesV1JournalGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListEntriesV1JournalGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListEntriesV1JournalGetResponses,
    ListEntriesV1JournalGetErrors,
    ThrowOnError
  >({
    responseTransformer: listEntriesV1JournalGetResponseTransformer,
    url: "/v1/journal",
    ...options,
  });

/**
 * Get Calendar Data
 */
export const getCalendarV1JournalCalendarGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCalendarV1JournalCalendarGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCalendarV1JournalCalendarGetResponses,
    GetCalendarV1JournalCalendarGetErrors,
    ThrowOnError
  >({
    responseTransformer: getCalendarV1JournalCalendarGetResponseTransformer,
    url: "/v1/journal/calendar",
    ...options,
  });

/**
 * Get Streak Info
 */
export const getStreakV1JournalStreakGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetStreakV1JournalStreakGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetStreakV1JournalStreakGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/journal/streak", ...options });

/**
 * Delete Journal Entry
 */
export const deleteEntryV1JournalEntryDateDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteEntryV1JournalEntryDateDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteEntryV1JournalEntryDateDeleteResponses,
    DeleteEntryV1JournalEntryDateDeleteErrors,
    ThrowOnError
  >({ url: "/v1/journal/{entry_date}", ...options });

/**
 * Get Journal Entry
 */
export const getEntryV1JournalEntryDateGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetEntryV1JournalEntryDateGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEntryV1JournalEntryDateGetResponses,
    GetEntryV1JournalEntryDateGetErrors,
    ThrowOnError
  >({
    responseTransformer: getEntryV1JournalEntryDateGetResponseTransformer,
    url: "/v1/journal/{entry_date}",
    ...options,
  });

/**
 * Upsert Journal Entry
 */
export const upsertEntryV1JournalEntryDatePut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpsertEntryV1JournalEntryDatePutData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpsertEntryV1JournalEntryDatePutResponses,
    UpsertEntryV1JournalEntryDatePutErrors,
    ThrowOnError
  >({
    responseTransformer: upsertEntryV1JournalEntryDatePutResponseTransformer,
    url: "/v1/journal/{entry_date}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Places
 */
export const listPlacesV1PlacesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListPlacesV1PlacesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListPlacesV1PlacesGetResponses,
    ListPlacesV1PlacesGetErrors,
    ThrowOnError
  >({
    responseTransformer: listPlacesV1PlacesGetResponseTransformer,
    url: "/v1/places",
    ...options,
  });

/**
 * Create Place
 */
export const createPlaceV1PlacesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreatePlaceV1PlacesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreatePlaceV1PlacesPostResponses,
    CreatePlaceV1PlacesPostErrors,
    ThrowOnError
  >({
    responseTransformer: createPlaceV1PlacesPostResponseTransformer,
    url: "/v1/places",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search Google Places
 */
export const searchGooglePlacesV1PlacesSearchGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SearchGooglePlacesV1PlacesSearchGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchGooglePlacesV1PlacesSearchGetResponses,
    SearchGooglePlacesV1PlacesSearchGetErrors,
    ThrowOnError
  >({ url: "/v1/places/search", ...options });

/**
 * Delete Place
 */
export const deletePlaceV1PlacesPlaceIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePlaceV1PlacesPlaceIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeletePlaceV1PlacesPlaceIdDeleteResponses,
    DeletePlaceV1PlacesPlaceIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/places/{place_id}", ...options });

/**
 * Update Place
 */
export const updatePlaceV1PlacesPlaceIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePlaceV1PlacesPlaceIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdatePlaceV1PlacesPlaceIdPatchResponses,
    UpdatePlaceV1PlacesPlaceIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer: updatePlaceV1PlacesPlaceIdPatchResponseTransformer,
    url: "/v1/places/{place_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Tasks
 */
export const listTasksV1TasksGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListTasksV1TasksGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTasksV1TasksGetResponses,
    ListTasksV1TasksGetErrors,
    ThrowOnError
  >({
    responseTransformer: listTasksV1TasksGetResponseTransformer,
    url: "/v1/tasks",
    ...options,
  });

/**
 * Create Task
 */
export const createTaskV1TasksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTaskV1TasksPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateTaskV1TasksPostResponses,
    CreateTaskV1TasksPostErrors,
    ThrowOnError
  >({
    responseTransformer: createTaskV1TasksPostResponseTransformer,
    url: "/v1/tasks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Task
 */
export const deleteTaskV1TasksTaskIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTaskV1TasksTaskIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTaskV1TasksTaskIdDeleteResponses,
    DeleteTaskV1TasksTaskIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/tasks/{task_id}", ...options });

/**
 * Update Task
 */
export const updateTaskV1TasksTaskIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTaskV1TasksTaskIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateTaskV1TasksTaskIdPatchResponses,
    UpdateTaskV1TasksTaskIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer: updateTaskV1TasksTaskIdPatchResponseTransformer,
    url: "/v1/tasks/{task_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Complete Task
 */
export const completeTaskV1TasksTaskIdCompletePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompleteTaskV1TasksTaskIdCompletePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CompleteTaskV1TasksTaskIdCompletePostResponses,
    CompleteTaskV1TasksTaskIdCompletePostErrors,
    ThrowOnError
  >({
    responseTransformer:
      completeTaskV1TasksTaskIdCompletePostResponseTransformer,
    url: "/v1/tasks/{task_id}/complete",
    ...options,
  });

/**
 * Reopen Task
 */
export const reopenTaskV1TasksTaskIdReopenPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReopenTaskV1TasksTaskIdReopenPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ReopenTaskV1TasksTaskIdReopenPostResponses,
    ReopenTaskV1TasksTaskIdReopenPostErrors,
    ThrowOnError
  >({
    responseTransformer: reopenTaskV1TasksTaskIdReopenPostResponseTransformer,
    url: "/v1/tasks/{task_id}/reopen",
    ...options,
  });

/**
 * Reorder Tasks
 */
export const reorderTasksV1TasksReorderPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReorderTasksV1TasksReorderPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    ReorderTasksV1TasksReorderPatchResponses,
    ReorderTasksV1TasksReorderPatchErrors,
    ThrowOnError
  >({
    url: "/v1/tasks/reorder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Projects
 */
export const listProjectsV1TasksProjectsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListProjectsV1TasksProjectsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListProjectsV1TasksProjectsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/tasks/projects", ...options });

/**
 * List Areas
 */
export const listAreasV1TasksAreasGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListAreasV1TasksAreasGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListAreasV1TasksAreasGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/v1/tasks/areas", ...options });

/**
 * Delete Transactions
 *
 * Delete transactions by IDs.
 */
export const deleteTransactionsV1TransactionsDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTransactionsV1TransactionsDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTransactionsV1TransactionsDeleteResponses,
    DeleteTransactionsV1TransactionsDeleteErrors,
    ThrowOnError
  >({
    url: "/v1/transactions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Transactions
 *
 * List transactions.
 */
export const listTransactionsV1TransactionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTransactionsV1TransactionsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTransactionsV1TransactionsGetResponses,
    ListTransactionsV1TransactionsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listTransactionsV1TransactionsGetResponseTransformer,
    url: "/v1/transactions",
    ...options,
  });

/**
 * Import Transactions
 *
 * Import transactions from a bank export (CSV or XLSX).
 *
 * Duplicate transactions (by dedup hash) are automatically skipped.
 */
export const importTransactionsV1TransactionsImportPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ImportTransactionsV1TransactionsImportPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    ImportTransactionsV1TransactionsImportPostResponses,
    ImportTransactionsV1TransactionsImportPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/v1/transactions/import",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Update Transaction
 *
 * Update a transaction.
 */
export const updateTransactionV1TransactionsTransactionIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateTransactionV1TransactionsTransactionIdPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateTransactionV1TransactionsTransactionIdPatchResponses,
    UpdateTransactionV1TransactionsTransactionIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateTransactionV1TransactionsTransactionIdPatchResponseTransformer,
    url: "/v1/transactions/{transaction_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Bulk Update Transactions
 *
 * Update category for a list of transactions by ID.
 */
export const bulkUpdateTransactionsV1TransactionsBulkPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    BulkUpdateTransactionsV1TransactionsBulkPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    BulkUpdateTransactionsV1TransactionsBulkPatchResponses,
    BulkUpdateTransactionsV1TransactionsBulkPatchErrors,
    ThrowOnError
  >({
    url: "/v1/transactions/bulk",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Bulk Categorize by Description
 *
 * Set category for all transactions matching the given description.
 */
export const categorizeByDescriptionV1TransactionsCategorizeByDescriptionPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostData,
      ThrowOnError
    >,
  ) =>
    (options.client ?? client).post<
      CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponses,
      CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostErrors,
      ThrowOnError
    >({
      url: "/v1/transactions/categorize-by-description",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Monthly Spending by Category
 *
 * Aggregate debit spending per category for a given month.
 */
export const spendingByCategoryV1TransactionsSpendingByCategoryGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SpendingByCategoryV1TransactionsSpendingByCategoryGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    SpendingByCategoryV1TransactionsSpendingByCategoryGetResponses,
    SpendingByCategoryV1TransactionsSpendingByCategoryGetErrors,
    ThrowOnError
  >({ url: "/v1/transactions/spending-by-category", ...options });

/**
 * Monthly Income & Expenses
 *
 * Return income and expenses aggregated per month.
 */
export const monthlyFlowV1TransactionsMonthlyFlowGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MonthlyFlowV1TransactionsMonthlyFlowGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MonthlyFlowV1TransactionsMonthlyFlowGetResponses,
    MonthlyFlowV1TransactionsMonthlyFlowGetErrors,
    ThrowOnError
  >({ url: "/v1/transactions/monthly-flow", ...options });

/**
 * Get Weather Forecast
 */
export const getWeatherForecastV1WeatherGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetWeatherForecastV1WeatherGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetWeatherForecastV1WeatherGetResponses,
    GetWeatherForecastV1WeatherGetErrors,
    ThrowOnError
  >({
    responseTransformer: getWeatherForecastV1WeatherGetResponseTransformer,
    url: "/v1/weather",
    ...options,
  });

/**
 * Get Klarna Transactions
 *
 * Fetch Klarna transactions and return raw GraphQL response.
 */
export const getKlarnaTransactionsV1KlarnaTransactionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetKlarnaTransactionsV1KlarnaTransactionsGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetKlarnaTransactionsV1KlarnaTransactionsGetResponses,
    GetKlarnaTransactionsV1KlarnaTransactionsGetErrors,
    ThrowOnError
  >({ url: "/v1/klarna/transactions", ...options });

/**
 * Import Klarna Transactions
 *
 * Fetch Klarna transactions and import them into Metron.
 * Skips rejected (isAmountLineThrough), pending, and duplicate transactions.
 */
export const importKlarnaTransactionsV1KlarnaImportPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ImportKlarnaTransactionsV1KlarnaImportPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    ImportKlarnaTransactionsV1KlarnaImportPostResponses,
    ImportKlarnaTransactionsV1KlarnaImportPostErrors,
    ThrowOnError
  >({
    url: "/v1/klarna/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Exercises
 */
export const listExercisesV1WorkoutsExercisesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListExercisesV1WorkoutsExercisesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListExercisesV1WorkoutsExercisesGetResponses,
    ListExercisesV1WorkoutsExercisesGetErrors,
    ThrowOnError
  >({
    responseTransformer: listExercisesV1WorkoutsExercisesGetResponseTransformer,
    url: "/v1/workouts/exercises",
    ...options,
  });

/**
 * Create Custom Exercise
 */
export const createExerciseV1WorkoutsExercisesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateExerciseV1WorkoutsExercisesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateExerciseV1WorkoutsExercisesPostResponses,
    CreateExerciseV1WorkoutsExercisesPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      createExerciseV1WorkoutsExercisesPostResponseTransformer,
    url: "/v1/workouts/exercises",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Recent Exercises
 */
export const listRecentExercisesV1WorkoutsExercisesRecentGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListRecentExercisesV1WorkoutsExercisesRecentGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    ListRecentExercisesV1WorkoutsExercisesRecentGetResponses,
    ListRecentExercisesV1WorkoutsExercisesRecentGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      listRecentExercisesV1WorkoutsExercisesRecentGetResponseTransformer,
    url: "/v1/workouts/exercises/recent",
    ...options,
  });

/**
 * List Workouts
 */
export const listWorkoutsV1WorkoutsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListWorkoutsV1WorkoutsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListWorkoutsV1WorkoutsGetResponses,
    ListWorkoutsV1WorkoutsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listWorkoutsV1WorkoutsGetResponseTransformer,
    url: "/v1/workouts",
    ...options,
  });

/**
 * Create Workout
 */
export const createWorkoutV1WorkoutsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateWorkoutV1WorkoutsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateWorkoutV1WorkoutsPostResponses,
    CreateWorkoutV1WorkoutsPostErrors,
    ThrowOnError
  >({
    responseTransformer: createWorkoutV1WorkoutsPostResponseTransformer,
    url: "/v1/workouts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Workout
 */
export const deleteWorkoutV1WorkoutsWorkoutIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteWorkoutV1WorkoutsWorkoutIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteWorkoutV1WorkoutsWorkoutIdDeleteResponses,
    DeleteWorkoutV1WorkoutsWorkoutIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/workouts/{workout_id}", ...options });

/**
 * Get Workout Detail
 */
export const getWorkoutV1WorkoutsWorkoutIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetWorkoutV1WorkoutsWorkoutIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetWorkoutV1WorkoutsWorkoutIdGetResponses,
    GetWorkoutV1WorkoutsWorkoutIdGetErrors,
    ThrowOnError
  >({
    responseTransformer: getWorkoutV1WorkoutsWorkoutIdGetResponseTransformer,
    url: "/v1/workouts/{workout_id}",
    ...options,
  });

/**
 * Update Workout
 */
export const updateWorkoutV1WorkoutsWorkoutIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateWorkoutV1WorkoutsWorkoutIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateWorkoutV1WorkoutsWorkoutIdPatchResponses,
    UpdateWorkoutV1WorkoutsWorkoutIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateWorkoutV1WorkoutsWorkoutIdPatchResponseTransformer,
    url: "/v1/workouts/{workout_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Add Set to Workout
 */
export const createWorkoutSetV1WorkoutsWorkoutIdSetsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostResponses,
    CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      createWorkoutSetV1WorkoutsWorkoutIdSetsPostResponseTransformer,
    url: "/v1/workouts/{workout_id}/sets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Set
 */
export const deleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteResponses,
    DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteErrors,
    ThrowOnError
  >({ url: "/v1/workouts/{workout_id}/sets/{set_id}", ...options });

/**
 * Update Set
 */
export const updateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponses,
    UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponseTransformer,
    url: "/v1/workouts/{workout_id}/sets/{set_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Last Session for Exercise
 */
export const getLastSessionV1WorkoutsExercisesExerciseIdLastSessionGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetResponses,
    GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetErrors,
    ThrowOnError
  >({ url: "/v1/workouts/exercises/{exercise_id}/last-session", ...options });

/**
 * Get PRs for Exercise
 */
export const getExercisePrsV1WorkoutsExercisesExerciseIdPrsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponses,
    GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponseTransformer,
    url: "/v1/workouts/exercises/{exercise_id}/prs",
    ...options,
  });
