// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateBankAccountV1BankAccountsPostResponse,
  GetBankAccountV1BankAccountsBankAccountIdGetResponse,
  ListBankAccountsV1BankAccountsGetResponse,
  ListTransactionsV1TransactionsGetResponse,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
} from "./types.gen";

const bankAccountSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const bankAccountListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    bankAccountSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listBankAccountsV1BankAccountsGetResponseTransformer = async (
  data: any,
): Promise<ListBankAccountsV1BankAccountsGetResponse> => {
  data = bankAccountListResponseSchemaResponseTransformer(data);
  return data;
};

export const createBankAccountV1BankAccountsPostResponseTransformer = async (
  data: any,
): Promise<CreateBankAccountV1BankAccountsPostResponse> => {
  data = bankAccountSchemaSchemaResponseTransformer(data);
  return data;
};

export const getBankAccountV1BankAccountsBankAccountIdGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetBankAccountV1BankAccountsBankAccountIdGetResponse> => {
    data = bankAccountSchemaSchemaResponseTransformer(data);
    return data;
  };

export const updateBankAccountV1BankAccountsBankAccountIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse> => {
    data = bankAccountSchemaSchemaResponseTransformer(data);
    return data;
  };

const transactionSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.transaction_date = new Date(data.transaction_date);
  return data;
};

const transactionListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    transactionSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listTransactionsV1TransactionsGetResponseTransformer = async (
  data: any,
): Promise<ListTransactionsV1TransactionsGetResponse> => {
  data = transactionListResponseSchemaResponseTransformer(data);
  return data;
};
