// This file is auto-generated by @hey-api/openapi-ts

import type {
  CompleteTaskV1TasksTaskIdCompletePostResponse,
  CreateBankAccountV1BankAccountsPostResponse,
  CreateCategoryV1CategoriesPostResponse,
  CreatePlaceV1PlacesPostResponse,
  CreateTaskV1TasksPostResponse,
  GetBankAccountV1BankAccountsBankAccountIdGetResponse,
  GetCalendarV1JournalCalendarGetResponse,
  ListBankAccountsV1BankAccountsGetResponse,
  ListCategoriesV1CategoriesGetResponse,
  ListEntriesV1JournalGetResponse,
  ListPlacesV1PlacesGetResponse,
  ListTasksV1TasksGetResponse,
  ListTransactionsV1TransactionsGetResponse,
  ReopenTaskV1TasksTaskIdReopenPostResponse,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
  UpdateCategoryV1CategoriesCategoryIdPatchResponse,
  UpdatePlaceV1PlacesPlaceIdPatchResponse,
  UpdateTaskV1TasksTaskIdPatchResponse,
  UpdateTransactionV1TransactionsTransactionIdPatchResponse,
  UpsertEntryV1JournalEntryDatePutResponse,
} from "./types.gen";

const bankAccountSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const bankAccountListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    bankAccountSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listBankAccountsV1BankAccountsGetResponseTransformer = async (
  data: any,
): Promise<ListBankAccountsV1BankAccountsGetResponse> => {
  data = bankAccountListResponseSchemaResponseTransformer(data);
  return data;
};

export const createBankAccountV1BankAccountsPostResponseTransformer = async (
  data: any,
): Promise<CreateBankAccountV1BankAccountsPostResponse> => {
  data = bankAccountSchemaSchemaResponseTransformer(data);
  return data;
};

export const getBankAccountV1BankAccountsBankAccountIdGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetBankAccountV1BankAccountsBankAccountIdGetResponse> => {
    data = bankAccountSchemaSchemaResponseTransformer(data);
    return data;
  };

export const updateBankAccountV1BankAccountsBankAccountIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse> => {
    data = bankAccountSchemaSchemaResponseTransformer(data);
    return data;
  };

const categorySchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const categoryListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    categorySchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listCategoriesV1CategoriesGetResponseTransformer = async (
  data: any,
): Promise<ListCategoriesV1CategoriesGetResponse> => {
  data = categoryListResponseSchemaResponseTransformer(data);
  return data;
};

export const createCategoryV1CategoriesPostResponseTransformer = async (
  data: any,
): Promise<CreateCategoryV1CategoriesPostResponse> => {
  data = categorySchemaSchemaResponseTransformer(data);
  return data;
};

export const updateCategoryV1CategoriesCategoryIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateCategoryV1CategoriesCategoryIdPatchResponse> => {
    data = categorySchemaSchemaResponseTransformer(data);
    return data;
  };

const journalEntrySchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.entry_date = new Date(data.entry_date);
  return data;
};

const journalEntryListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    journalEntrySchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listEntriesV1JournalGetResponseTransformer = async (
  data: any,
): Promise<ListEntriesV1JournalGetResponse> => {
  data = journalEntryListResponseSchemaResponseTransformer(data);
  return data;
};

const journalCalendarDaySchemaResponseTransformer = (data: any) => {
  data.entry_date = new Date(data.entry_date);
  return data;
};

const journalCalendarResponseSchemaResponseTransformer = (data: any) => {
  data.days = data.days.map((item: any) =>
    journalCalendarDaySchemaResponseTransformer(item),
  );
  return data;
};

export const getCalendarV1JournalCalendarGetResponseTransformer = async (
  data: any,
): Promise<GetCalendarV1JournalCalendarGetResponse> => {
  data = journalCalendarResponseSchemaResponseTransformer(data);
  return data;
};

export const upsertEntryV1JournalEntryDatePutResponseTransformer = async (
  data: any,
): Promise<UpsertEntryV1JournalEntryDatePutResponse> => {
  data = journalEntrySchemaSchemaResponseTransformer(data);
  return data;
};

const placeSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.visited_at) {
    data.visited_at = new Date(data.visited_at);
  }
  return data;
};

const placeListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    placeSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listPlacesV1PlacesGetResponseTransformer = async (
  data: any,
): Promise<ListPlacesV1PlacesGetResponse> => {
  data = placeListResponseSchemaResponseTransformer(data);
  return data;
};

export const createPlaceV1PlacesPostResponseTransformer = async (
  data: any,
): Promise<CreatePlaceV1PlacesPostResponse> => {
  data = placeSchemaSchemaResponseTransformer(data);
  return data;
};

export const updatePlaceV1PlacesPlaceIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdatePlaceV1PlacesPlaceIdPatchResponse> => {
  data = placeSchemaSchemaResponseTransformer(data);
  return data;
};

const taskSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.due_date) {
    data.due_date = new Date(data.due_date);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  return data;
};

const taskListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    taskSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listTasksV1TasksGetResponseTransformer = async (
  data: any,
): Promise<ListTasksV1TasksGetResponse> => {
  data = taskListResponseSchemaResponseTransformer(data);
  return data;
};

export const createTaskV1TasksPostResponseTransformer = async (
  data: any,
): Promise<CreateTaskV1TasksPostResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateTaskV1TasksTaskIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateTaskV1TasksTaskIdPatchResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

const taskCompleteResponseSchemaResponseTransformer = (data: any) => {
  data.completed_task = taskSchemaSchemaResponseTransformer(
    data.completed_task,
  );
  if (data.next_task) {
    data.next_task = taskSchemaSchemaResponseTransformer(data.next_task);
  }
  return data;
};

export const completeTaskV1TasksTaskIdCompletePostResponseTransformer = async (
  data: any,
): Promise<CompleteTaskV1TasksTaskIdCompletePostResponse> => {
  data = taskCompleteResponseSchemaResponseTransformer(data);
  return data;
};

export const reopenTaskV1TasksTaskIdReopenPostResponseTransformer = async (
  data: any,
): Promise<ReopenTaskV1TasksTaskIdReopenPostResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

const transactionSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.transaction_date = new Date(data.transaction_date);
  return data;
};

const transactionListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    transactionSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listTransactionsV1TransactionsGetResponseTransformer = async (
  data: any,
): Promise<ListTransactionsV1TransactionsGetResponse> => {
  data = transactionListResponseSchemaResponseTransformer(data);
  return data;
};

export const updateTransactionV1TransactionsTransactionIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateTransactionV1TransactionsTransactionIdPatchResponse> => {
    data = transactionSchemaSchemaResponseTransformer(data);
    return data;
  };
