// This file is auto-generated by @hey-api/openapi-ts

import type {
  CompleteGoogleConnectV1CalendarsGoogleCallbackPostResponse,
  CompleteTaskV1TasksTaskIdCompletePostResponse,
  ConnectIcloudV1CalendarsIcloudPostResponse,
  CreateBankAccountV1BankAccountsPostResponse,
  CreateCalendarEventV1CalendarsCalendarIdEventsPostResponse,
  CreateCounterV1CountersPostResponse,
  CreateIngestTokenV1IngestTokensPostResponse,
  CreateNotificationV1NotificationsPostResponse,
  CreatePlaceV1PlacesPostResponse,
  CreateProjectV1ProjectsPostResponse,
  CreateRecipeV1RecipesPostResponse,
  CreateResetV1CountersCounterIdResetsPostResponse,
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponse,
  CreateSecurityV1InvestmentsSecuritiesPostResponse,
  CreateTaskV1TasksPostResponse,
  CreateTradeV1InvestmentsTradesPostResponse,
  GetAgentUsageStatusV1AgentUsageStatusGetResponse,
  GetBankAccountV1BankAccountsBankAccountIdGetResponse,
  GetHealthSummaryV1HealthkitSummaryGetResponse,
  GetLocationHistoryDayV1LocationHistoryDayGetResponse,
  GetLocationHistorySummaryV1LocationHistorySummaryGetResponse,
  GetPlaceV1PlacesPlaceIdGetResponse,
  GetRecipeV1RecipesRecipeIdGetResponse,
  GetTaskV1TasksTaskIdGetResponse,
  GetWeatherForecastV1WeatherGetResponse,
  ImportLocationHistoryV1LocationHistoryImportPostResponse,
  ListBankAccountsV1BankAccountsGetResponse,
  ListCalendarAccountsV1CalendarsAccountsGetResponse,
  ListCalendarEventsV1CalendarsEventsGetResponse,
  ListCategoriesV1CategoriesGetResponse,
  ListCountersV1CountersGetResponse,
  ListDevicesV1DevicesGetResponse,
  ListGymExercisesV1GymExercisesGetResponse,
  ListGymTopSetsV1GymExercisesExerciseIdSetsGetResponse,
  ListHealthkitSleepV1HealthkitSleepGetResponse,
  ListHealthkitWorkoutsV1HealthkitWorkoutsGetResponse,
  ListIngestTokensV1IngestTokensGetResponse,
  ListNotificationsV1NotificationsGetResponse,
  ListPlacesV1PlacesGetResponse,
  ListProjectsV1ProjectsGetResponse,
  ListRecipesV1RecipesGetResponse,
  ListResetsV1CountersCounterIdResetsGetResponse,
  ListSecuritiesV1InvestmentsSecuritiesGetResponse,
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse,
  ListTasksV1TasksGetResponse,
  ListTradesV1InvestmentsTradesGetResponse,
  ListTransactionsV1TransactionsGetResponse,
  MarkNotificationReadV1NotificationsNotificationIdReadPostResponse,
  PutGymTopSetV1GymExercisesExerciseIdSetsPerformedOnPutResponse,
  ReopenTaskV1TasksTaskIdReopenPostResponse,
  RespondToCalendarEventV1CalendarsEventsEventIdResponsePutResponse,
  SearchV1SearchGetResponse,
  SetProjectLocationV1ProjectsProjectIdLocationPutResponse,
  UndoCompleteTaskV1TasksTaskIdUndoCompletePostResponse,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
  UpdateCalendarEventV1CalendarsEventsEventIdPatchResponse,
  UpdateCounterV1CountersCounterIdPatchResponse,
  UpdateDeviceV1DevicesDeviceIdPatchResponse,
  UpdatePlaceV1PlacesPlaceIdPatchResponse,
  UpdateProjectV1ProjectsProjectIdPatchResponse,
  UpdateRecipeV1RecipesRecipeIdPatchResponse,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponse,
  UpdateTaskV1TasksTaskIdPatchResponse,
  UpdateTradeV1InvestmentsTradesTradeIdPatchResponse,
  UpdateTransactionV1TransactionsTransactionIdPatchResponse,
  UploadTaskAttachmentV1TasksTaskIdAttachmentsPostResponse,
  UpsertGymExerciseV1GymExercisesExerciseIdPutResponse,
} from "./types.gen.js";

const agentUsageStatusEntrySchemaResponseTransformer = (data: any) => {
  if (data.resets_at) {
    data.resets_at = new Date(data.resets_at);
  }
  data.observed_at = new Date(data.observed_at);
  return data;
};

const agentUsageStatusResponseSchemaResponseTransformer = (data: any) => {
  data.entries = data.entries.map((item: any) =>
    agentUsageStatusEntrySchemaResponseTransformer(item),
  );
  return data;
};

export const getAgentUsageStatusV1AgentUsageStatusGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetAgentUsageStatusV1AgentUsageStatusGetResponse> => {
    data = agentUsageStatusResponseSchemaResponseTransformer(data);
    return data;
  };

const bankAccountSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const bankAccountListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    bankAccountSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listBankAccountsV1BankAccountsGetResponseTransformer = async (
  data: any,
): Promise<ListBankAccountsV1BankAccountsGetResponse> => {
  data = bankAccountListResponseSchemaResponseTransformer(data);
  return data;
};

export const createBankAccountV1BankAccountsPostResponseTransformer = async (
  data: any,
): Promise<CreateBankAccountV1BankAccountsPostResponse> => {
  data = bankAccountSchemaSchemaResponseTransformer(data);
  return data;
};

export const getBankAccountV1BankAccountsBankAccountIdGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetBankAccountV1BankAccountsBankAccountIdGetResponse> => {
    data = bankAccountSchemaSchemaResponseTransformer(data);
    return data;
  };

export const updateBankAccountV1BankAccountsBankAccountIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse> => {
    data = bankAccountSchemaSchemaResponseTransformer(data);
    return data;
  };

const calendarAccountSchemaSchemaResponseTransformer = (data: any) => {
  if (data.last_synced_at) {
    data.last_synced_at = new Date(data.last_synced_at);
  }
  return data;
};

const calendarAccountListResponseSchemaResponseTransformer = (data: any) => {
  data.accounts = data.accounts.map((item: any) =>
    calendarAccountSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listCalendarAccountsV1CalendarsAccountsGetResponseTransformer =
  async (
    data: any,
  ): Promise<ListCalendarAccountsV1CalendarsAccountsGetResponse> => {
    data = calendarAccountListResponseSchemaResponseTransformer(data);
    return data;
  };

export const completeGoogleConnectV1CalendarsGoogleCallbackPostResponseTransformer =
  async (
    data: any,
  ): Promise<CompleteGoogleConnectV1CalendarsGoogleCallbackPostResponse> => {
    data = calendarAccountSchemaSchemaResponseTransformer(data);
    return data;
  };

export const connectIcloudV1CalendarsIcloudPostResponseTransformer = async (
  data: any,
): Promise<ConnectIcloudV1CalendarsIcloudPostResponse> => {
  data = calendarAccountSchemaSchemaResponseTransformer(data);
  return data;
};

const calendarEventSchemaSchemaResponseTransformer = (data: any) => {
  if (data.start_at) {
    data.start_at = new Date(data.start_at);
  }
  if (data.end_at) {
    data.end_at = new Date(data.end_at);
  }
  if (data.start_date) {
    data.start_date = new Date(data.start_date);
  }
  if (data.end_date) {
    data.end_date = new Date(data.end_date);
  }
  return data;
};

const calendarEventListResponseSchemaResponseTransformer = (data: any) => {
  data.events = data.events.map((item: any) =>
    calendarEventSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listCalendarEventsV1CalendarsEventsGetResponseTransformer = async (
  data: any,
): Promise<ListCalendarEventsV1CalendarsEventsGetResponse> => {
  data = calendarEventListResponseSchemaResponseTransformer(data);
  return data;
};

const eventWriteResponseSchemaResponseTransformer = (data: any) => {
  if (data.event) {
    data.event = calendarEventSchemaSchemaResponseTransformer(data.event);
  }
  return data;
};

export const createCalendarEventV1CalendarsCalendarIdEventsPostResponseTransformer =
  async (
    data: any,
  ): Promise<CreateCalendarEventV1CalendarsCalendarIdEventsPostResponse> => {
    data = eventWriteResponseSchemaResponseTransformer(data);
    return data;
  };

export const updateCalendarEventV1CalendarsEventsEventIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateCalendarEventV1CalendarsEventsEventIdPatchResponse> => {
    data = eventWriteResponseSchemaResponseTransformer(data);
    return data;
  };

export const respondToCalendarEventV1CalendarsEventsEventIdResponsePutResponseTransformer =
  async (
    data: any,
  ): Promise<RespondToCalendarEventV1CalendarsEventsEventIdResponsePutResponse> => {
    data = eventWriteResponseSchemaResponseTransformer(data);
    return data;
  };

const categorySchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const categoryListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    categorySchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listCategoriesV1CategoriesGetResponseTransformer = async (
  data: any,
): Promise<ListCategoriesV1CategoriesGetResponse> => {
  data = categoryListResponseSchemaResponseTransformer(data);
  return data;
};

const counterSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.last_reset_at) {
    data.last_reset_at = new Date(data.last_reset_at);
  }
  return data;
};

export const listCountersV1CountersGetResponseTransformer = async (
  data: any,
): Promise<ListCountersV1CountersGetResponse> => {
  data = data.map((item: any) => counterSchemaSchemaResponseTransformer(item));
  return data;
};

export const createCounterV1CountersPostResponseTransformer = async (
  data: any,
): Promise<CreateCounterV1CountersPostResponse> => {
  data = counterSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateCounterV1CountersCounterIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateCounterV1CountersCounterIdPatchResponse> => {
  data = counterSchemaSchemaResponseTransformer(data);
  return data;
};

const counterResetSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

export const listResetsV1CountersCounterIdResetsGetResponseTransformer = async (
  data: any,
): Promise<ListResetsV1CountersCounterIdResetsGetResponse> => {
  data = data.map((item: any) =>
    counterResetSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const createResetV1CountersCounterIdResetsPostResponseTransformer =
  async (
    data: any,
  ): Promise<CreateResetV1CountersCounterIdResetsPostResponse> => {
    data = counterResetSchemaSchemaResponseTransformer(data);
    return data;
  };

const deviceSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.last_seen_at = new Date(data.last_seen_at);
  return data;
};

export const listDevicesV1DevicesGetResponseTransformer = async (
  data: any,
): Promise<ListDevicesV1DevicesGetResponse> => {
  data = data.map((item: any) => deviceSchemaSchemaResponseTransformer(item));
  return data;
};

export const updateDeviceV1DevicesDeviceIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateDeviceV1DevicesDeviceIdPatchResponse> => {
  data = deviceSchemaSchemaResponseTransformer(data);
  return data;
};

const gymTopSetSchemaSchemaResponseTransformer = (data: any) => {
  data.performed_on = new Date(data.performed_on);
  return data;
};

const gymExerciseSummarySchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.last_set) {
    data.last_set = gymTopSetSchemaSchemaResponseTransformer(data.last_set);
  }
  if (data.best_set) {
    data.best_set = gymTopSetSchemaSchemaResponseTransformer(data.best_set);
  }
  data.recent_sets = data.recent_sets.map((item: any) =>
    gymTopSetSchemaSchemaResponseTransformer(item),
  );
  return data;
};

const gymExerciseListResponseSchemaResponseTransformer = (data: any) => {
  data.exercises = data.exercises.map((item: any) =>
    gymExerciseSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const listGymExercisesV1GymExercisesGetResponseTransformer = async (
  data: any,
): Promise<ListGymExercisesV1GymExercisesGetResponse> => {
  data = gymExerciseListResponseSchemaResponseTransformer(data);
  return data;
};

const gymExerciseSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const upsertGymExerciseV1GymExercisesExerciseIdPutResponseTransformer =
  async (
    data: any,
  ): Promise<UpsertGymExerciseV1GymExercisesExerciseIdPutResponse> => {
    data = gymExerciseSchemaSchemaResponseTransformer(data);
    return data;
  };

const gymTopSetListResponseSchemaResponseTransformer = (data: any) => {
  data.sets = data.sets.map((item: any) =>
    gymTopSetSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listGymTopSetsV1GymExercisesExerciseIdSetsGetResponseTransformer =
  async (
    data: any,
  ): Promise<ListGymTopSetsV1GymExercisesExerciseIdSetsGetResponse> => {
    data = gymTopSetListResponseSchemaResponseTransformer(data);
    return data;
  };

export const putGymTopSetV1GymExercisesExerciseIdSetsPerformedOnPutResponseTransformer =
  async (
    data: any,
  ): Promise<PutGymTopSetV1GymExercisesExerciseIdSetsPerformedOnPutResponse> => {
    data = gymTopSetSchemaSchemaResponseTransformer(data);
    return data;
  };

const healthKitWorkoutSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.start_date = new Date(data.start_date);
  data.end_date = new Date(data.end_date);
  return data;
};

const healthKitWorkoutListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    healthKitWorkoutSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listHealthkitWorkoutsV1HealthkitWorkoutsGetResponseTransformer =
  async (
    data: any,
  ): Promise<ListHealthkitWorkoutsV1HealthkitWorkoutsGetResponse> => {
    data = healthKitWorkoutListResponseSchemaResponseTransformer(data);
    return data;
  };

const healthKitSleepSampleSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.start_date = new Date(data.start_date);
  data.end_date = new Date(data.end_date);
  return data;
};

const healthKitSleepListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    healthKitSleepSampleSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listHealthkitSleepV1HealthkitSleepGetResponseTransformer = async (
  data: any,
): Promise<ListHealthkitSleepV1HealthkitSleepGetResponse> => {
  data = healthKitSleepListResponseSchemaResponseTransformer(data);
  return data;
};

const sleepStageSegmentSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  data.end = new Date(data.end);
  return data;
};

const sleepDaySummarySchemaResponseTransformer = (data: any) => {
  data.segments = data.segments.map((item: any) =>
    sleepStageSegmentSchemaResponseTransformer(item),
  );
  return data;
};

const healthWeekDaySchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  return data;
};

const healthSummaryResponseSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  if (data.sleep) {
    data.sleep = sleepDaySummarySchemaResponseTransformer(data.sleep);
  }
  data.week = data.week.map((item: any) =>
    healthWeekDaySchemaResponseTransformer(item),
  );
  return data;
};

export const getHealthSummaryV1HealthkitSummaryGetResponseTransformer = async (
  data: any,
): Promise<GetHealthSummaryV1HealthkitSummaryGetResponse> => {
  data = healthSummaryResponseSchemaResponseTransformer(data);
  return data;
};

const ingestTokenSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.last_used_at) {
    data.last_used_at = new Date(data.last_used_at);
  }
  return data;
};

export const listIngestTokensV1IngestTokensGetResponseTransformer = async (
  data: any,
): Promise<ListIngestTokensV1IngestTokensGetResponse> => {
  data = data.map((item: any) =>
    ingestTokenSchemaSchemaResponseTransformer(item),
  );
  return data;
};

const ingestTokenCreatedSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.last_used_at) {
    data.last_used_at = new Date(data.last_used_at);
  }
  return data;
};

export const createIngestTokenV1IngestTokensPostResponseTransformer = async (
  data: any,
): Promise<CreateIngestTokenV1IngestTokensPostResponse> => {
  data = ingestTokenCreatedSchemaResponseTransformer(data);
  return data;
};

const securitySchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const securityListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    securitySchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listSecuritiesV1InvestmentsSecuritiesGetResponseTransformer =
  async (
    data: any,
  ): Promise<ListSecuritiesV1InvestmentsSecuritiesGetResponse> => {
    data = securityListResponseSchemaResponseTransformer(data);
    return data;
  };

export const createSecurityV1InvestmentsSecuritiesPostResponseTransformer =
  async (
    data: any,
  ): Promise<CreateSecurityV1InvestmentsSecuritiesPostResponse> => {
    data = securitySchemaSchemaResponseTransformer(data);
    return data;
  };

export const updateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponse> => {
    data = securitySchemaSchemaResponseTransformer(data);
    return data;
  };

const tradeSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.trade_date = new Date(data.trade_date);
  return data;
};

const tradeListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    tradeSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listTradesV1InvestmentsTradesGetResponseTransformer = async (
  data: any,
): Promise<ListTradesV1InvestmentsTradesGetResponse> => {
  data = tradeListResponseSchemaResponseTransformer(data);
  return data;
};

export const createTradeV1InvestmentsTradesPostResponseTransformer = async (
  data: any,
): Promise<CreateTradeV1InvestmentsTradesPostResponse> => {
  data = tradeSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateTradeV1InvestmentsTradesTradeIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateTradeV1InvestmentsTradesTradeIdPatchResponse> => {
    data = tradeSchemaSchemaResponseTransformer(data);
    return data;
  };

const securityPriceSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.price_date = new Date(data.price_date);
  return data;
};

const securityPriceListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    securityPriceSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponseTransformer =
  async (
    data: any,
  ): Promise<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse> => {
    data = securityPriceListResponseSchemaResponseTransformer(data);
    return data;
  };

export const createSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponseTransformer =
  async (
    data: any,
  ): Promise<CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponse> => {
    data = securityPriceSchemaSchemaResponseTransformer(data);
    return data;
  };

const locationImportSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.as_of = new Date(data.as_of);
  data.range_start = new Date(data.range_start);
  data.range_end = new Date(data.range_end);
  return data;
};

export const importLocationHistoryV1LocationHistoryImportPostResponseTransformer =
  async (
    data: any,
  ): Promise<ImportLocationHistoryV1LocationHistoryImportPostResponse> => {
    data = locationImportSchemaSchemaResponseTransformer(data);
    return data;
  };

const locationHistorySummarySchemaResponseTransformer = (data: any) => {
  data.days = data.days.map((item: any) => new Date(item));
  if (data.last_import) {
    data.last_import = locationImportSchemaSchemaResponseTransformer(
      data.last_import,
    );
  }
  return data;
};

export const getLocationHistorySummaryV1LocationHistorySummaryGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetLocationHistorySummaryV1LocationHistorySummaryGetResponse> => {
    data = locationHistorySummarySchemaResponseTransformer(data);
    return data;
  };

const locationVisitSchemaResponseTransformer = (data: any) => {
  data.start_at = new Date(data.start_at);
  data.end_at = new Date(data.end_at);
  return data;
};

const locationActivitySchemaResponseTransformer = (data: any) => {
  data.start_at = new Date(data.start_at);
  data.end_at = new Date(data.end_at);
  return data;
};

const locationDaySchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  data.visits = data.visits.map((item: any) =>
    locationVisitSchemaResponseTransformer(item),
  );
  data.activities = data.activities.map((item: any) =>
    locationActivitySchemaResponseTransformer(item),
  );
  return data;
};

export const getLocationHistoryDayV1LocationHistoryDayGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetLocationHistoryDayV1LocationHistoryDayGetResponse> => {
    data = locationDaySchemaResponseTransformer(data);
    return data;
  };

const notificationResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.read_at) {
    data.read_at = new Date(data.read_at);
  }
  return data;
};

const notificationsListResponseSchemaResponseTransformer = (data: any) => {
  data.notifications = data.notifications.map((item: any) =>
    notificationResponseSchemaResponseTransformer(item),
  );
  return data;
};

export const listNotificationsV1NotificationsGetResponseTransformer = async (
  data: any,
): Promise<ListNotificationsV1NotificationsGetResponse> => {
  data = notificationsListResponseSchemaResponseTransformer(data);
  return data;
};

export const createNotificationV1NotificationsPostResponseTransformer = async (
  data: any,
): Promise<CreateNotificationV1NotificationsPostResponse> => {
  data = notificationResponseSchemaResponseTransformer(data);
  return data;
};

export const markNotificationReadV1NotificationsNotificationIdReadPostResponseTransformer =
  async (
    data: any,
  ): Promise<MarkNotificationReadV1NotificationsNotificationIdReadPostResponse> => {
    data = notificationResponseSchemaResponseTransformer(data);
    return data;
  };

const placeSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.visited_at) {
    data.visited_at = new Date(data.visited_at);
  }
  return data;
};

const placeListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    placeSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listPlacesV1PlacesGetResponseTransformer = async (
  data: any,
): Promise<ListPlacesV1PlacesGetResponse> => {
  data = placeListResponseSchemaResponseTransformer(data);
  return data;
};

export const createPlaceV1PlacesPostResponseTransformer = async (
  data: any,
): Promise<CreatePlaceV1PlacesPostResponse> => {
  data = placeSchemaSchemaResponseTransformer(data);
  return data;
};

export const getPlaceV1PlacesPlaceIdGetResponseTransformer = async (
  data: any,
): Promise<GetPlaceV1PlacesPlaceIdGetResponse> => {
  data = placeSchemaSchemaResponseTransformer(data);
  return data;
};

export const updatePlaceV1PlacesPlaceIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdatePlaceV1PlacesPlaceIdPatchResponse> => {
  data = placeSchemaSchemaResponseTransformer(data);
  return data;
};

const projectSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

export const listProjectsV1ProjectsGetResponseTransformer = async (
  data: any,
): Promise<ListProjectsV1ProjectsGetResponse> => {
  data = data.map((item: any) => projectSchemaSchemaResponseTransformer(item));
  return data;
};

export const createProjectV1ProjectsPostResponseTransformer = async (
  data: any,
): Promise<CreateProjectV1ProjectsPostResponse> => {
  data = projectSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateProjectV1ProjectsProjectIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateProjectV1ProjectsProjectIdPatchResponse> => {
  data = projectSchemaSchemaResponseTransformer(data);
  return data;
};

export const setProjectLocationV1ProjectsProjectIdLocationPutResponseTransformer =
  async (
    data: any,
  ): Promise<SetProjectLocationV1ProjectsProjectIdLocationPutResponse> => {
    data = projectSchemaSchemaResponseTransformer(data);
    return data;
  };

const recipeSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const recipeListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    recipeSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listRecipesV1RecipesGetResponseTransformer = async (
  data: any,
): Promise<ListRecipesV1RecipesGetResponse> => {
  data = recipeListResponseSchemaResponseTransformer(data);
  return data;
};

export const createRecipeV1RecipesPostResponseTransformer = async (
  data: any,
): Promise<CreateRecipeV1RecipesPostResponse> => {
  data = recipeSchemaSchemaResponseTransformer(data);
  return data;
};

export const getRecipeV1RecipesRecipeIdGetResponseTransformer = async (
  data: any,
): Promise<GetRecipeV1RecipesRecipeIdGetResponse> => {
  data = recipeSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateRecipeV1RecipesRecipeIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateRecipeV1RecipesRecipeIdPatchResponse> => {
  data = recipeSchemaSchemaResponseTransformer(data);
  return data;
};

const eventHitSchemaResponseTransformer = (data: any) => {
  if (data.start_at) {
    data.start_at = new Date(data.start_at);
  }
  if (data.start_date) {
    data.start_date = new Date(data.start_date);
  }
  return data;
};

const searchResponseSchemaResponseTransformer = (data: any) => {
  data.events = data.events.map((item: any) =>
    eventHitSchemaResponseTransformer(item),
  );
  return data;
};

export const searchV1SearchGetResponseTransformer = async (
  data: any,
): Promise<SearchV1SearchGetResponse> => {
  data = searchResponseSchemaResponseTransformer(data);
  return data;
};

const taskAttachmentSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  return data;
};

const taskSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  if (data.due_date) {
    data.due_date = new Date(data.due_date);
  }
  if (data.completed_at) {
    data.completed_at = new Date(data.completed_at);
  }
  if (data.attachments) {
    data.attachments = data.attachments.map((item: any) =>
      taskAttachmentSchemaSchemaResponseTransformer(item),
    );
  }
  return data;
};

const taskListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    taskSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listTasksV1TasksGetResponseTransformer = async (
  data: any,
): Promise<ListTasksV1TasksGetResponse> => {
  data = taskListResponseSchemaResponseTransformer(data);
  return data;
};

export const createTaskV1TasksPostResponseTransformer = async (
  data: any,
): Promise<CreateTaskV1TasksPostResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

export const getTaskV1TasksTaskIdGetResponseTransformer = async (
  data: any,
): Promise<GetTaskV1TasksTaskIdGetResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateTaskV1TasksTaskIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateTaskV1TasksTaskIdPatchResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

export const uploadTaskAttachmentV1TasksTaskIdAttachmentsPostResponseTransformer =
  async (
    data: any,
  ): Promise<UploadTaskAttachmentV1TasksTaskIdAttachmentsPostResponse> => {
    data = taskAttachmentSchemaSchemaResponseTransformer(data);
    return data;
  };

const taskCompleteResponseSchemaResponseTransformer = (data: any) => {
  data.completed_task = taskSchemaSchemaResponseTransformer(
    data.completed_task,
  );
  if (data.next_task) {
    data.next_task = taskSchemaSchemaResponseTransformer(data.next_task);
  }
  return data;
};

export const completeTaskV1TasksTaskIdCompletePostResponseTransformer = async (
  data: any,
): Promise<CompleteTaskV1TasksTaskIdCompletePostResponse> => {
  data = taskCompleteResponseSchemaResponseTransformer(data);
  return data;
};

export const reopenTaskV1TasksTaskIdReopenPostResponseTransformer = async (
  data: any,
): Promise<ReopenTaskV1TasksTaskIdReopenPostResponse> => {
  data = taskSchemaSchemaResponseTransformer(data);
  return data;
};

export const undoCompleteTaskV1TasksTaskIdUndoCompletePostResponseTransformer =
  async (
    data: any,
  ): Promise<UndoCompleteTaskV1TasksTaskIdUndoCompletePostResponse> => {
    data = taskSchemaSchemaResponseTransformer(data);
    return data;
  };

const transactionSchemaSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.transaction_date = new Date(data.transaction_date);
  return data;
};

const transactionListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    transactionSchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const listTransactionsV1TransactionsGetResponseTransformer = async (
  data: any,
): Promise<ListTransactionsV1TransactionsGetResponse> => {
  data = transactionListResponseSchemaResponseTransformer(data);
  return data;
};

const transactionUpdateResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.modified_at) {
    data.modified_at = new Date(data.modified_at);
  }
  data.transaction_date = new Date(data.transaction_date);
  return data;
};

export const updateTransactionV1TransactionsTransactionIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateTransactionV1TransactionsTransactionIdPatchResponse> => {
    data = transactionUpdateResponseSchemaResponseTransformer(data);
    return data;
  };

const weatherDaySchemaSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  return data;
};

const weatherForecastResponseSchemaResponseTransformer = (data: any) => {
  data.days = data.days.map((item: any) =>
    weatherDaySchemaSchemaResponseTransformer(item),
  );
  return data;
};

export const getWeatherForecastV1WeatherGetResponseTransformer = async (
  data: any,
): Promise<GetWeatherForecastV1WeatherGetResponse> => {
  data = weatherForecastResponseSchemaResponseTransformer(data);
  return data;
};
