// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.metron.sh" | (string & {});
};

/**
 * BankAccountCreate
 */
export type BankAccountCreate = {
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name: string;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance?: number;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype: string;
};

/**
 * BankAccountListResponse
 */
export type BankAccountListResponse = {
  /**
   * Items
   */
  items: Array<BankAccountSchema>;
  pagination: Pagination;
};

/**
 * BankAccountSchema
 */
export type BankAccountSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name: string;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance: number;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype: string;
  /**
   * Current Balance
   *
   * Current balance in minor units (base_balance + credits - debits).
   */
  current_balance?: number;
};

/**
 * BankAccountSortProperty
 */
export const BankAccountSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  NAME: "name",
  "-NAME": "-name",
} as const;

/**
 * BankAccountSortProperty
 */
export type BankAccountSortProperty =
  (typeof BankAccountSortProperty)[keyof typeof BankAccountSortProperty];

/**
 * BankAccountUpdate
 */
export type BankAccountUpdate = {
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name?: string | null;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency?: string | null;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance?: number | null;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype?: string | null;
};

/**
 * Body_import_transactions_v1_transactions_import_post
 */
export type BodyImportTransactionsV1TransactionsImportPost = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * BulkDeleteRequest
 */
export type BulkDeleteRequest = {
  /**
   * Ids
   *
   * List of transaction IDs to delete.
   */
  ids: Array<string>;
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
  /**
   * Name
   *
   * Category name.
   */
  name: string;
  /**
   * Color
   *
   * Hex color code.
   */
  color?: string;
};

/**
 * CategoryListResponse
 */
export type CategoryListResponse = {
  /**
   * Items
   */
  items: Array<CategorySchema>;
  pagination: Pagination;
};

/**
 * CategorySchema
 */
export type CategorySchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Category name.
   */
  name: string;
  /**
   * Color
   *
   * Hex color code for UI display.
   */
  color: string;
};

/**
 * CategorySortProperty
 */
export const CategorySortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  NAME: "name",
  "-NAME": "-name",
} as const;

/**
 * CategorySortProperty
 */
export type CategorySortProperty =
  (typeof CategorySortProperty)[keyof typeof CategorySortProperty];

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
  /**
   * Name
   *
   * Category name.
   */
  name?: string | null;
  /**
   * Color
   *
   * Hex color code.
   */
  color?: string | null;
};

/**
 * GooglePlaceSearchResponse
 */
export type GooglePlaceSearchResponse = {
  /**
   * Results
   */
  results: Array<GooglePlaceSearchResult>;
};

/**
 * GooglePlaceSearchResult
 */
export type GooglePlaceSearchResult = {
  /**
   * Place Id
   *
   * Google Place ID.
   */
  place_id: string;
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   *
   * Formatted address.
   */
  address: string;
  /**
   * Country
   *
   * Country name.
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude.
   */
  longitude: number;
  /**
   * Plus Code
   *
   * Plus Code.
   */
  plus_code?: string | null;
  /**
   * Category
   *
   * Primary type.
   */
  category?: string | null;
  /**
   * Photo Url
   *
   * Photo reference URL.
   */
  photo_url?: string | null;
  /**
   * Website
   *
   * Website.
   */
  website?: string | null;
  /**
   * Phone
   *
   * Phone number.
   */
  phone?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ImportResponse
 */
export type ImportResponse = {
  /**
   * Created
   *
   * Number of new transactions imported.
   */
  created: number;
  /**
   * Skipped
   *
   * Number of duplicate transactions skipped.
   */
  skipped: number;
};

/**
 * Pagination
 */
export type Pagination = {
  /**
   * Total Count
   */
  total_count: number;
  /**
   * Max Page
   */
  max_page: number;
};

/**
 * PlaceCreate
 */
export type PlaceCreate = {
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Country
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude coordinate.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude coordinate.
   */
  longitude: number;
  /**
   * Google Place Id
   */
  google_place_id?: string | null;
  /**
   * Plus Code
   */
  plus_code?: string | null;
  status?: PlaceStatus;
  /**
   * Rating
   */
  rating?: number | null;
  /**
   * Visited At
   */
  visited_at?: Date | null;
  /**
   * Review
   */
  review?: string | null;
  /**
   * Category
   */
  category?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   */
  photo_url?: string | null;
  /**
   * Website
   */
  website?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * PlaceListResponse
 */
export type PlaceListResponse = {
  /**
   * Items
   */
  items: Array<PlaceSchema>;
  pagination: Pagination;
};

/**
 * PlaceSchema
 */
export type PlaceSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   *
   * Full address.
   */
  address?: string | null;
  /**
   * Country
   *
   * Country name.
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude coordinate.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude coordinate.
   */
  longitude: number;
  /**
   * Google Place Id
   *
   * Google Maps place ID.
   */
  google_place_id?: string | null;
  /**
   * Plus Code
   *
   * Google Plus Code.
   */
  plus_code?: string | null;
  /**
   * Place status.
   */
  status?: PlaceStatus;
  /**
   * Rating
   *
   * Personal rating (1-5).
   */
  rating?: number | null;
  /**
   * Visited At
   *
   * Date when the place was visited.
   */
  visited_at?: Date | null;
  /**
   * Review
   *
   * Personal review/notes.
   */
  review?: string | null;
  /**
   * Category
   *
   * Place category (e.g. restaurant, cafe).
   */
  category?: string | null;
  /**
   * Tags
   *
   * User-defined tags.
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   *
   * Photo URL from Google.
   */
  photo_url?: string | null;
  /**
   * Website
   *
   * Website URL.
   */
  website?: string | null;
  /**
   * Phone
   *
   * Phone number.
   */
  phone?: string | null;
};

/**
 * PlaceSortProperty
 */
export const PlaceSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  NAME: "name",
  "-NAME": "-name",
  RATING: "rating",
  "-RATING": "-rating",
  VISITED_AT: "visited_at",
  "-VISITED_AT": "-visited_at",
} as const;

/**
 * PlaceSortProperty
 */
export type PlaceSortProperty =
  (typeof PlaceSortProperty)[keyof typeof PlaceSortProperty];

/**
 * PlaceStatus
 */
export const PlaceStatus = {
  WANT_TO_GO: "want_to_go",
  VISITED: "visited",
} as const;

/**
 * PlaceStatus
 */
export type PlaceStatus = (typeof PlaceStatus)[keyof typeof PlaceStatus];

/**
 * PlaceUpdate
 */
export type PlaceUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Country
   */
  country?: string | null;
  /**
   * Latitude
   */
  latitude?: number | null;
  /**
   * Longitude
   */
  longitude?: number | null;
  status?: PlaceStatus | null;
  /**
   * Rating
   */
  rating?: number | null;
  /**
   * Visited At
   */
  visited_at?: Date | null;
  /**
   * Review
   */
  review?: string | null;
  /**
   * Category
   */
  category?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   */
  photo_url?: string | null;
  /**
   * Website
   */
  website?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * TransactionDirection
 */
export const TransactionDirection = {
  DEBIT: "debit",
  CREDIT: "credit",
} as const;

/**
 * TransactionDirection
 */
export type TransactionDirection =
  (typeof TransactionDirection)[keyof typeof TransactionDirection];

/**
 * TransactionListResponse
 */
export type TransactionListResponse = {
  /**
   * Items
   */
  items: Array<TransactionSchema>;
  pagination: Pagination;
};

/**
 * TransactionSchema
 */
export type TransactionSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Amount
   *
   * Amount in minor units (cents).
   */
  amount: number;
  /**
   * Currency
   */
  currency: string;
  /**
   * Transaction Date
   */
  transaction_date: Date;
  direction: TransactionDirection;
  /**
   * Description
   */
  description: string | null;
  /**
   * Category Id
   */
  category_id: string | null;
  /**
   * Transaction Type
   */
  transaction_type: string | null;
  /**
   * Dedup Hash
   */
  dedup_hash: string;
  /**
   * Bank Account Id
   */
  bank_account_id: string;
  /**
   * Raw Id
   */
  raw_id: string | null;
};

/**
 * TransactionSortProperty
 */
export const TransactionSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  TRANSACTION_DATE: "transaction_date",
  "-TRANSACTION_DATE": "-transaction_date",
  AMOUNT: "amount",
  "-AMOUNT": "-amount",
  DESCRIPTION: "description",
  "-DESCRIPTION": "-description",
} as const;

/**
 * TransactionSortProperty
 */
export type TransactionSortProperty =
  (typeof TransactionSortProperty)[keyof typeof TransactionSortProperty];

/**
 * TransactionUpdate
 */
export type TransactionUpdate = {
  /**
   * Category Id
   *
   * Category ID to assign.
   */
  category_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type HealthzHealthzGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/healthz";
};

export type HealthzHealthzGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListBankAccountsV1BankAccountsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<BankAccountSortProperty> | null;
  };
  url: "/v1/bank-accounts";
};

export type ListBankAccountsV1BankAccountsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListBankAccountsV1BankAccountsGetError =
  ListBankAccountsV1BankAccountsGetErrors[keyof ListBankAccountsV1BankAccountsGetErrors];

export type ListBankAccountsV1BankAccountsGetResponses = {
  /**
   * Successful Response
   */
  200: BankAccountListResponse;
};

export type ListBankAccountsV1BankAccountsGetResponse =
  ListBankAccountsV1BankAccountsGetResponses[keyof ListBankAccountsV1BankAccountsGetResponses];

export type CreateBankAccountV1BankAccountsPostData = {
  body: BankAccountCreate;
  path?: never;
  query?: never;
  url: "/v1/bank-accounts";
};

export type CreateBankAccountV1BankAccountsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBankAccountV1BankAccountsPostError =
  CreateBankAccountV1BankAccountsPostErrors[keyof CreateBankAccountV1BankAccountsPostErrors];

export type CreateBankAccountV1BankAccountsPostResponses = {
  /**
   * Successful Response
   */
  201: BankAccountSchema;
};

export type CreateBankAccountV1BankAccountsPostResponse =
  CreateBankAccountV1BankAccountsPostResponses[keyof CreateBankAccountV1BankAccountsPostResponses];

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteData = {
  body?: never;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteError =
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors[keyof DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors];

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse =
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses[keyof DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses];

export type GetBankAccountV1BankAccountsBankAccountIdGetData = {
  body?: never;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type GetBankAccountV1BankAccountsBankAccountIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBankAccountV1BankAccountsBankAccountIdGetError =
  GetBankAccountV1BankAccountsBankAccountIdGetErrors[keyof GetBankAccountV1BankAccountsBankAccountIdGetErrors];

export type GetBankAccountV1BankAccountsBankAccountIdGetResponses = {
  /**
   * Successful Response
   */
  200: BankAccountSchema;
};

export type GetBankAccountV1BankAccountsBankAccountIdGetResponse =
  GetBankAccountV1BankAccountsBankAccountIdGetResponses[keyof GetBankAccountV1BankAccountsBankAccountIdGetResponses];

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchData = {
  body: BankAccountUpdate;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchError =
  UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors[keyof UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors];

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses = {
  /**
   * Successful Response
   */
  200: BankAccountSchema;
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse =
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses[keyof UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses];

export type ListCategoriesV1CategoriesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<CategorySortProperty> | null;
  };
  url: "/v1/categories";
};

export type ListCategoriesV1CategoriesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCategoriesV1CategoriesGetError =
  ListCategoriesV1CategoriesGetErrors[keyof ListCategoriesV1CategoriesGetErrors];

export type ListCategoriesV1CategoriesGetResponses = {
  /**
   * Successful Response
   */
  200: CategoryListResponse;
};

export type ListCategoriesV1CategoriesGetResponse =
  ListCategoriesV1CategoriesGetResponses[keyof ListCategoriesV1CategoriesGetResponses];

export type CreateCategoryV1CategoriesPostData = {
  body: CategoryCreate;
  path?: never;
  query?: never;
  url: "/v1/categories";
};

export type CreateCategoryV1CategoriesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCategoryV1CategoriesPostError =
  CreateCategoryV1CategoriesPostErrors[keyof CreateCategoryV1CategoriesPostErrors];

export type CreateCategoryV1CategoriesPostResponses = {
  /**
   * Successful Response
   */
  201: CategorySchema;
};

export type CreateCategoryV1CategoriesPostResponse =
  CreateCategoryV1CategoriesPostResponses[keyof CreateCategoryV1CategoriesPostResponses];

export type DeleteCategoryV1CategoriesCategoryIdDeleteData = {
  body?: never;
  path: {
    /**
     * Category Id
     */
    category_id: string;
  };
  query?: never;
  url: "/v1/categories/{category_id}";
};

export type DeleteCategoryV1CategoriesCategoryIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCategoryV1CategoriesCategoryIdDeleteError =
  DeleteCategoryV1CategoriesCategoryIdDeleteErrors[keyof DeleteCategoryV1CategoriesCategoryIdDeleteErrors];

export type DeleteCategoryV1CategoriesCategoryIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteCategoryV1CategoriesCategoryIdDeleteResponse =
  DeleteCategoryV1CategoriesCategoryIdDeleteResponses[keyof DeleteCategoryV1CategoriesCategoryIdDeleteResponses];

export type UpdateCategoryV1CategoriesCategoryIdPatchData = {
  body: CategoryUpdate;
  path: {
    /**
     * Category Id
     */
    category_id: string;
  };
  query?: never;
  url: "/v1/categories/{category_id}";
};

export type UpdateCategoryV1CategoriesCategoryIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCategoryV1CategoriesCategoryIdPatchError =
  UpdateCategoryV1CategoriesCategoryIdPatchErrors[keyof UpdateCategoryV1CategoriesCategoryIdPatchErrors];

export type UpdateCategoryV1CategoriesCategoryIdPatchResponses = {
  /**
   * Successful Response
   */
  200: CategorySchema;
};

export type UpdateCategoryV1CategoriesCategoryIdPatchResponse =
  UpdateCategoryV1CategoriesCategoryIdPatchResponses[keyof UpdateCategoryV1CategoriesCategoryIdPatchResponses];

export type ListPlacesV1PlacesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     *
     * Filter by status.
     */
    status?: PlaceStatus | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<PlaceSortProperty> | null;
  };
  url: "/v1/places";
};

export type ListPlacesV1PlacesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListPlacesV1PlacesGetError =
  ListPlacesV1PlacesGetErrors[keyof ListPlacesV1PlacesGetErrors];

export type ListPlacesV1PlacesGetResponses = {
  /**
   * Successful Response
   */
  200: PlaceListResponse;
};

export type ListPlacesV1PlacesGetResponse =
  ListPlacesV1PlacesGetResponses[keyof ListPlacesV1PlacesGetResponses];

export type CreatePlaceV1PlacesPostData = {
  body: PlaceCreate;
  path?: never;
  query?: never;
  url: "/v1/places";
};

export type CreatePlaceV1PlacesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePlaceV1PlacesPostError =
  CreatePlaceV1PlacesPostErrors[keyof CreatePlaceV1PlacesPostErrors];

export type CreatePlaceV1PlacesPostResponses = {
  /**
   * Successful Response
   */
  201: PlaceSchema;
};

export type CreatePlaceV1PlacesPostResponse =
  CreatePlaceV1PlacesPostResponses[keyof CreatePlaceV1PlacesPostResponses];

export type SearchGooglePlacesV1PlacesSearchGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query
     *
     * Search query for Google Places.
     */
    query: string;
  };
  url: "/v1/places/search";
};

export type SearchGooglePlacesV1PlacesSearchGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchGooglePlacesV1PlacesSearchGetError =
  SearchGooglePlacesV1PlacesSearchGetErrors[keyof SearchGooglePlacesV1PlacesSearchGetErrors];

export type SearchGooglePlacesV1PlacesSearchGetResponses = {
  /**
   * Successful Response
   */
  200: GooglePlaceSearchResponse;
};

export type SearchGooglePlacesV1PlacesSearchGetResponse =
  SearchGooglePlacesV1PlacesSearchGetResponses[keyof SearchGooglePlacesV1PlacesSearchGetResponses];

export type DeletePlaceV1PlacesPlaceIdDeleteData = {
  body?: never;
  path: {
    /**
     * Place Id
     */
    place_id: string;
  };
  query?: never;
  url: "/v1/places/{place_id}";
};

export type DeletePlaceV1PlacesPlaceIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePlaceV1PlacesPlaceIdDeleteError =
  DeletePlaceV1PlacesPlaceIdDeleteErrors[keyof DeletePlaceV1PlacesPlaceIdDeleteErrors];

export type DeletePlaceV1PlacesPlaceIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeletePlaceV1PlacesPlaceIdDeleteResponse =
  DeletePlaceV1PlacesPlaceIdDeleteResponses[keyof DeletePlaceV1PlacesPlaceIdDeleteResponses];

export type UpdatePlaceV1PlacesPlaceIdPatchData = {
  body: PlaceUpdate;
  path: {
    /**
     * Place Id
     */
    place_id: string;
  };
  query?: never;
  url: "/v1/places/{place_id}";
};

export type UpdatePlaceV1PlacesPlaceIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePlaceV1PlacesPlaceIdPatchError =
  UpdatePlaceV1PlacesPlaceIdPatchErrors[keyof UpdatePlaceV1PlacesPlaceIdPatchErrors];

export type UpdatePlaceV1PlacesPlaceIdPatchResponses = {
  /**
   * Successful Response
   */
  200: PlaceSchema;
};

export type UpdatePlaceV1PlacesPlaceIdPatchResponse =
  UpdatePlaceV1PlacesPlaceIdPatchResponses[keyof UpdatePlaceV1PlacesPlaceIdPatchResponses];

export type DeleteTransactionsV1TransactionsDeleteData = {
  body: BulkDeleteRequest;
  path?: never;
  query?: never;
  url: "/v1/transactions";
};

export type DeleteTransactionsV1TransactionsDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTransactionsV1TransactionsDeleteError =
  DeleteTransactionsV1TransactionsDeleteErrors[keyof DeleteTransactionsV1TransactionsDeleteErrors];

export type DeleteTransactionsV1TransactionsDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTransactionsV1TransactionsDeleteResponse =
  DeleteTransactionsV1TransactionsDeleteResponses[keyof DeleteTransactionsV1TransactionsDeleteResponses];

export type ListTransactionsV1TransactionsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Bank Account Id
     *
     * Filter by bank account ID.
     */
    bank_account_id?: string | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<TransactionSortProperty> | null;
  };
  url: "/v1/transactions";
};

export type ListTransactionsV1TransactionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTransactionsV1TransactionsGetError =
  ListTransactionsV1TransactionsGetErrors[keyof ListTransactionsV1TransactionsGetErrors];

export type ListTransactionsV1TransactionsGetResponses = {
  /**
   * Successful Response
   */
  200: TransactionListResponse;
};

export type ListTransactionsV1TransactionsGetResponse =
  ListTransactionsV1TransactionsGetResponses[keyof ListTransactionsV1TransactionsGetResponses];

export type ImportTransactionsV1TransactionsImportPostData = {
  body: BodyImportTransactionsV1TransactionsImportPost;
  path?: never;
  query: {
    /**
     * Bank
     *
     * Bank identifier, e.g. 'marginalen'.
     */
    bank: string;
    /**
     * Bank Account Id
     *
     * Bank account to attach transactions to.
     */
    bank_account_id: string;
  };
  url: "/v1/transactions/import";
};

export type ImportTransactionsV1TransactionsImportPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportTransactionsV1TransactionsImportPostError =
  ImportTransactionsV1TransactionsImportPostErrors[keyof ImportTransactionsV1TransactionsImportPostErrors];

export type ImportTransactionsV1TransactionsImportPostResponses = {
  /**
   * Successful Response
   */
  200: ImportResponse;
};

export type ImportTransactionsV1TransactionsImportPostResponse =
  ImportTransactionsV1TransactionsImportPostResponses[keyof ImportTransactionsV1TransactionsImportPostResponses];

export type UpdateTransactionV1TransactionsTransactionIdPatchData = {
  body: TransactionUpdate;
  path: {
    /**
     * Transaction Id
     */
    transaction_id: string;
  };
  query?: never;
  url: "/v1/transactions/{transaction_id}";
};

export type UpdateTransactionV1TransactionsTransactionIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTransactionV1TransactionsTransactionIdPatchError =
  UpdateTransactionV1TransactionsTransactionIdPatchErrors[keyof UpdateTransactionV1TransactionsTransactionIdPatchErrors];

export type UpdateTransactionV1TransactionsTransactionIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TransactionSchema;
};

export type UpdateTransactionV1TransactionsTransactionIdPatchResponse =
  UpdateTransactionV1TransactionsTransactionIdPatchResponses[keyof UpdateTransactionV1TransactionsTransactionIdPatchResponses];
