// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.metron.sh" | (string & {});
};

/**
 * ActivityBatchRequest
 */
export type ActivityBatchRequest = {
  /**
   * Source
   *
   * Machine identifier, e.g. hostname.
   */
  source: string;
  /**
   * Events
   *
   * Batch of events to ingest.
   */
  events: Array<ActivityEventIn>;
};

/**
 * ActivityBatchResponse
 */
export type ActivityBatchResponse = {
  /**
   * Inserted
   *
   * Number of new events inserted.
   */
  inserted: number;
  /**
   * Skipped
   *
   * Number of duplicate events skipped.
   */
  skipped: number;
};

/**
 * ActivityEventIn
 */
export type ActivityEventIn = {
  /**
   * Local Id
   *
   * Original SQLite id from the source machine.
   */
  local_id: number;
  /**
   * Ts
   *
   * Unix epoch seconds (UTC) when the event was recorded.
   */
  ts: number;
  /**
   * State
   *
   * 'active' or 'idle'.
   */
  state: string;
  /**
   * App Class
   *
   * Window class / app identifier.
   */
  app_class?: string | null;
  /**
   * Title
   *
   * Window title.
   */
  title?: string | null;
  /**
   * Workspace
   *
   * Workspace name or number.
   */
  workspace?: string | null;
};

/**
 * AssetType
 */
export const AssetType = {
  STOCK: "stock",
  ETF: "etf",
  MUTUAL_FUND: "mutual_fund",
  BOND: "bond",
  CRYPTO: "crypto",
  REAL_ESTATE: "real_estate",
  OTHER: "other",
} as const;

/**
 * AssetType
 */
export type AssetType = (typeof AssetType)[keyof typeof AssetType];

/**
 * BankAccountCreate
 */
export type BankAccountCreate = {
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name: string;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance?: number;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype: string;
};

/**
 * BankAccountListResponse
 */
export type BankAccountListResponse = {
  /**
   * Items
   */
  items: Array<BankAccountSchema>;
  pagination: Pagination;
};

/**
 * BankAccountSchema
 */
export type BankAccountSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name: string;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance: number;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype: string;
  /**
   * Current Balance
   *
   * Current balance in minor units (base_balance + credits - debits).
   */
  current_balance?: number;
};

/**
 * BankAccountSortProperty
 */
export const BankAccountSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  NAME: "name",
  "-NAME": "-name",
} as const;

/**
 * BankAccountSortProperty
 */
export type BankAccountSortProperty =
  (typeof BankAccountSortProperty)[keyof typeof BankAccountSortProperty];

/**
 * BankAccountUpdate
 */
export type BankAccountUpdate = {
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name?: string | null;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency?: string | null;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance?: number | null;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype?: string | null;
};

/**
 * Body_import_transactions_v1_transactions_import_post
 */
export type BodyImportTransactionsV1TransactionsImportPost = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * BulkCategorizeRequest
 */
export type BulkCategorizeRequest = {
  /**
   * Description
   *
   * Exact description to match.
   */
  description: string;
  /**
   * Category Id
   *
   * Category ID to assign.
   */
  category_id: string | null;
};

/**
 * BulkCategorizeResponse
 */
export type BulkCategorizeResponse = {
  /**
   * Updated
   *
   * Number of transactions updated.
   */
  updated: number;
};

/**
 * BulkDeleteRequest
 */
export type BulkDeleteRequest = {
  /**
   * Ids
   *
   * List of transaction IDs to delete.
   */
  ids: Array<string>;
};

/**
 * BulkUpdateRequest
 */
export type BulkUpdateRequest = {
  /**
   * Ids
   *
   * List of transaction IDs to update.
   */
  ids: Array<string>;
  /**
   * Category Id
   *
   * Category ID to assign to all.
   */
  category_id?: string | null;
};

/**
 * BulkUpdateResponse
 */
export type BulkUpdateResponse = {
  /**
   * Updated
   *
   * Number of transactions updated.
   */
  updated: number;
};

/**
 * CategoryListResponse
 */
export type CategoryListResponse = {
  /**
   * Items
   */
  items: Array<CategorySchema>;
  pagination: Pagination;
};

/**
 * CategorySchema
 */
export type CategorySchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Category name.
   */
  name: string;
  /**
   * Slug
   *
   * URL-friendly identifier.
   */
  slug: string;
  /**
   * Color
   *
   * Hex color code for UI display.
   */
  color: string;
  /**
   * Excluded
   *
   * Whether this category is excluded from reports.
   */
  excluded: boolean;
  /**
   * Parent Id
   *
   * Parent category ID, null for top-level.
   */
  parent_id?: string | null;
};

/**
 * CategorySpending
 */
export type CategorySpending = {
  /**
   * Category Id
   *
   * Category ID.
   */
  category_id: string;
  /**
   * Category Name
   *
   * Category name.
   */
  category_name: string;
  /**
   * Category Color
   *
   * Category hex color.
   */
  category_color: string;
  /**
   * Total
   *
   * Total spending in minor units (cents).
   */
  total: number;
};

/**
 * Equipment
 */
export const Equipment = {
  BARBELL: "barbell",
  DUMBBELL: "dumbbell",
  CABLE: "cable",
  MACHINE: "machine",
  BODYWEIGHT: "bodyweight",
  KETTLEBELL: "kettlebell",
  BAND: "band",
  OTHER: "other",
} as const;

/**
 * Equipment
 */
export type Equipment = (typeof Equipment)[keyof typeof Equipment];

/**
 * ExerciseCreate
 */
export type ExerciseCreate = {
  /**
   * Name
   */
  name: string;
  category: MuscleCategory;
  equipment: Equipment;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ExerciseListResponse
 */
export type ExerciseListResponse = {
  /**
   * Items
   */
  items: Array<ExerciseSchema>;
  pagination: Pagination;
};

/**
 * ExercisePRListResponse
 */
export type ExercisePrListResponse = {
  /**
   * Items
   */
  items: Array<ExercisePrSchema>;
};

/**
 * ExercisePRSchema
 */
export type ExercisePrSchema = {
  /**
   * Exercise Id
   */
  exercise_id: string;
  /**
   * Exercise Name
   */
  exercise_name: string;
  /**
   * Reps
   */
  reps: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Weight Unit
   */
  weight_unit: string;
  /**
   * Achieved At
   */
  achieved_at: Date;
};

/**
 * ExerciseSchema
 */
export type ExerciseSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   */
  name: string;
  category: MuscleCategory;
  equipment: Equipment;
  /**
   * Description
   */
  description: string | null;
  /**
   * Is Custom
   */
  is_custom: boolean;
};

/**
 * GooglePlaceSearchResponse
 */
export type GooglePlaceSearchResponse = {
  /**
   * Results
   */
  results: Array<GooglePlaceSearchResult>;
};

/**
 * GooglePlaceSearchResult
 */
export type GooglePlaceSearchResult = {
  /**
   * Place Id
   *
   * Google Place ID.
   */
  place_id: string;
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   *
   * Formatted address.
   */
  address: string;
  /**
   * Country
   *
   * Country name.
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude.
   */
  longitude: number;
  /**
   * Plus Code
   *
   * Plus Code.
   */
  plus_code?: string | null;
  /**
   * Category
   *
   * Primary type.
   */
  category?: string | null;
  /**
   * Photo Url
   *
   * Photo reference URL.
   */
  photo_url?: string | null;
  /**
   * Website
   *
   * Website.
   */
  website?: string | null;
  /**
   * Phone
   *
   * Phone number.
   */
  phone?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HoldingSchema
 */
export type HoldingSchema = {
  /**
   * Security Id
   */
  security_id: string;
  /**
   * Security Name
   */
  security_name: string;
  /**
   * Ticker
   */
  ticker: string | null;
  asset_type: AssetType;
  /**
   * Currency
   */
  currency: string;
  /**
   * Quantity
   *
   * Net quantity in micro-units (x1,000,000).
   */
  quantity: number;
  /**
   * Avg Cost Per Unit
   *
   * Average cost per unit in minor units (cents).
   */
  avg_cost_per_unit: number;
  /**
   * Cost Basis
   *
   * Total cost basis in minor units (cents).
   */
  cost_basis: number;
  /**
   * Current Price
   *
   * Latest price per unit in minor units, or null if no price recorded.
   */
  current_price: number | null;
  /**
   * Current Value
   *
   * Current value in minor units, or null if no price recorded.
   */
  current_value: number | null;
  /**
   * Gain Loss
   *
   * Unrealized gain/loss in minor units, or null if no price.
   */
  gain_loss: number | null;
  /**
   * Gain Loss Pct
   *
   * Unrealized gain/loss percentage, or null if no price or zero cost.
   */
  gain_loss_pct: number | null;
};

/**
 * HoldingsResponse
 */
export type HoldingsResponse = {
  /**
   * Items
   */
  items: Array<HoldingSchema>;
};

/**
 * ImportResponse
 */
export type ImportResponse = {
  /**
   * Created
   *
   * Number of new transactions imported.
   */
  created: number;
  /**
   * Skipped
   *
   * Number of duplicate transactions skipped.
   */
  skipped: number;
};

/**
 * JournalCalendarDay
 */
export type JournalCalendarDay = {
  /**
   * Entry Date
   */
  entry_date: Date;
  /**
   * Has Morning
   */
  has_morning?: boolean;
  /**
   * Has Audit
   */
  has_audit?: boolean;
};

/**
 * JournalCalendarResponse
 */
export type JournalCalendarResponse = {
  /**
   * Days
   */
  days: Array<JournalCalendarDay>;
};

/**
 * JournalEntryListResponse
 */
export type JournalEntryListResponse = {
  /**
   * Items
   */
  items: Array<JournalEntrySchema>;
  pagination: Pagination;
};

/**
 * JournalEntrySchema
 */
export type JournalEntrySchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Entry Date
   *
   * Calendar date for this entry.
   */
  entry_date: Date;
  /**
   * Priority
   *
   * The one thing today.
   */
  priority?: string | null;
  /**
   * Friction
   *
   * What might stop me.
   */
  friction?: string | null;
  /**
   * Gratitude 1
   *
   * Gratitude bullet 1.
   */
  gratitude_1?: string | null;
  /**
   * Gratitude 2
   *
   * Gratitude bullet 2.
   */
  gratitude_2?: string | null;
  /**
   * Gratitude 3
   *
   * Gratitude bullet 3.
   */
  gratitude_3?: string | null;
  /**
   * Morning Committed At
   *
   * When morning was committed.
   */
  morning_committed_at?: Date | null;
  /**
   * Captures
   *
   * Captured thoughts.
   */
  captures?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Scorecard
   *
   * Day rating 1-5.
   */
  scorecard?: number | null;
  /**
   * Priority Done
   *
   * Did the priority get done.
   */
  priority_done?: boolean | null;
  /**
   * Insight
   *
   * What did I learn today.
   */
  insight?: string | null;
  /**
   * Seed
   *
   * Problem for tomorrow.
   */
  seed?: string | null;
};

/**
 * JournalEntryUpsert
 */
export type JournalEntryUpsert = {
  /**
   * Priority
   */
  priority?: string | null;
  /**
   * Friction
   */
  friction?: string | null;
  /**
   * Gratitude 1
   */
  gratitude_1?: string | null;
  /**
   * Gratitude 2
   */
  gratitude_2?: string | null;
  /**
   * Gratitude 3
   */
  gratitude_3?: string | null;
  /**
   * Morning Committed At
   */
  morning_committed_at?: Date | null;
  /**
   * Captures
   */
  captures?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Scorecard
   */
  scorecard?: number | null;
  /**
   * Priority Done
   */
  priority_done?: boolean | null;
  /**
   * Insight
   */
  insight?: string | null;
  /**
   * Seed
   */
  seed?: string | null;
};

/**
 * JournalSortProperty
 */
export const JournalSortProperty = {
  ENTRY_DATE: "entry_date",
  "-ENTRY_DATE": "-entry_date",
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
} as const;

/**
 * JournalSortProperty
 */
export type JournalSortProperty =
  (typeof JournalSortProperty)[keyof typeof JournalSortProperty];

/**
 * JournalStreakResponse
 */
export type JournalStreakResponse = {
  /**
   * Current Streak
   */
  current_streak: number;
  /**
   * Longest Streak
   */
  longest_streak: number;
  /**
   * Total Entries
   */
  total_entries: number;
};

/**
 * KlarnaImportRequest
 */
export type KlarnaImportRequest = {
  /**
   * Bank Account Id
   */
  bank_account_id: string;
  /**
   * Authorization
   */
  authorization: string;
  /**
   * Cookie
   */
  cookie?: string | null;
};

/**
 * LastSessionBestSet
 */
export type LastSessionBestSet = {
  /**
   * Weight
   */
  weight: number;
  /**
   * Reps
   */
  reps: number;
  /**
   * Weight Unit
   */
  weight_unit: string;
};

/**
 * LastSessionResponse
 */
export type LastSessionResponse = {
  /**
   * Sets
   */
  sets: Array<LastSessionSetSchema>;
  best_set: LastSessionBestSet | null;
};

/**
 * LastSessionSetSchema
 */
export type LastSessionSetSchema = {
  /**
   * Set Number
   */
  set_number: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Reps
   */
  reps: number;
  /**
   * Weight Unit
   */
  weight_unit: string;
  /**
   * Rir
   */
  rir: number | null;
  /**
   * Set Type
   */
  set_type: string | null;
};

/**
 * MonthlyFlow
 */
export type MonthlyFlow = {
  /**
   * Year
   */
  year: number;
  /**
   * Month
   */
  month: number;
  /**
   * Income
   *
   * Total credit amount in minor units.
   */
  income: number;
  /**
   * Expenses
   *
   * Total debit amount in minor units.
   */
  expenses: number;
};

/**
 * MonthlyFlowResponse
 */
export type MonthlyFlowResponse = {
  /**
   * Items
   *
   * Monthly income/expenses, ordered chronologically.
   */
  items: Array<MonthlyFlow>;
};

/**
 * MonthlySpendingResponse
 */
export type MonthlySpendingResponse = {
  /**
   * Year
   */
  year: number;
  /**
   * Month
   */
  month: number;
  /**
   * Items
   *
   * Spending per category, sorted descending by total.
   */
  items: Array<CategorySpending>;
};

/**
 * MuscleCategory
 */
export const MuscleCategory = {
  CHEST: "chest",
  BACK: "back",
  SHOULDERS: "shoulders",
  BICEPS: "biceps",
  TRICEPS: "triceps",
  FOREARMS: "forearms",
  CORE: "core",
  QUADS: "quads",
  HAMSTRINGS: "hamstrings",
  GLUTES: "glutes",
  CALVES: "calves",
  CARDIO: "cardio",
  OLYMPIC: "olympic",
  OTHER: "other",
} as const;

/**
 * MuscleCategory
 */
export type MuscleCategory =
  (typeof MuscleCategory)[keyof typeof MuscleCategory];

/**
 * Pagination
 */
export type Pagination = {
  /**
   * Total Count
   */
  total_count: number;
  /**
   * Max Page
   */
  max_page: number;
};

/**
 * PlaceCreate
 */
export type PlaceCreate = {
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Country
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude coordinate.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude coordinate.
   */
  longitude: number;
  /**
   * Google Place Id
   */
  google_place_id?: string | null;
  /**
   * Plus Code
   */
  plus_code?: string | null;
  status?: PlaceStatus;
  /**
   * Rating
   */
  rating?: number | null;
  /**
   * Visited At
   */
  visited_at?: Date | null;
  /**
   * Review
   */
  review?: string | null;
  /**
   * Category
   */
  category?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   */
  photo_url?: string | null;
  /**
   * Website
   */
  website?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * PlaceListResponse
 */
export type PlaceListResponse = {
  /**
   * Items
   */
  items: Array<PlaceSchema>;
  pagination: Pagination;
};

/**
 * PlaceSchema
 */
export type PlaceSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   *
   * Full address.
   */
  address?: string | null;
  /**
   * Country
   *
   * Country name.
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude coordinate.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude coordinate.
   */
  longitude: number;
  /**
   * Google Place Id
   *
   * Google Maps place ID.
   */
  google_place_id?: string | null;
  /**
   * Plus Code
   *
   * Google Plus Code.
   */
  plus_code?: string | null;
  /**
   * Place status.
   */
  status?: PlaceStatus;
  /**
   * Rating
   *
   * Personal rating (1-5).
   */
  rating?: number | null;
  /**
   * Visited At
   *
   * Date when the place was visited.
   */
  visited_at?: Date | null;
  /**
   * Review
   *
   * Personal review/notes.
   */
  review?: string | null;
  /**
   * Category
   *
   * Place category (e.g. restaurant, cafe).
   */
  category?: string | null;
  /**
   * Tags
   *
   * User-defined tags.
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   *
   * Photo URL from Google.
   */
  photo_url?: string | null;
  /**
   * Website
   *
   * Website URL.
   */
  website?: string | null;
  /**
   * Phone
   *
   * Phone number.
   */
  phone?: string | null;
};

/**
 * PlaceSortProperty
 */
export const PlaceSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  NAME: "name",
  "-NAME": "-name",
  RATING: "rating",
  "-RATING": "-rating",
  VISITED_AT: "visited_at",
  "-VISITED_AT": "-visited_at",
} as const;

/**
 * PlaceSortProperty
 */
export type PlaceSortProperty =
  (typeof PlaceSortProperty)[keyof typeof PlaceSortProperty];

/**
 * PlaceStatus
 */
export const PlaceStatus = {
  WANT_TO_GO: "want_to_go",
  VISITED: "visited",
} as const;

/**
 * PlaceStatus
 */
export type PlaceStatus = (typeof PlaceStatus)[keyof typeof PlaceStatus];

/**
 * PlaceUpdate
 */
export type PlaceUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Country
   */
  country?: string | null;
  /**
   * Latitude
   */
  latitude?: number | null;
  /**
   * Longitude
   */
  longitude?: number | null;
  status?: PlaceStatus | null;
  /**
   * Rating
   */
  rating?: number | null;
  /**
   * Visited At
   */
  visited_at?: Date | null;
  /**
   * Review
   */
  review?: string | null;
  /**
   * Category
   */
  category?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   */
  photo_url?: string | null;
  /**
   * Website
   */
  website?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * RruleFrequency
 */
export const RruleFrequency = {
  DAILY: "daily",
  WEEKLY: "weekly",
  MONTHLY: "monthly",
  YEARLY: "yearly",
} as const;

/**
 * RruleFrequency
 */
export type RruleFrequency =
  (typeof RruleFrequency)[keyof typeof RruleFrequency];

/**
 * SecurityCreate
 */
export type SecurityCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Ticker
   */
  ticker?: string | null;
  asset_type: AssetType;
  /**
   * Currency
   */
  currency: string;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * SecurityListResponse
 */
export type SecurityListResponse = {
  /**
   * Items
   */
  items: Array<SecuritySchema>;
  pagination: Pagination;
};

/**
 * SecurityPriceCreate
 */
export type SecurityPriceCreate = {
  /**
   * Price Date
   */
  price_date: Date;
  /**
   * Price Per Unit
   *
   * Price in minor units (cents).
   */
  price_per_unit: number;
  /**
   * Currency
   */
  currency: string;
};

/**
 * SecurityPriceListResponse
 */
export type SecurityPriceListResponse = {
  /**
   * Items
   */
  items: Array<SecurityPriceSchema>;
  pagination: Pagination;
};

/**
 * SecurityPriceSchema
 */
export type SecurityPriceSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Security Id
   */
  security_id: string;
  /**
   * Price Date
   */
  price_date: Date;
  /**
   * Price Per Unit
   *
   * Price in minor units (cents).
   */
  price_per_unit: number;
  /**
   * Currency
   */
  currency: string;
};

/**
 * SecuritySchema
 */
export type SecuritySchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Ticker
   */
  ticker: string | null;
  asset_type: AssetType;
  /**
   * Currency
   */
  currency: string;
  /**
   * Notes
   */
  notes: string | null;
};

/**
 * SecurityUpdate
 */
export type SecurityUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Ticker
   */
  ticker?: string | null;
  asset_type?: AssetType | null;
  /**
   * Currency
   */
  currency?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * TaskCompleteResponse
 */
export type TaskCompleteResponse = {
  completed_task: TaskSchema;
  /**
   * Next recurring instance, if applicable.
   */
  next_task?: TaskSchema | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
  /**
   * Title
   *
   * Task title.
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  status?: TaskStatus;
  /**
   * Priority
   */
  priority?: number;
  /**
   * Due Date
   */
  due_date?: Date | null;
  /**
   * Project
   */
  project?: string | null;
  /**
   * Area
   */
  area?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Position
   */
  position?: number;
  /**
   * Is Recurring
   */
  is_recurring?: boolean;
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   */
  rrule_day_of_month?: number | null;
};

/**
 * TaskListResponse
 */
export type TaskListResponse = {
  /**
   * Items
   */
  items: Array<TaskSchema>;
  pagination: Pagination;
};

/**
 * TaskReorderItem
 */
export type TaskReorderItem = {
  /**
   * Id
   */
  id: string;
  /**
   * Position
   */
  position: number;
  status?: TaskStatus | null;
};

/**
 * TaskSchema
 */
export type TaskSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Title
   *
   * Task title.
   */
  title: string;
  /**
   * Description
   *
   * Task description.
   */
  description?: string | null;
  /**
   * Task status.
   */
  status?: TaskStatus;
  /**
   * Priority
   *
   * Priority (0=none, 1=low, 2=medium, 3=high, 4=urgent).
   */
  priority?: number;
  /**
   * Due Date
   *
   * Due date.
   */
  due_date?: Date | null;
  /**
   * Completed At
   *
   * Completion timestamp.
   */
  completed_at?: Date | null;
  /**
   * Project
   *
   * Project name.
   */
  project?: string | null;
  /**
   * Area
   *
   * Area (e.g. Company, Personal, Travel).
   */
  area?: string | null;
  /**
   * Tags
   *
   * User-defined tags.
   */
  tags?: Array<string> | null;
  /**
   * Position
   *
   * Position for ordering within a status column.
   */
  position?: number;
  /**
   * Is Recurring
   *
   * Whether this task recurs.
   */
  is_recurring?: boolean;
  /**
   * Recurrence frequency.
   */
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   *
   * Recurrence interval.
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   *
   * Day of week for weekly recurrence (0=Mon, 6=Sun).
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   *
   * Day of month for monthly recurrence (1-31).
   */
  rrule_day_of_month?: number | null;
  /**
   * Parent Task Id
   *
   * Parent task ID for recurring chain.
   */
  parent_task_id?: string | null;
};

/**
 * TaskSortProperty
 */
export const TaskSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  DUE_DATE: "due_date",
  "-DUE_DATE": "-due_date",
  PRIORITY: "priority",
  "-PRIORITY": "-priority",
  TITLE: "title",
  "-TITLE": "-title",
  COMPLETED_AT: "completed_at",
  "-COMPLETED_AT": "-completed_at",
  POSITION: "position",
  "-POSITION": "-position",
} as const;

/**
 * TaskSortProperty
 */
export type TaskSortProperty =
  (typeof TaskSortProperty)[keyof typeof TaskSortProperty];

/**
 * TaskStatus
 */
export const TaskStatus = {
  TODO: "todo",
  IN_PROGRESS: "in_progress",
  DONE: "done",
  CANCELLED: "cancelled",
} as const;

/**
 * TaskStatus
 */
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

/**
 * TaskUpdate
 */
export type TaskUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  status?: TaskStatus | null;
  /**
   * Priority
   */
  priority?: number | null;
  /**
   * Due Date
   */
  due_date?: Date | null;
  /**
   * Project
   */
  project?: string | null;
  /**
   * Area
   */
  area?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Position
   */
  position?: number | null;
  /**
   * Is Recurring
   */
  is_recurring?: boolean | null;
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   */
  rrule_day_of_month?: number | null;
};

/**
 * TradeCreate
 */
export type TradeCreate = {
  /**
   * Security Id
   */
  security_id: string;
  /**
   * Bank Account Id
   */
  bank_account_id: string;
  trade_type: TradeType;
  /**
   * Trade Date
   */
  trade_date: Date;
  /**
   * Quantity
   *
   * Quantity in micro-units (x1,000,000).
   */
  quantity: number;
  /**
   * Price Per Unit
   *
   * Price per unit in minor units (cents).
   */
  price_per_unit: number;
  /**
   * Currency
   */
  currency: string;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * TradeListResponse
 */
export type TradeListResponse = {
  /**
   * Items
   */
  items: Array<TradeSchema>;
  pagination: Pagination;
};

/**
 * TradeSchema
 */
export type TradeSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Security Id
   */
  security_id: string;
  /**
   * Bank Account Id
   */
  bank_account_id: string;
  trade_type: TradeType;
  /**
   * Trade Date
   */
  trade_date: Date;
  /**
   * Quantity
   *
   * Quantity in micro-units (x1,000,000).
   */
  quantity: number;
  /**
   * Price Per Unit
   *
   * Price per unit in minor units (cents).
   */
  price_per_unit: number;
  /**
   * Currency
   */
  currency: string;
  /**
   * Notes
   */
  notes: string | null;
};

/**
 * TradeType
 */
export const TradeType = { BUY: "buy", SELL: "sell" } as const;

/**
 * TradeType
 */
export type TradeType = (typeof TradeType)[keyof typeof TradeType];

/**
 * TradeUpdate
 */
export type TradeUpdate = {
  trade_type?: TradeType | null;
  /**
   * Trade Date
   */
  trade_date?: Date | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Price Per Unit
   */
  price_per_unit?: number | null;
  /**
   * Currency
   */
  currency?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * TransactionDirection
 */
export const TransactionDirection = {
  DEBIT: "debit",
  CREDIT: "credit",
} as const;

/**
 * TransactionDirection
 */
export type TransactionDirection =
  (typeof TransactionDirection)[keyof typeof TransactionDirection];

/**
 * TransactionListResponse
 */
export type TransactionListResponse = {
  /**
   * Items
   */
  items: Array<TransactionSchema>;
  pagination: Pagination;
};

/**
 * TransactionSchema
 */
export type TransactionSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Amount
   *
   * Amount in minor units (cents).
   */
  amount: number;
  /**
   * Currency
   */
  currency: string;
  /**
   * Transaction Date
   */
  transaction_date: Date;
  direction: TransactionDirection;
  /**
   * Description
   */
  description: string | null;
  /**
   * Category Id
   */
  category_id: string | null;
  /**
   * Transaction Type
   */
  transaction_type: string | null;
  /**
   * Dedup Hash
   */
  dedup_hash: string;
  /**
   * Bank Account Id
   */
  bank_account_id: string;
  /**
   * Raw Id
   */
  raw_id: string | null;
  /**
   * Is Business
   *
   * Whether this is a business transaction.
   */
  is_business?: boolean;
};

/**
 * TransactionSortProperty
 */
export const TransactionSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  TRANSACTION_DATE: "transaction_date",
  "-TRANSACTION_DATE": "-transaction_date",
  AMOUNT: "amount",
  "-AMOUNT": "-amount",
  DESCRIPTION: "description",
  "-DESCRIPTION": "-description",
} as const;

/**
 * TransactionSortProperty
 */
export type TransactionSortProperty =
  (typeof TransactionSortProperty)[keyof typeof TransactionSortProperty];

/**
 * TransactionUpdate
 */
export type TransactionUpdate = {
  /**
   * Category Id
   *
   * Category ID to assign.
   */
  category_id?: string | null;
  /**
   * Is Business
   *
   * Mark as a business transaction.
   */
  is_business?: boolean | null;
};

/**
 * TransactionUpdateResponse
 */
export type TransactionUpdateResponse = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Amount
   *
   * Amount in minor units (cents).
   */
  amount: number;
  /**
   * Currency
   */
  currency: string;
  /**
   * Transaction Date
   */
  transaction_date: Date;
  direction: TransactionDirection;
  /**
   * Description
   */
  description: string | null;
  /**
   * Category Id
   */
  category_id: string | null;
  /**
   * Transaction Type
   */
  transaction_type: string | null;
  /**
   * Dedup Hash
   */
  dedup_hash: string;
  /**
   * Bank Account Id
   */
  bank_account_id: string;
  /**
   * Raw Id
   */
  raw_id: string | null;
  /**
   * Is Business
   *
   * Whether this is a business transaction.
   */
  is_business?: boolean;
  /**
   * Same Description Count
   *
   * Number of other transactions with the same description not yet assigned this category.
   */
  same_description_count?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * WeatherDaySchema
 */
export type WeatherDaySchema = {
  /**
   * Date
   *
   * Date of the weather data.
   */
  date: Date;
  /**
   * Temperature Max
   *
   * Maximum temperature in Celsius.
   */
  temperature_max: number;
  /**
   * Temperature Min
   *
   * Minimum temperature in Celsius.
   */
  temperature_min: number;
  /**
   * Apparent Temperature Max
   *
   * Maximum feels-like temperature in Celsius.
   */
  apparent_temperature_max: number;
  /**
   * Precipitation Probability Max
   *
   * Maximum precipitation probability in percent.
   */
  precipitation_probability_max: number;
  /**
   * Weather Code
   *
   * WMO weather interpretation code.
   */
  weather_code: number;
  /**
   * Weather Label
   *
   * Human-readable weather condition.
   */
  weather_label: string;
};

/**
 * WeatherForecastResponse
 */
export type WeatherForecastResponse = {
  /**
   * Days
   *
   * 10-day weather forecast.
   */
  days: Array<WeatherDaySchema>;
};

/**
 * WorkoutLogCreate
 */
export type WorkoutLogCreate = {
  /**
   * Started At
   */
  started_at: Date;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * WorkoutLogDetailSchema
 */
export type WorkoutLogDetailSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Started At
   */
  started_at: Date;
  /**
   * Completed At
   */
  completed_at: Date | null;
  /**
   * Notes
   */
  notes: string | null;
  /**
   * Sets
   */
  sets: Array<WorkoutSetSchema>;
};

/**
 * WorkoutLogListResponse
 */
export type WorkoutLogListResponse = {
  /**
   * Items
   */
  items: Array<WorkoutLogSchema>;
  pagination: Pagination;
};

/**
 * WorkoutLogSchema
 */
export type WorkoutLogSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Started At
   */
  started_at: Date;
  /**
   * Completed At
   */
  completed_at: Date | null;
  /**
   * Notes
   */
  notes: string | null;
};

/**
 * WorkoutLogSortProperty
 */
export const WorkoutLogSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  STARTED_AT: "started_at",
  "-STARTED_AT": "-started_at",
} as const;

/**
 * WorkoutLogSortProperty
 */
export type WorkoutLogSortProperty =
  (typeof WorkoutLogSortProperty)[keyof typeof WorkoutLogSortProperty];

/**
 * WorkoutLogUpdate
 */
export type WorkoutLogUpdate = {
  /**
   * Completed At
   */
  completed_at?: Date | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * WorkoutSetCreate
 */
export type WorkoutSetCreate = {
  /**
   * Exercise Id
   */
  exercise_id: string;
  /**
   * Set Number
   */
  set_number: number;
  /**
   * Reps
   */
  reps: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Weight Unit
   */
  weight_unit?: string;
  /**
   * Rpe
   */
  rpe?: number | null;
  /**
   * Rir
   */
  rir?: number | null;
  /**
   * Set Type
   */
  set_type?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * WorkoutSetSchema
 */
export type WorkoutSetSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Workout Log Id
   */
  workout_log_id: string;
  /**
   * Exercise Id
   */
  exercise_id: string;
  /**
   * Set Number
   */
  set_number: number;
  /**
   * Reps
   */
  reps: number;
  /**
   * Weight
   */
  weight: number;
  /**
   * Weight Unit
   */
  weight_unit: string;
  /**
   * Rpe
   */
  rpe: number | null;
  /**
   * Rir
   */
  rir: number | null;
  /**
   * Set Type
   */
  set_type: string | null;
  /**
   * E1Rm
   */
  e1rm: number | null;
  /**
   * Is Pr
   */
  is_pr: boolean;
  /**
   * Notes
   */
  notes: string | null;
};

/**
 * WorkoutSetUpdate
 */
export type WorkoutSetUpdate = {
  /**
   * Reps
   */
  reps?: number | null;
  /**
   * Weight
   */
  weight?: number | null;
  /**
   * Weight Unit
   */
  weight_unit?: string | null;
  /**
   * Rpe
   */
  rpe?: number | null;
  /**
   * Rir
   */
  rir?: number | null;
  /**
   * Set Type
   */
  set_type?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
};

export type HealthzHealthzGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/healthz";
};

export type HealthzHealthzGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type IngestActivityBatchV1ActivityBatchPostData = {
  body: ActivityBatchRequest;
  path?: never;
  query?: never;
  url: "/v1/activity/batch";
};

export type IngestActivityBatchV1ActivityBatchPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type IngestActivityBatchV1ActivityBatchPostError =
  IngestActivityBatchV1ActivityBatchPostErrors[keyof IngestActivityBatchV1ActivityBatchPostErrors];

export type IngestActivityBatchV1ActivityBatchPostResponses = {
  /**
   * Successful Response
   */
  200: ActivityBatchResponse;
};

export type IngestActivityBatchV1ActivityBatchPostResponse =
  IngestActivityBatchV1ActivityBatchPostResponses[keyof IngestActivityBatchV1ActivityBatchPostResponses];

export type ListBankAccountsV1BankAccountsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<BankAccountSortProperty> | null;
  };
  url: "/v1/bank-accounts";
};

export type ListBankAccountsV1BankAccountsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListBankAccountsV1BankAccountsGetError =
  ListBankAccountsV1BankAccountsGetErrors[keyof ListBankAccountsV1BankAccountsGetErrors];

export type ListBankAccountsV1BankAccountsGetResponses = {
  /**
   * Successful Response
   */
  200: BankAccountListResponse;
};

export type ListBankAccountsV1BankAccountsGetResponse =
  ListBankAccountsV1BankAccountsGetResponses[keyof ListBankAccountsV1BankAccountsGetResponses];

export type CreateBankAccountV1BankAccountsPostData = {
  body: BankAccountCreate;
  path?: never;
  query?: never;
  url: "/v1/bank-accounts";
};

export type CreateBankAccountV1BankAccountsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBankAccountV1BankAccountsPostError =
  CreateBankAccountV1BankAccountsPostErrors[keyof CreateBankAccountV1BankAccountsPostErrors];

export type CreateBankAccountV1BankAccountsPostResponses = {
  /**
   * Successful Response
   */
  201: BankAccountSchema;
};

export type CreateBankAccountV1BankAccountsPostResponse =
  CreateBankAccountV1BankAccountsPostResponses[keyof CreateBankAccountV1BankAccountsPostResponses];

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteData = {
  body?: never;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteError =
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors[keyof DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors];

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse =
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses[keyof DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses];

export type GetBankAccountV1BankAccountsBankAccountIdGetData = {
  body?: never;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type GetBankAccountV1BankAccountsBankAccountIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBankAccountV1BankAccountsBankAccountIdGetError =
  GetBankAccountV1BankAccountsBankAccountIdGetErrors[keyof GetBankAccountV1BankAccountsBankAccountIdGetErrors];

export type GetBankAccountV1BankAccountsBankAccountIdGetResponses = {
  /**
   * Successful Response
   */
  200: BankAccountSchema;
};

export type GetBankAccountV1BankAccountsBankAccountIdGetResponse =
  GetBankAccountV1BankAccountsBankAccountIdGetResponses[keyof GetBankAccountV1BankAccountsBankAccountIdGetResponses];

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchData = {
  body: BankAccountUpdate;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchError =
  UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors[keyof UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors];

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses = {
  /**
   * Successful Response
   */
  200: BankAccountSchema;
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse =
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses[keyof UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses];

export type ListCategoriesV1CategoriesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
  };
  url: "/v1/categories";
};

export type ListCategoriesV1CategoriesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCategoriesV1CategoriesGetError =
  ListCategoriesV1CategoriesGetErrors[keyof ListCategoriesV1CategoriesGetErrors];

export type ListCategoriesV1CategoriesGetResponses = {
  /**
   * Successful Response
   */
  200: CategoryListResponse;
};

export type ListCategoriesV1CategoriesGetResponse =
  ListCategoriesV1CategoriesGetResponses[keyof ListCategoriesV1CategoriesGetResponses];

export type ListSecuritiesV1InvestmentsSecuritiesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
  };
  url: "/v1/investments/securities";
};

export type ListSecuritiesV1InvestmentsSecuritiesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSecuritiesV1InvestmentsSecuritiesGetError =
  ListSecuritiesV1InvestmentsSecuritiesGetErrors[keyof ListSecuritiesV1InvestmentsSecuritiesGetErrors];

export type ListSecuritiesV1InvestmentsSecuritiesGetResponses = {
  /**
   * Successful Response
   */
  200: SecurityListResponse;
};

export type ListSecuritiesV1InvestmentsSecuritiesGetResponse =
  ListSecuritiesV1InvestmentsSecuritiesGetResponses[keyof ListSecuritiesV1InvestmentsSecuritiesGetResponses];

export type CreateSecurityV1InvestmentsSecuritiesPostData = {
  body: SecurityCreate;
  path?: never;
  query?: never;
  url: "/v1/investments/securities";
};

export type CreateSecurityV1InvestmentsSecuritiesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSecurityV1InvestmentsSecuritiesPostError =
  CreateSecurityV1InvestmentsSecuritiesPostErrors[keyof CreateSecurityV1InvestmentsSecuritiesPostErrors];

export type CreateSecurityV1InvestmentsSecuritiesPostResponses = {
  /**
   * Successful Response
   */
  201: SecuritySchema;
};

export type CreateSecurityV1InvestmentsSecuritiesPostResponse =
  CreateSecurityV1InvestmentsSecuritiesPostResponses[keyof CreateSecurityV1InvestmentsSecuritiesPostResponses];

export type DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteData = {
  body?: never;
  path: {
    /**
     * Security Id
     */
    security_id: string;
  };
  query?: never;
  url: "/v1/investments/securities/{security_id}";
};

export type DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteError =
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteErrors[keyof DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteErrors];

export type DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponse =
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponses[keyof DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponses];

export type UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchData = {
  body: SecurityUpdate;
  path: {
    /**
     * Security Id
     */
    security_id: string;
  };
  query?: never;
  url: "/v1/investments/securities/{security_id}";
};

export type UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchError =
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchErrors[keyof UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchErrors];

export type UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponses = {
  /**
   * Successful Response
   */
  200: SecuritySchema;
};

export type UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponse =
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponses[keyof UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponses];

export type ListTradesV1InvestmentsTradesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Security Id
     */
    security_id?: string | null;
    /**
     * Bank Account Id
     */
    bank_account_id?: string | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
  };
  url: "/v1/investments/trades";
};

export type ListTradesV1InvestmentsTradesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTradesV1InvestmentsTradesGetError =
  ListTradesV1InvestmentsTradesGetErrors[keyof ListTradesV1InvestmentsTradesGetErrors];

export type ListTradesV1InvestmentsTradesGetResponses = {
  /**
   * Successful Response
   */
  200: TradeListResponse;
};

export type ListTradesV1InvestmentsTradesGetResponse =
  ListTradesV1InvestmentsTradesGetResponses[keyof ListTradesV1InvestmentsTradesGetResponses];

export type CreateTradeV1InvestmentsTradesPostData = {
  body: TradeCreate;
  path?: never;
  query?: never;
  url: "/v1/investments/trades";
};

export type CreateTradeV1InvestmentsTradesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTradeV1InvestmentsTradesPostError =
  CreateTradeV1InvestmentsTradesPostErrors[keyof CreateTradeV1InvestmentsTradesPostErrors];

export type CreateTradeV1InvestmentsTradesPostResponses = {
  /**
   * Successful Response
   */
  201: TradeSchema;
};

export type CreateTradeV1InvestmentsTradesPostResponse =
  CreateTradeV1InvestmentsTradesPostResponses[keyof CreateTradeV1InvestmentsTradesPostResponses];

export type DeleteTradeV1InvestmentsTradesTradeIdDeleteData = {
  body?: never;
  path: {
    /**
     * Trade Id
     */
    trade_id: string;
  };
  query?: never;
  url: "/v1/investments/trades/{trade_id}";
};

export type DeleteTradeV1InvestmentsTradesTradeIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTradeV1InvestmentsTradesTradeIdDeleteError =
  DeleteTradeV1InvestmentsTradesTradeIdDeleteErrors[keyof DeleteTradeV1InvestmentsTradesTradeIdDeleteErrors];

export type DeleteTradeV1InvestmentsTradesTradeIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTradeV1InvestmentsTradesTradeIdDeleteResponse =
  DeleteTradeV1InvestmentsTradesTradeIdDeleteResponses[keyof DeleteTradeV1InvestmentsTradesTradeIdDeleteResponses];

export type UpdateTradeV1InvestmentsTradesTradeIdPatchData = {
  body: TradeUpdate;
  path: {
    /**
     * Trade Id
     */
    trade_id: string;
  };
  query?: never;
  url: "/v1/investments/trades/{trade_id}";
};

export type UpdateTradeV1InvestmentsTradesTradeIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTradeV1InvestmentsTradesTradeIdPatchError =
  UpdateTradeV1InvestmentsTradesTradeIdPatchErrors[keyof UpdateTradeV1InvestmentsTradesTradeIdPatchErrors];

export type UpdateTradeV1InvestmentsTradesTradeIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TradeSchema;
};

export type UpdateTradeV1InvestmentsTradesTradeIdPatchResponse =
  UpdateTradeV1InvestmentsTradesTradeIdPatchResponses[keyof UpdateTradeV1InvestmentsTradesTradeIdPatchResponses];

export type ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData = {
  body?: never;
  path: {
    /**
     * Security Id
     */
    security_id: string;
  };
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
  };
  url: "/v1/investments/securities/{security_id}/prices";
};

export type ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetError =
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetErrors[keyof ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetErrors];

export type ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponses =
  {
    /**
     * Successful Response
     */
    200: SecurityPriceListResponse;
  };

export type ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse =
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponses[keyof ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponses];

export type CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostData =
  {
    body: SecurityPriceCreate;
    path: {
      /**
       * Security Id
       */
      security_id: string;
    };
    query?: never;
    url: "/v1/investments/securities/{security_id}/prices";
  };

export type CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostError =
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostErrors[keyof CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostErrors];

export type CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponses =
  {
    /**
     * Successful Response
     */
    201: SecurityPriceSchema;
  };

export type CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponse =
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponses[keyof CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponses];

export type GetHoldingsV1InvestmentsHoldingsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/investments/holdings";
};

export type GetHoldingsV1InvestmentsHoldingsGetResponses = {
  /**
   * Successful Response
   */
  200: HoldingsResponse;
};

export type GetHoldingsV1InvestmentsHoldingsGetResponse =
  GetHoldingsV1InvestmentsHoldingsGetResponses[keyof GetHoldingsV1InvestmentsHoldingsGetResponses];

export type ListEntriesV1JournalGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<JournalSortProperty> | null;
  };
  url: "/v1/journal";
};

export type ListEntriesV1JournalGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListEntriesV1JournalGetError =
  ListEntriesV1JournalGetErrors[keyof ListEntriesV1JournalGetErrors];

export type ListEntriesV1JournalGetResponses = {
  /**
   * Successful Response
   */
  200: JournalEntryListResponse;
};

export type ListEntriesV1JournalGetResponse =
  ListEntriesV1JournalGetResponses[keyof ListEntriesV1JournalGetResponses];

export type GetCalendarV1JournalCalendarGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Year
     *
     * Year.
     */
    year: number;
    /**
     * Month
     *
     * Month.
     */
    month: number;
  };
  url: "/v1/journal/calendar";
};

export type GetCalendarV1JournalCalendarGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCalendarV1JournalCalendarGetError =
  GetCalendarV1JournalCalendarGetErrors[keyof GetCalendarV1JournalCalendarGetErrors];

export type GetCalendarV1JournalCalendarGetResponses = {
  /**
   * Successful Response
   */
  200: JournalCalendarResponse;
};

export type GetCalendarV1JournalCalendarGetResponse =
  GetCalendarV1JournalCalendarGetResponses[keyof GetCalendarV1JournalCalendarGetResponses];

export type GetStreakV1JournalStreakGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/journal/streak";
};

export type GetStreakV1JournalStreakGetResponses = {
  /**
   * Successful Response
   */
  200: JournalStreakResponse;
};

export type GetStreakV1JournalStreakGetResponse =
  GetStreakV1JournalStreakGetResponses[keyof GetStreakV1JournalStreakGetResponses];

export type DeleteEntryV1JournalEntryDateDeleteData = {
  body?: never;
  path: {
    /**
     * Entry Date
     */
    entry_date: Date;
  };
  query?: never;
  url: "/v1/journal/{entry_date}";
};

export type DeleteEntryV1JournalEntryDateDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEntryV1JournalEntryDateDeleteError =
  DeleteEntryV1JournalEntryDateDeleteErrors[keyof DeleteEntryV1JournalEntryDateDeleteErrors];

export type DeleteEntryV1JournalEntryDateDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteEntryV1JournalEntryDateDeleteResponse =
  DeleteEntryV1JournalEntryDateDeleteResponses[keyof DeleteEntryV1JournalEntryDateDeleteResponses];

export type GetEntryV1JournalEntryDateGetData = {
  body?: never;
  path: {
    /**
     * Entry Date
     */
    entry_date: Date;
  };
  query?: never;
  url: "/v1/journal/{entry_date}";
};

export type GetEntryV1JournalEntryDateGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEntryV1JournalEntryDateGetError =
  GetEntryV1JournalEntryDateGetErrors[keyof GetEntryV1JournalEntryDateGetErrors];

export type GetEntryV1JournalEntryDateGetResponses = {
  /**
   * Response Get Entry V1 Journal  Entry Date  Get
   *
   * Successful Response
   */
  200: JournalEntrySchema | null;
};

export type GetEntryV1JournalEntryDateGetResponse =
  GetEntryV1JournalEntryDateGetResponses[keyof GetEntryV1JournalEntryDateGetResponses];

export type UpsertEntryV1JournalEntryDatePutData = {
  body: JournalEntryUpsert;
  path: {
    /**
     * Entry Date
     */
    entry_date: Date;
  };
  query?: never;
  url: "/v1/journal/{entry_date}";
};

export type UpsertEntryV1JournalEntryDatePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertEntryV1JournalEntryDatePutError =
  UpsertEntryV1JournalEntryDatePutErrors[keyof UpsertEntryV1JournalEntryDatePutErrors];

export type UpsertEntryV1JournalEntryDatePutResponses = {
  /**
   * Successful Response
   */
  200: JournalEntrySchema;
};

export type UpsertEntryV1JournalEntryDatePutResponse =
  UpsertEntryV1JournalEntryDatePutResponses[keyof UpsertEntryV1JournalEntryDatePutResponses];

export type ListPlacesV1PlacesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     *
     * Filter by status.
     */
    status?: PlaceStatus | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<PlaceSortProperty> | null;
  };
  url: "/v1/places";
};

export type ListPlacesV1PlacesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListPlacesV1PlacesGetError =
  ListPlacesV1PlacesGetErrors[keyof ListPlacesV1PlacesGetErrors];

export type ListPlacesV1PlacesGetResponses = {
  /**
   * Successful Response
   */
  200: PlaceListResponse;
};

export type ListPlacesV1PlacesGetResponse =
  ListPlacesV1PlacesGetResponses[keyof ListPlacesV1PlacesGetResponses];

export type CreatePlaceV1PlacesPostData = {
  body: PlaceCreate;
  path?: never;
  query?: never;
  url: "/v1/places";
};

export type CreatePlaceV1PlacesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePlaceV1PlacesPostError =
  CreatePlaceV1PlacesPostErrors[keyof CreatePlaceV1PlacesPostErrors];

export type CreatePlaceV1PlacesPostResponses = {
  /**
   * Successful Response
   */
  201: PlaceSchema;
};

export type CreatePlaceV1PlacesPostResponse =
  CreatePlaceV1PlacesPostResponses[keyof CreatePlaceV1PlacesPostResponses];

export type SearchGooglePlacesV1PlacesSearchGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query
     *
     * Search query for Google Places.
     */
    query: string;
  };
  url: "/v1/places/search";
};

export type SearchGooglePlacesV1PlacesSearchGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchGooglePlacesV1PlacesSearchGetError =
  SearchGooglePlacesV1PlacesSearchGetErrors[keyof SearchGooglePlacesV1PlacesSearchGetErrors];

export type SearchGooglePlacesV1PlacesSearchGetResponses = {
  /**
   * Successful Response
   */
  200: GooglePlaceSearchResponse;
};

export type SearchGooglePlacesV1PlacesSearchGetResponse =
  SearchGooglePlacesV1PlacesSearchGetResponses[keyof SearchGooglePlacesV1PlacesSearchGetResponses];

export type DeletePlaceV1PlacesPlaceIdDeleteData = {
  body?: never;
  path: {
    /**
     * Place Id
     */
    place_id: string;
  };
  query?: never;
  url: "/v1/places/{place_id}";
};

export type DeletePlaceV1PlacesPlaceIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePlaceV1PlacesPlaceIdDeleteError =
  DeletePlaceV1PlacesPlaceIdDeleteErrors[keyof DeletePlaceV1PlacesPlaceIdDeleteErrors];

export type DeletePlaceV1PlacesPlaceIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeletePlaceV1PlacesPlaceIdDeleteResponse =
  DeletePlaceV1PlacesPlaceIdDeleteResponses[keyof DeletePlaceV1PlacesPlaceIdDeleteResponses];

export type UpdatePlaceV1PlacesPlaceIdPatchData = {
  body: PlaceUpdate;
  path: {
    /**
     * Place Id
     */
    place_id: string;
  };
  query?: never;
  url: "/v1/places/{place_id}";
};

export type UpdatePlaceV1PlacesPlaceIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePlaceV1PlacesPlaceIdPatchError =
  UpdatePlaceV1PlacesPlaceIdPatchErrors[keyof UpdatePlaceV1PlacesPlaceIdPatchErrors];

export type UpdatePlaceV1PlacesPlaceIdPatchResponses = {
  /**
   * Successful Response
   */
  200: PlaceSchema;
};

export type UpdatePlaceV1PlacesPlaceIdPatchResponse =
  UpdatePlaceV1PlacesPlaceIdPatchResponses[keyof UpdatePlaceV1PlacesPlaceIdPatchResponses];

export type ListTasksV1TasksGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     *
     * Filter by status.
     */
    status?: TaskStatus | null;
    /**
     * Priority
     *
     * Filter by priority.
     */
    priority?: number | null;
    /**
     * Project
     *
     * Filter by project.
     */
    project?: string | null;
    /**
     * Area
     *
     * Filter by area.
     */
    area?: string | null;
    /**
     * Is Recurring
     *
     * Filter by recurring.
     */
    is_recurring?: boolean | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<TaskSortProperty> | null;
  };
  url: "/v1/tasks";
};

export type ListTasksV1TasksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTasksV1TasksGetError =
  ListTasksV1TasksGetErrors[keyof ListTasksV1TasksGetErrors];

export type ListTasksV1TasksGetResponses = {
  /**
   * Successful Response
   */
  200: TaskListResponse;
};

export type ListTasksV1TasksGetResponse =
  ListTasksV1TasksGetResponses[keyof ListTasksV1TasksGetResponses];

export type CreateTaskV1TasksPostData = {
  body: TaskCreate;
  path?: never;
  query?: never;
  url: "/v1/tasks";
};

export type CreateTaskV1TasksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTaskV1TasksPostError =
  CreateTaskV1TasksPostErrors[keyof CreateTaskV1TasksPostErrors];

export type CreateTaskV1TasksPostResponses = {
  /**
   * Successful Response
   */
  201: TaskSchema;
};

export type CreateTaskV1TasksPostResponse =
  CreateTaskV1TasksPostResponses[keyof CreateTaskV1TasksPostResponses];

export type DeleteTaskV1TasksTaskIdDeleteData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type DeleteTaskV1TasksTaskIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTaskV1TasksTaskIdDeleteError =
  DeleteTaskV1TasksTaskIdDeleteErrors[keyof DeleteTaskV1TasksTaskIdDeleteErrors];

export type DeleteTaskV1TasksTaskIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTaskV1TasksTaskIdDeleteResponse =
  DeleteTaskV1TasksTaskIdDeleteResponses[keyof DeleteTaskV1TasksTaskIdDeleteResponses];

export type UpdateTaskV1TasksTaskIdPatchData = {
  body: TaskUpdate;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type UpdateTaskV1TasksTaskIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTaskV1TasksTaskIdPatchError =
  UpdateTaskV1TasksTaskIdPatchErrors[keyof UpdateTaskV1TasksTaskIdPatchErrors];

export type UpdateTaskV1TasksTaskIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TaskSchema;
};

export type UpdateTaskV1TasksTaskIdPatchResponse =
  UpdateTaskV1TasksTaskIdPatchResponses[keyof UpdateTaskV1TasksTaskIdPatchResponses];

export type CompleteTaskV1TasksTaskIdCompletePostData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/complete";
};

export type CompleteTaskV1TasksTaskIdCompletePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CompleteTaskV1TasksTaskIdCompletePostError =
  CompleteTaskV1TasksTaskIdCompletePostErrors[keyof CompleteTaskV1TasksTaskIdCompletePostErrors];

export type CompleteTaskV1TasksTaskIdCompletePostResponses = {
  /**
   * Successful Response
   */
  200: TaskCompleteResponse;
};

export type CompleteTaskV1TasksTaskIdCompletePostResponse =
  CompleteTaskV1TasksTaskIdCompletePostResponses[keyof CompleteTaskV1TasksTaskIdCompletePostResponses];

export type ReopenTaskV1TasksTaskIdReopenPostData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/reopen";
};

export type ReopenTaskV1TasksTaskIdReopenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReopenTaskV1TasksTaskIdReopenPostError =
  ReopenTaskV1TasksTaskIdReopenPostErrors[keyof ReopenTaskV1TasksTaskIdReopenPostErrors];

export type ReopenTaskV1TasksTaskIdReopenPostResponses = {
  /**
   * Successful Response
   */
  200: TaskSchema;
};

export type ReopenTaskV1TasksTaskIdReopenPostResponse =
  ReopenTaskV1TasksTaskIdReopenPostResponses[keyof ReopenTaskV1TasksTaskIdReopenPostResponses];

export type ReorderTasksV1TasksReorderPatchData = {
  /**
   * Body
   */
  body: Array<TaskReorderItem>;
  path?: never;
  query?: never;
  url: "/v1/tasks/reorder";
};

export type ReorderTasksV1TasksReorderPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReorderTasksV1TasksReorderPatchError =
  ReorderTasksV1TasksReorderPatchErrors[keyof ReorderTasksV1TasksReorderPatchErrors];

export type ReorderTasksV1TasksReorderPatchResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ReorderTasksV1TasksReorderPatchResponse =
  ReorderTasksV1TasksReorderPatchResponses[keyof ReorderTasksV1TasksReorderPatchResponses];

export type ListProjectsV1TasksProjectsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/tasks/projects";
};

export type ListProjectsV1TasksProjectsGetResponses = {
  /**
   * Response List Projects V1 Tasks Projects Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ListProjectsV1TasksProjectsGetResponse =
  ListProjectsV1TasksProjectsGetResponses[keyof ListProjectsV1TasksProjectsGetResponses];

export type ListAreasV1TasksAreasGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/tasks/areas";
};

export type ListAreasV1TasksAreasGetResponses = {
  /**
   * Response List Areas V1 Tasks Areas Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ListAreasV1TasksAreasGetResponse =
  ListAreasV1TasksAreasGetResponses[keyof ListAreasV1TasksAreasGetResponses];

export type DeleteTransactionsV1TransactionsDeleteData = {
  body: BulkDeleteRequest;
  path?: never;
  query?: never;
  url: "/v1/transactions";
};

export type DeleteTransactionsV1TransactionsDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTransactionsV1TransactionsDeleteError =
  DeleteTransactionsV1TransactionsDeleteErrors[keyof DeleteTransactionsV1TransactionsDeleteErrors];

export type DeleteTransactionsV1TransactionsDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTransactionsV1TransactionsDeleteResponse =
  DeleteTransactionsV1TransactionsDeleteResponses[keyof DeleteTransactionsV1TransactionsDeleteResponses];

export type ListTransactionsV1TransactionsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Bank Account Id
     *
     * Filter by bank account ID(s).
     */
    bank_account_id?: Array<string> | null;
    /**
     * Category Id
     *
     * Filter by category ID(s).
     */
    category_id?: Array<string> | null;
    /**
     * Uncategorized
     *
     * If true, only show transactions without a category.
     */
    uncategorized?: boolean;
    /**
     * Direction
     *
     * Filter by direction: 'debit' or 'credit'.
     */
    direction?: string | null;
    /**
     * Search
     *
     * Search in description (case-insensitive).
     */
    search?: string | null;
    /**
     * Date From
     *
     * Start date (inclusive).
     */
    date_from?: Date | null;
    /**
     * Date To
     *
     * End date (inclusive).
     */
    date_to?: Date | null;
    /**
     * Is Business
     *
     * Filter by business flag.
     */
    is_business?: boolean | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<TransactionSortProperty> | null;
  };
  url: "/v1/transactions";
};

export type ListTransactionsV1TransactionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTransactionsV1TransactionsGetError =
  ListTransactionsV1TransactionsGetErrors[keyof ListTransactionsV1TransactionsGetErrors];

export type ListTransactionsV1TransactionsGetResponses = {
  /**
   * Successful Response
   */
  200: TransactionListResponse;
};

export type ListTransactionsV1TransactionsGetResponse =
  ListTransactionsV1TransactionsGetResponses[keyof ListTransactionsV1TransactionsGetResponses];

export type ImportTransactionsV1TransactionsImportPostData = {
  body: BodyImportTransactionsV1TransactionsImportPost;
  path?: never;
  query: {
    /**
     * Bank
     *
     * Bank identifier, e.g. 'marginalen'.
     */
    bank: string;
    /**
     * Bank Account Id
     *
     * Bank account to attach transactions to.
     */
    bank_account_id: string;
  };
  url: "/v1/transactions/import";
};

export type ImportTransactionsV1TransactionsImportPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportTransactionsV1TransactionsImportPostError =
  ImportTransactionsV1TransactionsImportPostErrors[keyof ImportTransactionsV1TransactionsImportPostErrors];

export type ImportTransactionsV1TransactionsImportPostResponses = {
  /**
   * Successful Response
   */
  200: ImportResponse;
};

export type ImportTransactionsV1TransactionsImportPostResponse =
  ImportTransactionsV1TransactionsImportPostResponses[keyof ImportTransactionsV1TransactionsImportPostResponses];

export type UpdateTransactionV1TransactionsTransactionIdPatchData = {
  body: TransactionUpdate;
  path: {
    /**
     * Transaction Id
     */
    transaction_id: string;
  };
  query?: never;
  url: "/v1/transactions/{transaction_id}";
};

export type UpdateTransactionV1TransactionsTransactionIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTransactionV1TransactionsTransactionIdPatchError =
  UpdateTransactionV1TransactionsTransactionIdPatchErrors[keyof UpdateTransactionV1TransactionsTransactionIdPatchErrors];

export type UpdateTransactionV1TransactionsTransactionIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TransactionUpdateResponse;
};

export type UpdateTransactionV1TransactionsTransactionIdPatchResponse =
  UpdateTransactionV1TransactionsTransactionIdPatchResponses[keyof UpdateTransactionV1TransactionsTransactionIdPatchResponses];

export type BulkUpdateTransactionsV1TransactionsBulkPatchData = {
  body: BulkUpdateRequest;
  path?: never;
  query?: never;
  url: "/v1/transactions/bulk";
};

export type BulkUpdateTransactionsV1TransactionsBulkPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type BulkUpdateTransactionsV1TransactionsBulkPatchError =
  BulkUpdateTransactionsV1TransactionsBulkPatchErrors[keyof BulkUpdateTransactionsV1TransactionsBulkPatchErrors];

export type BulkUpdateTransactionsV1TransactionsBulkPatchResponses = {
  /**
   * Successful Response
   */
  200: BulkUpdateResponse;
};

export type BulkUpdateTransactionsV1TransactionsBulkPatchResponse =
  BulkUpdateTransactionsV1TransactionsBulkPatchResponses[keyof BulkUpdateTransactionsV1TransactionsBulkPatchResponses];

export type CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostData =
  {
    body: BulkCategorizeRequest;
    path?: never;
    query?: never;
    url: "/v1/transactions/categorize-by-description";
  };

export type CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostError =
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostErrors[keyof CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostErrors];

export type CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponses =
  {
    /**
     * Successful Response
     */
    200: BulkCategorizeResponse;
  };

export type CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponse =
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponses[keyof CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponses];

export type SpendingByCategoryV1TransactionsSpendingByCategoryGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Year
     *
     * Year to query.
     */
    year: number;
    /**
     * Month
     *
     * Month to query (1-12).
     */
    month: number;
  };
  url: "/v1/transactions/spending-by-category";
};

export type SpendingByCategoryV1TransactionsSpendingByCategoryGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SpendingByCategoryV1TransactionsSpendingByCategoryGetError =
  SpendingByCategoryV1TransactionsSpendingByCategoryGetErrors[keyof SpendingByCategoryV1TransactionsSpendingByCategoryGetErrors];

export type SpendingByCategoryV1TransactionsSpendingByCategoryGetResponses = {
  /**
   * Successful Response
   */
  200: MonthlySpendingResponse;
};

export type SpendingByCategoryV1TransactionsSpendingByCategoryGetResponse =
  SpendingByCategoryV1TransactionsSpendingByCategoryGetResponses[keyof SpendingByCategoryV1TransactionsSpendingByCategoryGetResponses];

export type MonthlyFlowV1TransactionsMonthlyFlowGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Months
     *
     * Number of months to look back (including current).
     */
    months?: number;
  };
  url: "/v1/transactions/monthly-flow";
};

export type MonthlyFlowV1TransactionsMonthlyFlowGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MonthlyFlowV1TransactionsMonthlyFlowGetError =
  MonthlyFlowV1TransactionsMonthlyFlowGetErrors[keyof MonthlyFlowV1TransactionsMonthlyFlowGetErrors];

export type MonthlyFlowV1TransactionsMonthlyFlowGetResponses = {
  /**
   * Successful Response
   */
  200: MonthlyFlowResponse;
};

export type MonthlyFlowV1TransactionsMonthlyFlowGetResponse =
  MonthlyFlowV1TransactionsMonthlyFlowGetResponses[keyof MonthlyFlowV1TransactionsMonthlyFlowGetResponses];

export type GetWeatherForecastV1WeatherGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Lat
     *
     * Latitude.
     */
    lat: number;
    /**
     * Lon
     *
     * Longitude.
     */
    lon: number;
  };
  url: "/v1/weather";
};

export type GetWeatherForecastV1WeatherGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWeatherForecastV1WeatherGetError =
  GetWeatherForecastV1WeatherGetErrors[keyof GetWeatherForecastV1WeatherGetErrors];

export type GetWeatherForecastV1WeatherGetResponses = {
  /**
   * Successful Response
   */
  200: WeatherForecastResponse;
};

export type GetWeatherForecastV1WeatherGetResponse =
  GetWeatherForecastV1WeatherGetResponses[keyof GetWeatherForecastV1WeatherGetResponses];

export type GetKlarnaTransactionsV1KlarnaTransactionsGetData = {
  body?: never;
  headers: {
    /**
     * Authorization
     *
     * Klarna Bearer token
     */
    authorization: string;
    /**
     * Cookie
     *
     * Klarna session cookies
     */
    cookie?: string | null;
  };
  path?: never;
  query?: never;
  url: "/v1/klarna/transactions";
};

export type GetKlarnaTransactionsV1KlarnaTransactionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetKlarnaTransactionsV1KlarnaTransactionsGetError =
  GetKlarnaTransactionsV1KlarnaTransactionsGetErrors[keyof GetKlarnaTransactionsV1KlarnaTransactionsGetErrors];

export type GetKlarnaTransactionsV1KlarnaTransactionsGetResponses = {
  /**
   * Response Get Klarna Transactions V1 Klarna Transactions Get
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetKlarnaTransactionsV1KlarnaTransactionsGetResponse =
  GetKlarnaTransactionsV1KlarnaTransactionsGetResponses[keyof GetKlarnaTransactionsV1KlarnaTransactionsGetResponses];

export type ImportKlarnaTransactionsV1KlarnaImportPostData = {
  body: KlarnaImportRequest;
  path?: never;
  query?: never;
  url: "/v1/klarna/import";
};

export type ImportKlarnaTransactionsV1KlarnaImportPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportKlarnaTransactionsV1KlarnaImportPostError =
  ImportKlarnaTransactionsV1KlarnaImportPostErrors[keyof ImportKlarnaTransactionsV1KlarnaImportPostErrors];

export type ImportKlarnaTransactionsV1KlarnaImportPostResponses = {
  /**
   * Successful Response
   */
  200: ImportResponse;
};

export type ImportKlarnaTransactionsV1KlarnaImportPostResponse =
  ImportKlarnaTransactionsV1KlarnaImportPostResponses[keyof ImportKlarnaTransactionsV1KlarnaImportPostResponses];

export type ListExercisesV1WorkoutsExercisesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     *
     * Search exercises by name.
     */
    q?: string | null;
    /**
     * Category
     *
     * Filter by muscle category.
     */
    category?: MuscleCategory | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
  };
  url: "/v1/workouts/exercises";
};

export type ListExercisesV1WorkoutsExercisesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListExercisesV1WorkoutsExercisesGetError =
  ListExercisesV1WorkoutsExercisesGetErrors[keyof ListExercisesV1WorkoutsExercisesGetErrors];

export type ListExercisesV1WorkoutsExercisesGetResponses = {
  /**
   * Successful Response
   */
  200: ExerciseListResponse;
};

export type ListExercisesV1WorkoutsExercisesGetResponse =
  ListExercisesV1WorkoutsExercisesGetResponses[keyof ListExercisesV1WorkoutsExercisesGetResponses];

export type CreateExerciseV1WorkoutsExercisesPostData = {
  body: ExerciseCreate;
  path?: never;
  query?: never;
  url: "/v1/workouts/exercises";
};

export type CreateExerciseV1WorkoutsExercisesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateExerciseV1WorkoutsExercisesPostError =
  CreateExerciseV1WorkoutsExercisesPostErrors[keyof CreateExerciseV1WorkoutsExercisesPostErrors];

export type CreateExerciseV1WorkoutsExercisesPostResponses = {
  /**
   * Successful Response
   */
  201: ExerciseSchema;
};

export type CreateExerciseV1WorkoutsExercisesPostResponse =
  CreateExerciseV1WorkoutsExercisesPostResponses[keyof CreateExerciseV1WorkoutsExercisesPostResponses];

export type ListRecentExercisesV1WorkoutsExercisesRecentGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/v1/workouts/exercises/recent";
};

export type ListRecentExercisesV1WorkoutsExercisesRecentGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListRecentExercisesV1WorkoutsExercisesRecentGetError =
  ListRecentExercisesV1WorkoutsExercisesRecentGetErrors[keyof ListRecentExercisesV1WorkoutsExercisesRecentGetErrors];

export type ListRecentExercisesV1WorkoutsExercisesRecentGetResponses = {
  /**
   * Response List Recent Exercises V1 Workouts Exercises Recent Get
   *
   * Successful Response
   */
  200: Array<ExerciseSchema>;
};

export type ListRecentExercisesV1WorkoutsExercisesRecentGetResponse =
  ListRecentExercisesV1WorkoutsExercisesRecentGetResponses[keyof ListRecentExercisesV1WorkoutsExercisesRecentGetResponses];

export type ListWorkoutsV1WorkoutsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<WorkoutLogSortProperty> | null;
  };
  url: "/v1/workouts";
};

export type ListWorkoutsV1WorkoutsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListWorkoutsV1WorkoutsGetError =
  ListWorkoutsV1WorkoutsGetErrors[keyof ListWorkoutsV1WorkoutsGetErrors];

export type ListWorkoutsV1WorkoutsGetResponses = {
  /**
   * Successful Response
   */
  200: WorkoutLogListResponse;
};

export type ListWorkoutsV1WorkoutsGetResponse =
  ListWorkoutsV1WorkoutsGetResponses[keyof ListWorkoutsV1WorkoutsGetResponses];

export type CreateWorkoutV1WorkoutsPostData = {
  body: WorkoutLogCreate;
  path?: never;
  query?: never;
  url: "/v1/workouts";
};

export type CreateWorkoutV1WorkoutsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateWorkoutV1WorkoutsPostError =
  CreateWorkoutV1WorkoutsPostErrors[keyof CreateWorkoutV1WorkoutsPostErrors];

export type CreateWorkoutV1WorkoutsPostResponses = {
  /**
   * Successful Response
   */
  201: WorkoutLogSchema;
};

export type CreateWorkoutV1WorkoutsPostResponse =
  CreateWorkoutV1WorkoutsPostResponses[keyof CreateWorkoutV1WorkoutsPostResponses];

export type DeleteWorkoutV1WorkoutsWorkoutIdDeleteData = {
  body?: never;
  path: {
    /**
     * Workout Id
     */
    workout_id: string;
  };
  query?: never;
  url: "/v1/workouts/{workout_id}";
};

export type DeleteWorkoutV1WorkoutsWorkoutIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteWorkoutV1WorkoutsWorkoutIdDeleteError =
  DeleteWorkoutV1WorkoutsWorkoutIdDeleteErrors[keyof DeleteWorkoutV1WorkoutsWorkoutIdDeleteErrors];

export type DeleteWorkoutV1WorkoutsWorkoutIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteWorkoutV1WorkoutsWorkoutIdDeleteResponse =
  DeleteWorkoutV1WorkoutsWorkoutIdDeleteResponses[keyof DeleteWorkoutV1WorkoutsWorkoutIdDeleteResponses];

export type GetWorkoutV1WorkoutsWorkoutIdGetData = {
  body?: never;
  path: {
    /**
     * Workout Id
     */
    workout_id: string;
  };
  query?: never;
  url: "/v1/workouts/{workout_id}";
};

export type GetWorkoutV1WorkoutsWorkoutIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWorkoutV1WorkoutsWorkoutIdGetError =
  GetWorkoutV1WorkoutsWorkoutIdGetErrors[keyof GetWorkoutV1WorkoutsWorkoutIdGetErrors];

export type GetWorkoutV1WorkoutsWorkoutIdGetResponses = {
  /**
   * Successful Response
   */
  200: WorkoutLogDetailSchema;
};

export type GetWorkoutV1WorkoutsWorkoutIdGetResponse =
  GetWorkoutV1WorkoutsWorkoutIdGetResponses[keyof GetWorkoutV1WorkoutsWorkoutIdGetResponses];

export type UpdateWorkoutV1WorkoutsWorkoutIdPatchData = {
  body: WorkoutLogUpdate;
  path: {
    /**
     * Workout Id
     */
    workout_id: string;
  };
  query?: never;
  url: "/v1/workouts/{workout_id}";
};

export type UpdateWorkoutV1WorkoutsWorkoutIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateWorkoutV1WorkoutsWorkoutIdPatchError =
  UpdateWorkoutV1WorkoutsWorkoutIdPatchErrors[keyof UpdateWorkoutV1WorkoutsWorkoutIdPatchErrors];

export type UpdateWorkoutV1WorkoutsWorkoutIdPatchResponses = {
  /**
   * Successful Response
   */
  200: WorkoutLogSchema;
};

export type UpdateWorkoutV1WorkoutsWorkoutIdPatchResponse =
  UpdateWorkoutV1WorkoutsWorkoutIdPatchResponses[keyof UpdateWorkoutV1WorkoutsWorkoutIdPatchResponses];

export type CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostData = {
  body: WorkoutSetCreate;
  path: {
    /**
     * Workout Id
     */
    workout_id: string;
  };
  query?: never;
  url: "/v1/workouts/{workout_id}/sets";
};

export type CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostError =
  CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostErrors[keyof CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostErrors];

export type CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostResponses = {
  /**
   * Successful Response
   */
  201: WorkoutSetSchema;
};

export type CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostResponse =
  CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostResponses[keyof CreateWorkoutSetV1WorkoutsWorkoutIdSetsPostResponses];

export type DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteData = {
  body?: never;
  path: {
    /**
     * Workout Id
     */
    workout_id: string;
    /**
     * Set Id
     */
    set_id: string;
  };
  query?: never;
  url: "/v1/workouts/{workout_id}/sets/{set_id}";
};

export type DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteError =
  DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteErrors[keyof DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteErrors];

export type DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteResponse =
  DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteResponses[keyof DeleteWorkoutSetV1WorkoutsWorkoutIdSetsSetIdDeleteResponses];

export type UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchData = {
  body: WorkoutSetUpdate;
  path: {
    /**
     * Workout Id
     */
    workout_id: string;
    /**
     * Set Id
     */
    set_id: string;
  };
  query?: never;
  url: "/v1/workouts/{workout_id}/sets/{set_id}";
};

export type UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchError =
  UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchErrors[keyof UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchErrors];

export type UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponses = {
  /**
   * Successful Response
   */
  200: WorkoutSetSchema;
};

export type UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponse =
  UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponses[keyof UpdateWorkoutSetV1WorkoutsWorkoutIdSetsSetIdPatchResponses];

export type GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetData = {
  body?: never;
  path: {
    /**
     * Exercise Id
     */
    exercise_id: string;
  };
  query?: never;
  url: "/v1/workouts/exercises/{exercise_id}/last-session";
};

export type GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetError =
  GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetErrors[keyof GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetErrors];

export type GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetResponses =
  {
    /**
     * Successful Response
     */
    200: LastSessionResponse;
  };

export type GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetResponse =
  GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetResponses[keyof GetLastSessionV1WorkoutsExercisesExerciseIdLastSessionGetResponses];

export type GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetData = {
  body?: never;
  path: {
    /**
     * Exercise Id
     */
    exercise_id: string;
  };
  query?: never;
  url: "/v1/workouts/exercises/{exercise_id}/prs";
};

export type GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetError =
  GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetErrors[keyof GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetErrors];

export type GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponses = {
  /**
   * Successful Response
   */
  200: ExercisePrListResponse;
};

export type GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponse =
  GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponses[keyof GetExercisePrsV1WorkoutsExercisesExerciseIdPrsGetResponses];
