// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.metron.sh" | (string & {});
};

/**
 * BankAccountCreate
 */
export type BankAccountCreate = {
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name: string;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance?: number;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype: string;
};

/**
 * BankAccountListResponse
 */
export type BankAccountListResponse = {
  /**
   * Items
   */
  items: Array<BankAccountSchema>;
  pagination: Pagination;
};

/**
 * BankAccountSchema
 */
export type BankAccountSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name: string;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency: string;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance: number;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype: string;
  /**
   * Current Balance
   *
   * Current balance in minor units (base_balance + credits - debits).
   */
  current_balance?: number;
};

/**
 * BankAccountSortProperty
 */
export const BankAccountSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  NAME: "name",
  "-NAME": "-name",
} as const;

/**
 * BankAccountSortProperty
 */
export type BankAccountSortProperty =
  (typeof BankAccountSortProperty)[keyof typeof BankAccountSortProperty];

/**
 * BankAccountUpdate
 */
export type BankAccountUpdate = {
  /**
   * Name
   *
   * Display name of the bank account.
   */
  name?: string | null;
  /**
   * Currency
   *
   * ISO 4217 currency code.
   */
  currency?: string | null;
  /**
   * Base Balance
   *
   * Starting balance in minor units (cents).
   */
  base_balance?: number | null;
  /**
   * Subtype
   *
   * Account subtype, e.g. 'checking', 'savings'.
   */
  subtype?: string | null;
};

/**
 * Body_import_transactions_v1_transactions_import_post
 */
export type BodyImportTransactionsV1TransactionsImportPost = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * BulkDeleteRequest
 */
export type BulkDeleteRequest = {
  /**
   * Ids
   *
   * List of transaction IDs to delete.
   */
  ids: Array<string>;
};

/**
 * CategoryListResponse
 */
export type CategoryListResponse = {
  /**
   * Items
   */
  items: Array<CategorySchema>;
  pagination: Pagination;
};

/**
 * CategorySchema
 */
export type CategorySchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Category name.
   */
  name: string;
  /**
   * Slug
   *
   * URL-friendly identifier.
   */
  slug: string;
  /**
   * Color
   *
   * Hex color code for UI display.
   */
  color: string;
  /**
   * Excluded
   *
   * Whether this category is excluded from reports.
   */
  excluded: boolean;
  /**
   * Parent Id
   *
   * Parent category ID, null for top-level.
   */
  parent_id?: string | null;
};

/**
 * GooglePlaceSearchResponse
 */
export type GooglePlaceSearchResponse = {
  /**
   * Results
   */
  results: Array<GooglePlaceSearchResult>;
};

/**
 * GooglePlaceSearchResult
 */
export type GooglePlaceSearchResult = {
  /**
   * Place Id
   *
   * Google Place ID.
   */
  place_id: string;
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   *
   * Formatted address.
   */
  address: string;
  /**
   * Country
   *
   * Country name.
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude.
   */
  longitude: number;
  /**
   * Plus Code
   *
   * Plus Code.
   */
  plus_code?: string | null;
  /**
   * Category
   *
   * Primary type.
   */
  category?: string | null;
  /**
   * Photo Url
   *
   * Photo reference URL.
   */
  photo_url?: string | null;
  /**
   * Website
   *
   * Website.
   */
  website?: string | null;
  /**
   * Phone
   *
   * Phone number.
   */
  phone?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ImportResponse
 */
export type ImportResponse = {
  /**
   * Created
   *
   * Number of new transactions imported.
   */
  created: number;
  /**
   * Skipped
   *
   * Number of duplicate transactions skipped.
   */
  skipped: number;
};

/**
 * JournalCalendarDay
 */
export type JournalCalendarDay = {
  /**
   * Entry Date
   */
  entry_date: Date;
  /**
   * Mood
   */
  mood?: number | null;
  /**
   * Word Count
   */
  word_count?: number;
  /**
   * Has Wins
   */
  has_wins?: boolean;
  /**
   * Has Learnings
   */
  has_learnings?: boolean;
};

/**
 * JournalCalendarResponse
 */
export type JournalCalendarResponse = {
  /**
   * Days
   */
  days: Array<JournalCalendarDay>;
};

/**
 * JournalEntryListResponse
 */
export type JournalEntryListResponse = {
  /**
   * Items
   */
  items: Array<JournalEntrySchema>;
  pagination: Pagination;
};

/**
 * JournalEntrySchema
 */
export type JournalEntrySchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Entry Date
   *
   * Calendar date for this entry.
   */
  entry_date: Date;
  /**
   * Body
   *
   * Free-form markdown body.
   */
  body?: string | null;
  /**
   * Mood
   *
   * Mood rating 1-5.
   */
  mood?: number | null;
  /**
   * Energy
   *
   * Energy rating 1-5.
   */
  energy?: number | null;
  /**
   * Focus
   *
   * Focus quality 1-5.
   */
  focus?: number | null;
  /**
   * Sleep Hours
   *
   * Hours of sleep.
   */
  sleep_hours?: number | null;
  /**
   * Wins
   *
   * Wins for the day.
   */
  wins?: string | null;
  /**
   * Blockers
   *
   * Blockers / challenges.
   */
  blockers?: string | null;
  /**
   * Learnings
   *
   * Key learnings.
   */
  learnings?: string | null;
  /**
   * Gratitude
   *
   * Gratitude notes.
   */
  gratitude?: string | null;
  /**
   * Intention
   *
   * Intention for tomorrow.
   */
  intention?: string | null;
  /**
   * Decisions
   *
   * Decisions log.
   */
  decisions?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Tags
   *
   * Tags.
   */
  tags?: Array<string> | null;
  /**
   * Word Count
   *
   * Word count of body.
   */
  word_count?: number;
};

/**
 * JournalEntryUpsert
 */
export type JournalEntryUpsert = {
  /**
   * Body
   */
  body?: string | null;
  /**
   * Mood
   */
  mood?: number | null;
  /**
   * Energy
   */
  energy?: number | null;
  /**
   * Focus
   */
  focus?: number | null;
  /**
   * Sleep Hours
   */
  sleep_hours?: number | null;
  /**
   * Wins
   */
  wins?: string | null;
  /**
   * Blockers
   */
  blockers?: string | null;
  /**
   * Learnings
   */
  learnings?: string | null;
  /**
   * Gratitude
   */
  gratitude?: string | null;
  /**
   * Intention
   */
  intention?: string | null;
  /**
   * Decisions
   */
  decisions?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
};

/**
 * JournalSortProperty
 */
export const JournalSortProperty = {
  ENTRY_DATE: "entry_date",
  "-ENTRY_DATE": "-entry_date",
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  MOOD: "mood",
  "-MOOD": "-mood",
  ENERGY: "energy",
  "-ENERGY": "-energy",
} as const;

/**
 * JournalSortProperty
 */
export type JournalSortProperty =
  (typeof JournalSortProperty)[keyof typeof JournalSortProperty];

/**
 * JournalStreakResponse
 */
export type JournalStreakResponse = {
  /**
   * Current Streak
   */
  current_streak: number;
  /**
   * Longest Streak
   */
  longest_streak: number;
  /**
   * Total Entries
   */
  total_entries: number;
};

/**
 * Pagination
 */
export type Pagination = {
  /**
   * Total Count
   */
  total_count: number;
  /**
   * Max Page
   */
  max_page: number;
};

/**
 * PlaceCreate
 */
export type PlaceCreate = {
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Country
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude coordinate.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude coordinate.
   */
  longitude: number;
  /**
   * Google Place Id
   */
  google_place_id?: string | null;
  /**
   * Plus Code
   */
  plus_code?: string | null;
  status?: PlaceStatus;
  /**
   * Rating
   */
  rating?: number | null;
  /**
   * Visited At
   */
  visited_at?: Date | null;
  /**
   * Review
   */
  review?: string | null;
  /**
   * Category
   */
  category?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   */
  photo_url?: string | null;
  /**
   * Website
   */
  website?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * PlaceListResponse
 */
export type PlaceListResponse = {
  /**
   * Items
   */
  items: Array<PlaceSchema>;
  pagination: Pagination;
};

/**
 * PlaceSchema
 */
export type PlaceSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Name
   *
   * Place name.
   */
  name: string;
  /**
   * Address
   *
   * Full address.
   */
  address?: string | null;
  /**
   * Country
   *
   * Country name.
   */
  country?: string | null;
  /**
   * Latitude
   *
   * Latitude coordinate.
   */
  latitude: number;
  /**
   * Longitude
   *
   * Longitude coordinate.
   */
  longitude: number;
  /**
   * Google Place Id
   *
   * Google Maps place ID.
   */
  google_place_id?: string | null;
  /**
   * Plus Code
   *
   * Google Plus Code.
   */
  plus_code?: string | null;
  /**
   * Place status.
   */
  status?: PlaceStatus;
  /**
   * Rating
   *
   * Personal rating (1-5).
   */
  rating?: number | null;
  /**
   * Visited At
   *
   * Date when the place was visited.
   */
  visited_at?: Date | null;
  /**
   * Review
   *
   * Personal review/notes.
   */
  review?: string | null;
  /**
   * Category
   *
   * Place category (e.g. restaurant, cafe).
   */
  category?: string | null;
  /**
   * Tags
   *
   * User-defined tags.
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   *
   * Photo URL from Google.
   */
  photo_url?: string | null;
  /**
   * Website
   *
   * Website URL.
   */
  website?: string | null;
  /**
   * Phone
   *
   * Phone number.
   */
  phone?: string | null;
};

/**
 * PlaceSortProperty
 */
export const PlaceSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  NAME: "name",
  "-NAME": "-name",
  RATING: "rating",
  "-RATING": "-rating",
  VISITED_AT: "visited_at",
  "-VISITED_AT": "-visited_at",
} as const;

/**
 * PlaceSortProperty
 */
export type PlaceSortProperty =
  (typeof PlaceSortProperty)[keyof typeof PlaceSortProperty];

/**
 * PlaceStatus
 */
export const PlaceStatus = {
  WANT_TO_GO: "want_to_go",
  VISITED: "visited",
} as const;

/**
 * PlaceStatus
 */
export type PlaceStatus = (typeof PlaceStatus)[keyof typeof PlaceStatus];

/**
 * PlaceUpdate
 */
export type PlaceUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Address
   */
  address?: string | null;
  /**
   * Country
   */
  country?: string | null;
  /**
   * Latitude
   */
  latitude?: number | null;
  /**
   * Longitude
   */
  longitude?: number | null;
  status?: PlaceStatus | null;
  /**
   * Rating
   */
  rating?: number | null;
  /**
   * Visited At
   */
  visited_at?: Date | null;
  /**
   * Review
   */
  review?: string | null;
  /**
   * Category
   */
  category?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Photo Url
   */
  photo_url?: string | null;
  /**
   * Website
   */
  website?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
};

/**
 * RruleFrequency
 */
export const RruleFrequency = {
  DAILY: "daily",
  WEEKLY: "weekly",
  MONTHLY: "monthly",
  YEARLY: "yearly",
} as const;

/**
 * RruleFrequency
 */
export type RruleFrequency =
  (typeof RruleFrequency)[keyof typeof RruleFrequency];

/**
 * TaskCompleteResponse
 */
export type TaskCompleteResponse = {
  completed_task: TaskSchema;
  /**
   * Next recurring instance, if applicable.
   */
  next_task?: TaskSchema | null;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
  /**
   * Title
   *
   * Task title.
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  status?: TaskStatus;
  /**
   * Priority
   */
  priority?: number;
  /**
   * Due Date
   */
  due_date?: Date | null;
  /**
   * Project
   */
  project?: string | null;
  /**
   * Area
   */
  area?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Position
   */
  position?: number;
  /**
   * Is Recurring
   */
  is_recurring?: boolean;
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   */
  rrule_day_of_month?: number | null;
};

/**
 * TaskListResponse
 */
export type TaskListResponse = {
  /**
   * Items
   */
  items: Array<TaskSchema>;
  pagination: Pagination;
};

/**
 * TaskReorderItem
 */
export type TaskReorderItem = {
  /**
   * Id
   */
  id: string;
  /**
   * Position
   */
  position: number;
  status?: TaskStatus | null;
};

/**
 * TaskSchema
 */
export type TaskSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Title
   *
   * Task title.
   */
  title: string;
  /**
   * Description
   *
   * Task description.
   */
  description?: string | null;
  /**
   * Task status.
   */
  status?: TaskStatus;
  /**
   * Priority
   *
   * Priority (0=none, 1=low, 2=medium, 3=high, 4=urgent).
   */
  priority?: number;
  /**
   * Due Date
   *
   * Due date.
   */
  due_date?: Date | null;
  /**
   * Completed At
   *
   * Completion timestamp.
   */
  completed_at?: Date | null;
  /**
   * Project
   *
   * Project name.
   */
  project?: string | null;
  /**
   * Area
   *
   * Area (e.g. Company, Personal, Travel).
   */
  area?: string | null;
  /**
   * Tags
   *
   * User-defined tags.
   */
  tags?: Array<string> | null;
  /**
   * Position
   *
   * Position for ordering within a status column.
   */
  position?: number;
  /**
   * Is Recurring
   *
   * Whether this task recurs.
   */
  is_recurring?: boolean;
  /**
   * Recurrence frequency.
   */
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   *
   * Recurrence interval.
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   *
   * Day of week for weekly recurrence (0=Mon, 6=Sun).
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   *
   * Day of month for monthly recurrence (1-31).
   */
  rrule_day_of_month?: number | null;
  /**
   * Parent Task Id
   *
   * Parent task ID for recurring chain.
   */
  parent_task_id?: string | null;
};

/**
 * TaskSortProperty
 */
export const TaskSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  DUE_DATE: "due_date",
  "-DUE_DATE": "-due_date",
  PRIORITY: "priority",
  "-PRIORITY": "-priority",
  TITLE: "title",
  "-TITLE": "-title",
  COMPLETED_AT: "completed_at",
  "-COMPLETED_AT": "-completed_at",
  POSITION: "position",
  "-POSITION": "-position",
} as const;

/**
 * TaskSortProperty
 */
export type TaskSortProperty =
  (typeof TaskSortProperty)[keyof typeof TaskSortProperty];

/**
 * TaskStatus
 */
export const TaskStatus = {
  TODO: "todo",
  IN_PROGRESS: "in_progress",
  DONE: "done",
  CANCELLED: "cancelled",
} as const;

/**
 * TaskStatus
 */
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

/**
 * TaskUpdate
 */
export type TaskUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  status?: TaskStatus | null;
  /**
   * Priority
   */
  priority?: number | null;
  /**
   * Due Date
   */
  due_date?: Date | null;
  /**
   * Project
   */
  project?: string | null;
  /**
   * Area
   */
  area?: string | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Position
   */
  position?: number | null;
  /**
   * Is Recurring
   */
  is_recurring?: boolean | null;
  rrule_frequency?: RruleFrequency | null;
  /**
   * Rrule Interval
   */
  rrule_interval?: number | null;
  /**
   * Rrule Day Of Week
   */
  rrule_day_of_week?: number | null;
  /**
   * Rrule Day Of Month
   */
  rrule_day_of_month?: number | null;
};

/**
 * TransactionDirection
 */
export const TransactionDirection = {
  DEBIT: "debit",
  CREDIT: "credit",
} as const;

/**
 * TransactionDirection
 */
export type TransactionDirection =
  (typeof TransactionDirection)[keyof typeof TransactionDirection];

/**
 * TransactionListResponse
 */
export type TransactionListResponse = {
  /**
   * Items
   */
  items: Array<TransactionSchema>;
  pagination: Pagination;
};

/**
 * TransactionSchema
 */
export type TransactionSchema = {
  /**
   * Created At
   *
   * Creation timestamp of the object.
   */
  created_at: Date;
  /**
   * Modified At
   *
   * Last modification timestamp of the object.
   */
  modified_at: Date | null;
  /**
   * Id
   *
   * The ID of the object.
   */
  id: string;
  /**
   * Amount
   *
   * Amount in minor units (cents).
   */
  amount: number;
  /**
   * Currency
   */
  currency: string;
  /**
   * Transaction Date
   */
  transaction_date: Date;
  direction: TransactionDirection;
  /**
   * Description
   */
  description: string | null;
  /**
   * Category Id
   */
  category_id: string | null;
  /**
   * Transaction Type
   */
  transaction_type: string | null;
  /**
   * Dedup Hash
   */
  dedup_hash: string;
  /**
   * Bank Account Id
   */
  bank_account_id: string;
  /**
   * Raw Id
   */
  raw_id: string | null;
};

/**
 * TransactionSortProperty
 */
export const TransactionSortProperty = {
  CREATED_AT: "created_at",
  "-CREATED_AT": "-created_at",
  TRANSACTION_DATE: "transaction_date",
  "-TRANSACTION_DATE": "-transaction_date",
  AMOUNT: "amount",
  "-AMOUNT": "-amount",
  DESCRIPTION: "description",
  "-DESCRIPTION": "-description",
} as const;

/**
 * TransactionSortProperty
 */
export type TransactionSortProperty =
  (typeof TransactionSortProperty)[keyof typeof TransactionSortProperty];

/**
 * TransactionUpdate
 */
export type TransactionUpdate = {
  /**
   * Category Id
   *
   * Category ID to assign.
   */
  category_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type HealthzHealthzGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/healthz";
};

export type HealthzHealthzGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListBankAccountsV1BankAccountsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<BankAccountSortProperty> | null;
  };
  url: "/v1/bank-accounts";
};

export type ListBankAccountsV1BankAccountsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListBankAccountsV1BankAccountsGetError =
  ListBankAccountsV1BankAccountsGetErrors[keyof ListBankAccountsV1BankAccountsGetErrors];

export type ListBankAccountsV1BankAccountsGetResponses = {
  /**
   * Successful Response
   */
  200: BankAccountListResponse;
};

export type ListBankAccountsV1BankAccountsGetResponse =
  ListBankAccountsV1BankAccountsGetResponses[keyof ListBankAccountsV1BankAccountsGetResponses];

export type CreateBankAccountV1BankAccountsPostData = {
  body: BankAccountCreate;
  path?: never;
  query?: never;
  url: "/v1/bank-accounts";
};

export type CreateBankAccountV1BankAccountsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBankAccountV1BankAccountsPostError =
  CreateBankAccountV1BankAccountsPostErrors[keyof CreateBankAccountV1BankAccountsPostErrors];

export type CreateBankAccountV1BankAccountsPostResponses = {
  /**
   * Successful Response
   */
  201: BankAccountSchema;
};

export type CreateBankAccountV1BankAccountsPostResponse =
  CreateBankAccountV1BankAccountsPostResponses[keyof CreateBankAccountV1BankAccountsPostResponses];

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteData = {
  body?: never;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteError =
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors[keyof DeleteBankAccountV1BankAccountsBankAccountIdDeleteErrors];

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse =
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses[keyof DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponses];

export type GetBankAccountV1BankAccountsBankAccountIdGetData = {
  body?: never;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type GetBankAccountV1BankAccountsBankAccountIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBankAccountV1BankAccountsBankAccountIdGetError =
  GetBankAccountV1BankAccountsBankAccountIdGetErrors[keyof GetBankAccountV1BankAccountsBankAccountIdGetErrors];

export type GetBankAccountV1BankAccountsBankAccountIdGetResponses = {
  /**
   * Successful Response
   */
  200: BankAccountSchema;
};

export type GetBankAccountV1BankAccountsBankAccountIdGetResponse =
  GetBankAccountV1BankAccountsBankAccountIdGetResponses[keyof GetBankAccountV1BankAccountsBankAccountIdGetResponses];

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchData = {
  body: BankAccountUpdate;
  path: {
    /**
     * Bank Account Id
     */
    bank_account_id: string;
  };
  query?: never;
  url: "/v1/bank-accounts/{bank_account_id}";
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchError =
  UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors[keyof UpdateBankAccountV1BankAccountsBankAccountIdPatchErrors];

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses = {
  /**
   * Successful Response
   */
  200: BankAccountSchema;
};

export type UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse =
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses[keyof UpdateBankAccountV1BankAccountsBankAccountIdPatchResponses];

export type ListCategoriesV1CategoriesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
  };
  url: "/v1/categories";
};

export type ListCategoriesV1CategoriesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListCategoriesV1CategoriesGetError =
  ListCategoriesV1CategoriesGetErrors[keyof ListCategoriesV1CategoriesGetErrors];

export type ListCategoriesV1CategoriesGetResponses = {
  /**
   * Successful Response
   */
  200: CategoryListResponse;
};

export type ListCategoriesV1CategoriesGetResponse =
  ListCategoriesV1CategoriesGetResponses[keyof ListCategoriesV1CategoriesGetResponses];

export type ListEntriesV1JournalGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Tag
     *
     * Filter by tag.
     */
    tag?: string | null;
    /**
     * Search
     *
     * Search body text.
     */
    search?: string | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<JournalSortProperty> | null;
  };
  url: "/v1/journal";
};

export type ListEntriesV1JournalGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListEntriesV1JournalGetError =
  ListEntriesV1JournalGetErrors[keyof ListEntriesV1JournalGetErrors];

export type ListEntriesV1JournalGetResponses = {
  /**
   * Successful Response
   */
  200: JournalEntryListResponse;
};

export type ListEntriesV1JournalGetResponse =
  ListEntriesV1JournalGetResponses[keyof ListEntriesV1JournalGetResponses];

export type GetCalendarV1JournalCalendarGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Year
     *
     * Year.
     */
    year: number;
    /**
     * Month
     *
     * Month.
     */
    month: number;
  };
  url: "/v1/journal/calendar";
};

export type GetCalendarV1JournalCalendarGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCalendarV1JournalCalendarGetError =
  GetCalendarV1JournalCalendarGetErrors[keyof GetCalendarV1JournalCalendarGetErrors];

export type GetCalendarV1JournalCalendarGetResponses = {
  /**
   * Successful Response
   */
  200: JournalCalendarResponse;
};

export type GetCalendarV1JournalCalendarGetResponse =
  GetCalendarV1JournalCalendarGetResponses[keyof GetCalendarV1JournalCalendarGetResponses];

export type GetStreakV1JournalStreakGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/journal/streak";
};

export type GetStreakV1JournalStreakGetResponses = {
  /**
   * Successful Response
   */
  200: JournalStreakResponse;
};

export type GetStreakV1JournalStreakGetResponse =
  GetStreakV1JournalStreakGetResponses[keyof GetStreakV1JournalStreakGetResponses];

export type DeleteEntryV1JournalEntryDateDeleteData = {
  body?: never;
  path: {
    /**
     * Entry Date
     */
    entry_date: Date;
  };
  query?: never;
  url: "/v1/journal/{entry_date}";
};

export type DeleteEntryV1JournalEntryDateDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteEntryV1JournalEntryDateDeleteError =
  DeleteEntryV1JournalEntryDateDeleteErrors[keyof DeleteEntryV1JournalEntryDateDeleteErrors];

export type DeleteEntryV1JournalEntryDateDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteEntryV1JournalEntryDateDeleteResponse =
  DeleteEntryV1JournalEntryDateDeleteResponses[keyof DeleteEntryV1JournalEntryDateDeleteResponses];

export type GetEntryV1JournalEntryDateGetData = {
  body?: never;
  path: {
    /**
     * Entry Date
     */
    entry_date: Date;
  };
  query?: never;
  url: "/v1/journal/{entry_date}";
};

export type GetEntryV1JournalEntryDateGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetEntryV1JournalEntryDateGetError =
  GetEntryV1JournalEntryDateGetErrors[keyof GetEntryV1JournalEntryDateGetErrors];

export type GetEntryV1JournalEntryDateGetResponses = {
  /**
   * Response Get Entry V1 Journal  Entry Date  Get
   *
   * Successful Response
   */
  200: JournalEntrySchema | null;
};

export type GetEntryV1JournalEntryDateGetResponse =
  GetEntryV1JournalEntryDateGetResponses[keyof GetEntryV1JournalEntryDateGetResponses];

export type UpsertEntryV1JournalEntryDatePutData = {
  body: JournalEntryUpsert;
  path: {
    /**
     * Entry Date
     */
    entry_date: Date;
  };
  query?: never;
  url: "/v1/journal/{entry_date}";
};

export type UpsertEntryV1JournalEntryDatePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpsertEntryV1JournalEntryDatePutError =
  UpsertEntryV1JournalEntryDatePutErrors[keyof UpsertEntryV1JournalEntryDatePutErrors];

export type UpsertEntryV1JournalEntryDatePutResponses = {
  /**
   * Successful Response
   */
  200: JournalEntrySchema;
};

export type UpsertEntryV1JournalEntryDatePutResponse =
  UpsertEntryV1JournalEntryDatePutResponses[keyof UpsertEntryV1JournalEntryDatePutResponses];

export type ListPlacesV1PlacesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     *
     * Filter by status.
     */
    status?: PlaceStatus | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<PlaceSortProperty> | null;
  };
  url: "/v1/places";
};

export type ListPlacesV1PlacesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListPlacesV1PlacesGetError =
  ListPlacesV1PlacesGetErrors[keyof ListPlacesV1PlacesGetErrors];

export type ListPlacesV1PlacesGetResponses = {
  /**
   * Successful Response
   */
  200: PlaceListResponse;
};

export type ListPlacesV1PlacesGetResponse =
  ListPlacesV1PlacesGetResponses[keyof ListPlacesV1PlacesGetResponses];

export type CreatePlaceV1PlacesPostData = {
  body: PlaceCreate;
  path?: never;
  query?: never;
  url: "/v1/places";
};

export type CreatePlaceV1PlacesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePlaceV1PlacesPostError =
  CreatePlaceV1PlacesPostErrors[keyof CreatePlaceV1PlacesPostErrors];

export type CreatePlaceV1PlacesPostResponses = {
  /**
   * Successful Response
   */
  201: PlaceSchema;
};

export type CreatePlaceV1PlacesPostResponse =
  CreatePlaceV1PlacesPostResponses[keyof CreatePlaceV1PlacesPostResponses];

export type SearchGooglePlacesV1PlacesSearchGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query
     *
     * Search query for Google Places.
     */
    query: string;
  };
  url: "/v1/places/search";
};

export type SearchGooglePlacesV1PlacesSearchGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchGooglePlacesV1PlacesSearchGetError =
  SearchGooglePlacesV1PlacesSearchGetErrors[keyof SearchGooglePlacesV1PlacesSearchGetErrors];

export type SearchGooglePlacesV1PlacesSearchGetResponses = {
  /**
   * Successful Response
   */
  200: GooglePlaceSearchResponse;
};

export type SearchGooglePlacesV1PlacesSearchGetResponse =
  SearchGooglePlacesV1PlacesSearchGetResponses[keyof SearchGooglePlacesV1PlacesSearchGetResponses];

export type DeletePlaceV1PlacesPlaceIdDeleteData = {
  body?: never;
  path: {
    /**
     * Place Id
     */
    place_id: string;
  };
  query?: never;
  url: "/v1/places/{place_id}";
};

export type DeletePlaceV1PlacesPlaceIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePlaceV1PlacesPlaceIdDeleteError =
  DeletePlaceV1PlacesPlaceIdDeleteErrors[keyof DeletePlaceV1PlacesPlaceIdDeleteErrors];

export type DeletePlaceV1PlacesPlaceIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeletePlaceV1PlacesPlaceIdDeleteResponse =
  DeletePlaceV1PlacesPlaceIdDeleteResponses[keyof DeletePlaceV1PlacesPlaceIdDeleteResponses];

export type UpdatePlaceV1PlacesPlaceIdPatchData = {
  body: PlaceUpdate;
  path: {
    /**
     * Place Id
     */
    place_id: string;
  };
  query?: never;
  url: "/v1/places/{place_id}";
};

export type UpdatePlaceV1PlacesPlaceIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePlaceV1PlacesPlaceIdPatchError =
  UpdatePlaceV1PlacesPlaceIdPatchErrors[keyof UpdatePlaceV1PlacesPlaceIdPatchErrors];

export type UpdatePlaceV1PlacesPlaceIdPatchResponses = {
  /**
   * Successful Response
   */
  200: PlaceSchema;
};

export type UpdatePlaceV1PlacesPlaceIdPatchResponse =
  UpdatePlaceV1PlacesPlaceIdPatchResponses[keyof UpdatePlaceV1PlacesPlaceIdPatchResponses];

export type ListTasksV1TasksGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     *
     * Filter by status.
     */
    status?: TaskStatus | null;
    /**
     * Priority
     *
     * Filter by priority.
     */
    priority?: number | null;
    /**
     * Project
     *
     * Filter by project.
     */
    project?: string | null;
    /**
     * Area
     *
     * Filter by area.
     */
    area?: string | null;
    /**
     * Is Recurring
     *
     * Filter by recurring.
     */
    is_recurring?: boolean | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<TaskSortProperty> | null;
  };
  url: "/v1/tasks";
};

export type ListTasksV1TasksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTasksV1TasksGetError =
  ListTasksV1TasksGetErrors[keyof ListTasksV1TasksGetErrors];

export type ListTasksV1TasksGetResponses = {
  /**
   * Successful Response
   */
  200: TaskListResponse;
};

export type ListTasksV1TasksGetResponse =
  ListTasksV1TasksGetResponses[keyof ListTasksV1TasksGetResponses];

export type CreateTaskV1TasksPostData = {
  body: TaskCreate;
  path?: never;
  query?: never;
  url: "/v1/tasks";
};

export type CreateTaskV1TasksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTaskV1TasksPostError =
  CreateTaskV1TasksPostErrors[keyof CreateTaskV1TasksPostErrors];

export type CreateTaskV1TasksPostResponses = {
  /**
   * Successful Response
   */
  201: TaskSchema;
};

export type CreateTaskV1TasksPostResponse =
  CreateTaskV1TasksPostResponses[keyof CreateTaskV1TasksPostResponses];

export type DeleteTaskV1TasksTaskIdDeleteData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type DeleteTaskV1TasksTaskIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTaskV1TasksTaskIdDeleteError =
  DeleteTaskV1TasksTaskIdDeleteErrors[keyof DeleteTaskV1TasksTaskIdDeleteErrors];

export type DeleteTaskV1TasksTaskIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTaskV1TasksTaskIdDeleteResponse =
  DeleteTaskV1TasksTaskIdDeleteResponses[keyof DeleteTaskV1TasksTaskIdDeleteResponses];

export type UpdateTaskV1TasksTaskIdPatchData = {
  body: TaskUpdate;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}";
};

export type UpdateTaskV1TasksTaskIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTaskV1TasksTaskIdPatchError =
  UpdateTaskV1TasksTaskIdPatchErrors[keyof UpdateTaskV1TasksTaskIdPatchErrors];

export type UpdateTaskV1TasksTaskIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TaskSchema;
};

export type UpdateTaskV1TasksTaskIdPatchResponse =
  UpdateTaskV1TasksTaskIdPatchResponses[keyof UpdateTaskV1TasksTaskIdPatchResponses];

export type CompleteTaskV1TasksTaskIdCompletePostData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/complete";
};

export type CompleteTaskV1TasksTaskIdCompletePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CompleteTaskV1TasksTaskIdCompletePostError =
  CompleteTaskV1TasksTaskIdCompletePostErrors[keyof CompleteTaskV1TasksTaskIdCompletePostErrors];

export type CompleteTaskV1TasksTaskIdCompletePostResponses = {
  /**
   * Successful Response
   */
  200: TaskCompleteResponse;
};

export type CompleteTaskV1TasksTaskIdCompletePostResponse =
  CompleteTaskV1TasksTaskIdCompletePostResponses[keyof CompleteTaskV1TasksTaskIdCompletePostResponses];

export type ReopenTaskV1TasksTaskIdReopenPostData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: string;
  };
  query?: never;
  url: "/v1/tasks/{task_id}/reopen";
};

export type ReopenTaskV1TasksTaskIdReopenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReopenTaskV1TasksTaskIdReopenPostError =
  ReopenTaskV1TasksTaskIdReopenPostErrors[keyof ReopenTaskV1TasksTaskIdReopenPostErrors];

export type ReopenTaskV1TasksTaskIdReopenPostResponses = {
  /**
   * Successful Response
   */
  200: TaskSchema;
};

export type ReopenTaskV1TasksTaskIdReopenPostResponse =
  ReopenTaskV1TasksTaskIdReopenPostResponses[keyof ReopenTaskV1TasksTaskIdReopenPostResponses];

export type ReorderTasksV1TasksReorderPatchData = {
  /**
   * Body
   */
  body: Array<TaskReorderItem>;
  path?: never;
  query?: never;
  url: "/v1/tasks/reorder";
};

export type ReorderTasksV1TasksReorderPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReorderTasksV1TasksReorderPatchError =
  ReorderTasksV1TasksReorderPatchErrors[keyof ReorderTasksV1TasksReorderPatchErrors];

export type ReorderTasksV1TasksReorderPatchResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ReorderTasksV1TasksReorderPatchResponse =
  ReorderTasksV1TasksReorderPatchResponses[keyof ReorderTasksV1TasksReorderPatchResponses];

export type ListProjectsV1TasksProjectsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/tasks/projects";
};

export type ListProjectsV1TasksProjectsGetResponses = {
  /**
   * Response List Projects V1 Tasks Projects Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ListProjectsV1TasksProjectsGetResponse =
  ListProjectsV1TasksProjectsGetResponses[keyof ListProjectsV1TasksProjectsGetResponses];

export type ListAreasV1TasksAreasGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/tasks/areas";
};

export type ListAreasV1TasksAreasGetResponses = {
  /**
   * Response List Areas V1 Tasks Areas Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type ListAreasV1TasksAreasGetResponse =
  ListAreasV1TasksAreasGetResponses[keyof ListAreasV1TasksAreasGetResponses];

export type DeleteTransactionsV1TransactionsDeleteData = {
  body: BulkDeleteRequest;
  path?: never;
  query?: never;
  url: "/v1/transactions";
};

export type DeleteTransactionsV1TransactionsDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTransactionsV1TransactionsDeleteError =
  DeleteTransactionsV1TransactionsDeleteErrors[keyof DeleteTransactionsV1TransactionsDeleteErrors];

export type DeleteTransactionsV1TransactionsDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTransactionsV1TransactionsDeleteResponse =
  DeleteTransactionsV1TransactionsDeleteResponses[keyof DeleteTransactionsV1TransactionsDeleteResponses];

export type ListTransactionsV1TransactionsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Bank Account Id
     *
     * Filter by bank account ID.
     */
    bank_account_id?: string | null;
    /**
     * Page
     *
     * Page number, defaults to 1.
     */
    page?: number;
    /**
     * Limit
     *
     * Size of a page, defaults to 10. Maximum is 100.
     */
    limit?: number;
    /**
     * Sorting
     *
     * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
     */
    sorting?: Array<TransactionSortProperty> | null;
  };
  url: "/v1/transactions";
};

export type ListTransactionsV1TransactionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTransactionsV1TransactionsGetError =
  ListTransactionsV1TransactionsGetErrors[keyof ListTransactionsV1TransactionsGetErrors];

export type ListTransactionsV1TransactionsGetResponses = {
  /**
   * Successful Response
   */
  200: TransactionListResponse;
};

export type ListTransactionsV1TransactionsGetResponse =
  ListTransactionsV1TransactionsGetResponses[keyof ListTransactionsV1TransactionsGetResponses];

export type ImportTransactionsV1TransactionsImportPostData = {
  body: BodyImportTransactionsV1TransactionsImportPost;
  path?: never;
  query: {
    /**
     * Bank
     *
     * Bank identifier, e.g. 'marginalen'.
     */
    bank: string;
    /**
     * Bank Account Id
     *
     * Bank account to attach transactions to.
     */
    bank_account_id: string;
  };
  url: "/v1/transactions/import";
};

export type ImportTransactionsV1TransactionsImportPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImportTransactionsV1TransactionsImportPostError =
  ImportTransactionsV1TransactionsImportPostErrors[keyof ImportTransactionsV1TransactionsImportPostErrors];

export type ImportTransactionsV1TransactionsImportPostResponses = {
  /**
   * Successful Response
   */
  200: ImportResponse;
};

export type ImportTransactionsV1TransactionsImportPostResponse =
  ImportTransactionsV1TransactionsImportPostResponses[keyof ImportTransactionsV1TransactionsImportPostResponses];

export type UpdateTransactionV1TransactionsTransactionIdPatchData = {
  body: TransactionUpdate;
  path: {
    /**
     * Transaction Id
     */
    transaction_id: string;
  };
  query?: never;
  url: "/v1/transactions/{transaction_id}";
};

export type UpdateTransactionV1TransactionsTransactionIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTransactionV1TransactionsTransactionIdPatchError =
  UpdateTransactionV1TransactionsTransactionIdPatchErrors[keyof UpdateTransactionV1TransactionsTransactionIdPatchErrors];

export type UpdateTransactionV1TransactionsTransactionIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TransactionSchema;
};

export type UpdateTransactionV1TransactionsTransactionIdPatchResponse =
  UpdateTransactionV1TransactionsTransactionIdPatchResponses[keyof UpdateTransactionV1TransactionsTransactionIdPatchResponses];
