// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen.js";
import {
  bulkUpdateTransactionsV1TransactionsBulkPatch,
  categorizeByDescriptionV1TransactionsCategorizeByDescriptionPost,
  completeTaskV1TasksTaskIdCompletePost,
  createBankAccountV1BankAccountsPost,
  createCounterV1CountersPost,
  createNotificationV1NotificationsPost,
  createPlaceV1PlacesPost,
  createProjectV1ProjectsPost,
  createRecipeV1RecipesPost,
  createResetV1CountersCounterIdResetsPost,
  createSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPost,
  createSecurityV1InvestmentsSecuritiesPost,
  createTaskV1TasksPost,
  createTradeV1InvestmentsTradesPost,
  deleteBankAccountV1BankAccountsBankAccountIdDelete,
  deleteCounterV1CountersCounterIdDelete,
  deleteDeviceV1DevicesDeviceIdDelete,
  deletePlaceV1PlacesPlaceIdDelete,
  deleteProjectV1ProjectsProjectIdDelete,
  deleteRecipeV1RecipesRecipeIdDelete,
  deleteSecurityV1InvestmentsSecuritiesSecurityIdDelete,
  deleteTaskV1TasksTaskIdDelete,
  deleteTradeV1InvestmentsTradesTradeIdDelete,
  deleteTransactionsV1TransactionsDelete,
  getActivitySummaryV1ActivitySummaryGet,
  getBankAccountV1BankAccountsBankAccountIdGet,
  getCryptoPriceV1InvestmentsCryptoPriceCoinIdGet,
  getDailyActivityV1ActivityDailyGet,
  getHoldingsV1InvestmentsHoldingsGet,
  getIntradayActivityV1ActivityIntradayGet,
  getKlarnaTransactionsV1KlarnaTransactionsGet,
  getMeV1AuthMeGet,
  getRecipeV1RecipesRecipeIdGet,
  getTaskV1TasksTaskIdGet,
  getWeatherForecastV1WeatherGet,
  healthzHealthzGet,
  importKlarnaTransactionsV1KlarnaImportPost,
  importTransactionsV1TransactionsImportPost,
  ingestActivityBatchV1ActivityBatchPost,
  listActivitySourcesV1ActivitySourcesGet,
  listAreasV1TasksAreasGet,
  listBankAccountsV1BankAccountsGet,
  listCategoriesV1CategoriesGet,
  listCountersV1CountersGet,
  listDevicesV1DevicesGet,
  listHealthkitWorkoutsV1HealthkitWorkoutsGet,
  listNotificationsV1NotificationsGet,
  listPlacesV1PlacesGet,
  listProjectsV1ProjectsGet,
  listRecipesV1RecipesGet,
  listResetsV1CountersCounterIdResetsGet,
  listSecuritiesV1InvestmentsSecuritiesGet,
  listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGet,
  listTasksV1TasksGet,
  listTradesV1InvestmentsTradesGet,
  listTransactionsV1TransactionsGet,
  markAllNotificationsReadV1NotificationsReadAllPost,
  markNotificationReadV1NotificationsNotificationIdReadPost,
  monthlyFlowV1TransactionsMonthlyFlowGet,
  type Options,
  reopenTaskV1TasksTaskIdReopenPost,
  reorderTasksV1TasksReorderPatch,
  searchGooglePlacesV1PlacesSearchGet,
  setProjectLocationV1ProjectsProjectIdLocationPut,
  spendingByCategoryV1TransactionsSpendingByCategoryGet,
  syncHealthkitWorkoutsV1HealthkitWorkoutsSyncPost,
  undoResetV1CountersCounterIdResetsResetIdDelete,
  updateBankAccountV1BankAccountsBankAccountIdPatch,
  updateCounterV1CountersCounterIdPatch,
  updateDeviceV1DevicesDeviceIdPatch,
  updatePlaceV1PlacesPlaceIdPatch,
  updateProjectV1ProjectsProjectIdPatch,
  updateRecipeV1RecipesRecipeIdPatch,
  updateSecurityV1InvestmentsSecuritiesSecurityIdPatch,
  updateTaskV1TasksTaskIdPatch,
  updateTradeV1InvestmentsTradesTradeIdPatch,
  updateTransactionV1TransactionsTransactionIdPatch,
} from "../sdk.gen.js";
import type {
  BulkUpdateTransactionsV1TransactionsBulkPatchData,
  BulkUpdateTransactionsV1TransactionsBulkPatchError,
  BulkUpdateTransactionsV1TransactionsBulkPatchResponse,
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostData,
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostError,
  CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponse,
  CompleteTaskV1TasksTaskIdCompletePostData,
  CompleteTaskV1TasksTaskIdCompletePostError,
  CompleteTaskV1TasksTaskIdCompletePostResponse,
  CreateBankAccountV1BankAccountsPostData,
  CreateBankAccountV1BankAccountsPostError,
  CreateBankAccountV1BankAccountsPostResponse,
  CreateCounterV1CountersPostData,
  CreateCounterV1CountersPostError,
  CreateCounterV1CountersPostResponse,
  CreateNotificationV1NotificationsPostData,
  CreateNotificationV1NotificationsPostError,
  CreateNotificationV1NotificationsPostResponse,
  CreatePlaceV1PlacesPostData,
  CreatePlaceV1PlacesPostError,
  CreatePlaceV1PlacesPostResponse,
  CreateProjectV1ProjectsPostData,
  CreateProjectV1ProjectsPostError,
  CreateProjectV1ProjectsPostResponse,
  CreateRecipeV1RecipesPostData,
  CreateRecipeV1RecipesPostError,
  CreateRecipeV1RecipesPostResponse,
  CreateResetV1CountersCounterIdResetsPostData,
  CreateResetV1CountersCounterIdResetsPostError,
  CreateResetV1CountersCounterIdResetsPostResponse,
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostData,
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostError,
  CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponse,
  CreateSecurityV1InvestmentsSecuritiesPostData,
  CreateSecurityV1InvestmentsSecuritiesPostError,
  CreateSecurityV1InvestmentsSecuritiesPostResponse,
  CreateTaskV1TasksPostData,
  CreateTaskV1TasksPostError,
  CreateTaskV1TasksPostResponse,
  CreateTradeV1InvestmentsTradesPostData,
  CreateTradeV1InvestmentsTradesPostError,
  CreateTradeV1InvestmentsTradesPostResponse,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteData,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteError,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse,
  DeleteCounterV1CountersCounterIdDeleteData,
  DeleteCounterV1CountersCounterIdDeleteError,
  DeleteCounterV1CountersCounterIdDeleteResponse,
  DeleteDeviceV1DevicesDeviceIdDeleteData,
  DeleteDeviceV1DevicesDeviceIdDeleteError,
  DeleteDeviceV1DevicesDeviceIdDeleteResponse,
  DeletePlaceV1PlacesPlaceIdDeleteData,
  DeletePlaceV1PlacesPlaceIdDeleteError,
  DeletePlaceV1PlacesPlaceIdDeleteResponse,
  DeleteProjectV1ProjectsProjectIdDeleteData,
  DeleteProjectV1ProjectsProjectIdDeleteError,
  DeleteProjectV1ProjectsProjectIdDeleteResponse,
  DeleteRecipeV1RecipesRecipeIdDeleteData,
  DeleteRecipeV1RecipesRecipeIdDeleteError,
  DeleteRecipeV1RecipesRecipeIdDeleteResponse,
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteData,
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteError,
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponse,
  DeleteTaskV1TasksTaskIdDeleteData,
  DeleteTaskV1TasksTaskIdDeleteError,
  DeleteTaskV1TasksTaskIdDeleteResponse,
  DeleteTradeV1InvestmentsTradesTradeIdDeleteData,
  DeleteTradeV1InvestmentsTradesTradeIdDeleteError,
  DeleteTradeV1InvestmentsTradesTradeIdDeleteResponse,
  DeleteTransactionsV1TransactionsDeleteData,
  DeleteTransactionsV1TransactionsDeleteError,
  DeleteTransactionsV1TransactionsDeleteResponse,
  GetActivitySummaryV1ActivitySummaryGetData,
  GetActivitySummaryV1ActivitySummaryGetError,
  GetActivitySummaryV1ActivitySummaryGetResponse,
  GetBankAccountV1BankAccountsBankAccountIdGetData,
  GetBankAccountV1BankAccountsBankAccountIdGetError,
  GetBankAccountV1BankAccountsBankAccountIdGetResponse,
  GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetData,
  GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetError,
  GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetResponse,
  GetDailyActivityV1ActivityDailyGetData,
  GetDailyActivityV1ActivityDailyGetError,
  GetDailyActivityV1ActivityDailyGetResponse,
  GetHoldingsV1InvestmentsHoldingsGetData,
  GetHoldingsV1InvestmentsHoldingsGetResponse,
  GetIntradayActivityV1ActivityIntradayGetData,
  GetIntradayActivityV1ActivityIntradayGetError,
  GetIntradayActivityV1ActivityIntradayGetResponse,
  GetKlarnaTransactionsV1KlarnaTransactionsGetData,
  GetKlarnaTransactionsV1KlarnaTransactionsGetError,
  GetKlarnaTransactionsV1KlarnaTransactionsGetResponse,
  GetMeV1AuthMeGetData,
  GetMeV1AuthMeGetResponse,
  GetRecipeV1RecipesRecipeIdGetData,
  GetRecipeV1RecipesRecipeIdGetError,
  GetRecipeV1RecipesRecipeIdGetResponse,
  GetTaskV1TasksTaskIdGetData,
  GetTaskV1TasksTaskIdGetError,
  GetTaskV1TasksTaskIdGetResponse,
  GetWeatherForecastV1WeatherGetData,
  GetWeatherForecastV1WeatherGetError,
  GetWeatherForecastV1WeatherGetResponse,
  HealthzHealthzGetData,
  ImportKlarnaTransactionsV1KlarnaImportPostData,
  ImportKlarnaTransactionsV1KlarnaImportPostError,
  ImportKlarnaTransactionsV1KlarnaImportPostResponse,
  ImportTransactionsV1TransactionsImportPostData,
  ImportTransactionsV1TransactionsImportPostError,
  ImportTransactionsV1TransactionsImportPostResponse,
  IngestActivityBatchV1ActivityBatchPostData,
  IngestActivityBatchV1ActivityBatchPostError,
  IngestActivityBatchV1ActivityBatchPostResponse,
  ListActivitySourcesV1ActivitySourcesGetData,
  ListActivitySourcesV1ActivitySourcesGetResponse,
  ListAreasV1TasksAreasGetData,
  ListAreasV1TasksAreasGetResponse,
  ListBankAccountsV1BankAccountsGetData,
  ListBankAccountsV1BankAccountsGetError,
  ListBankAccountsV1BankAccountsGetResponse,
  ListCategoriesV1CategoriesGetData,
  ListCategoriesV1CategoriesGetError,
  ListCategoriesV1CategoriesGetResponse,
  ListCountersV1CountersGetData,
  ListCountersV1CountersGetResponse,
  ListDevicesV1DevicesGetData,
  ListDevicesV1DevicesGetResponse,
  ListHealthkitWorkoutsV1HealthkitWorkoutsGetData,
  ListHealthkitWorkoutsV1HealthkitWorkoutsGetError,
  ListHealthkitWorkoutsV1HealthkitWorkoutsGetResponse,
  ListNotificationsV1NotificationsGetData,
  ListNotificationsV1NotificationsGetResponse,
  ListPlacesV1PlacesGetData,
  ListPlacesV1PlacesGetError,
  ListPlacesV1PlacesGetResponse,
  ListProjectsV1ProjectsGetData,
  ListProjectsV1ProjectsGetError,
  ListProjectsV1ProjectsGetResponse,
  ListRecipesV1RecipesGetData,
  ListRecipesV1RecipesGetError,
  ListRecipesV1RecipesGetResponse,
  ListResetsV1CountersCounterIdResetsGetData,
  ListResetsV1CountersCounterIdResetsGetError,
  ListResetsV1CountersCounterIdResetsGetResponse,
  ListSecuritiesV1InvestmentsSecuritiesGetData,
  ListSecuritiesV1InvestmentsSecuritiesGetError,
  ListSecuritiesV1InvestmentsSecuritiesGetResponse,
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData,
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetError,
  ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse,
  ListTasksV1TasksGetData,
  ListTasksV1TasksGetError,
  ListTasksV1TasksGetResponse,
  ListTradesV1InvestmentsTradesGetData,
  ListTradesV1InvestmentsTradesGetError,
  ListTradesV1InvestmentsTradesGetResponse,
  ListTransactionsV1TransactionsGetData,
  ListTransactionsV1TransactionsGetError,
  ListTransactionsV1TransactionsGetResponse,
  MarkAllNotificationsReadV1NotificationsReadAllPostData,
  MarkAllNotificationsReadV1NotificationsReadAllPostResponse,
  MarkNotificationReadV1NotificationsNotificationIdReadPostData,
  MarkNotificationReadV1NotificationsNotificationIdReadPostError,
  MarkNotificationReadV1NotificationsNotificationIdReadPostResponse,
  MonthlyFlowV1TransactionsMonthlyFlowGetData,
  MonthlyFlowV1TransactionsMonthlyFlowGetError,
  MonthlyFlowV1TransactionsMonthlyFlowGetResponse,
  ReopenTaskV1TasksTaskIdReopenPostData,
  ReopenTaskV1TasksTaskIdReopenPostError,
  ReopenTaskV1TasksTaskIdReopenPostResponse,
  ReorderTasksV1TasksReorderPatchData,
  ReorderTasksV1TasksReorderPatchError,
  ReorderTasksV1TasksReorderPatchResponse,
  SearchGooglePlacesV1PlacesSearchGetData,
  SearchGooglePlacesV1PlacesSearchGetError,
  SearchGooglePlacesV1PlacesSearchGetResponse,
  SetProjectLocationV1ProjectsProjectIdLocationPutData,
  SetProjectLocationV1ProjectsProjectIdLocationPutError,
  SetProjectLocationV1ProjectsProjectIdLocationPutResponse,
  SpendingByCategoryV1TransactionsSpendingByCategoryGetData,
  SpendingByCategoryV1TransactionsSpendingByCategoryGetError,
  SpendingByCategoryV1TransactionsSpendingByCategoryGetResponse,
  SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostData,
  SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostError,
  SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostResponse,
  UndoResetV1CountersCounterIdResetsResetIdDeleteData,
  UndoResetV1CountersCounterIdResetsResetIdDeleteError,
  UndoResetV1CountersCounterIdResetsResetIdDeleteResponse,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchData,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchError,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
  UpdateCounterV1CountersCounterIdPatchData,
  UpdateCounterV1CountersCounterIdPatchError,
  UpdateCounterV1CountersCounterIdPatchResponse,
  UpdateDeviceV1DevicesDeviceIdPatchData,
  UpdateDeviceV1DevicesDeviceIdPatchError,
  UpdateDeviceV1DevicesDeviceIdPatchResponse,
  UpdatePlaceV1PlacesPlaceIdPatchData,
  UpdatePlaceV1PlacesPlaceIdPatchError,
  UpdatePlaceV1PlacesPlaceIdPatchResponse,
  UpdateProjectV1ProjectsProjectIdPatchData,
  UpdateProjectV1ProjectsProjectIdPatchError,
  UpdateProjectV1ProjectsProjectIdPatchResponse,
  UpdateRecipeV1RecipesRecipeIdPatchData,
  UpdateRecipeV1RecipesRecipeIdPatchError,
  UpdateRecipeV1RecipesRecipeIdPatchResponse,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchData,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchError,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponse,
  UpdateTaskV1TasksTaskIdPatchData,
  UpdateTaskV1TasksTaskIdPatchError,
  UpdateTaskV1TasksTaskIdPatchResponse,
  UpdateTradeV1InvestmentsTradesTradeIdPatchData,
  UpdateTradeV1InvestmentsTradesTradeIdPatchError,
  UpdateTradeV1InvestmentsTradesTradeIdPatchResponse,
  UpdateTransactionV1TransactionsTransactionIdPatchData,
  UpdateTransactionV1TransactionsTransactionIdPatchError,
  UpdateTransactionV1TransactionsTransactionIdPatchResponse,
} from "../types.gen.js";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthzHealthzGetQueryKey = (
  options?: Options<HealthzHealthzGetData>,
) => createQueryKey("healthzHealthzGet", options);

/**
 * Healthz
 */
export const healthzHealthzGetOptions = (
  options?: Options<HealthzHealthzGetData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthzHealthzGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthzHealthzGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthzHealthzGetQueryKey(options),
  });

export const getMeV1AuthMeGetQueryKey = (
  options?: Options<GetMeV1AuthMeGetData>,
) => createQueryKey("getMeV1AuthMeGet", options);

/**
 * Get Current User
 */
export const getMeV1AuthMeGetOptions = (
  options?: Options<GetMeV1AuthMeGetData>,
) =>
  queryOptions<
    GetMeV1AuthMeGetResponse,
    DefaultError,
    GetMeV1AuthMeGetResponse,
    ReturnType<typeof getMeV1AuthMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMeV1AuthMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMeV1AuthMeGetQueryKey(options),
  });

/**
 * Ingest Activity Events
 */
export const ingestActivityBatchV1ActivityBatchPostMutation = (
  options?: Partial<Options<IngestActivityBatchV1ActivityBatchPostData>>,
): UseMutationOptions<
  IngestActivityBatchV1ActivityBatchPostResponse,
  IngestActivityBatchV1ActivityBatchPostError,
  Options<IngestActivityBatchV1ActivityBatchPostData>
> => {
  const mutationOptions: UseMutationOptions<
    IngestActivityBatchV1ActivityBatchPostResponse,
    IngestActivityBatchV1ActivityBatchPostError,
    Options<IngestActivityBatchV1ActivityBatchPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await ingestActivityBatchV1ActivityBatchPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listActivitySourcesV1ActivitySourcesGetQueryKey = (
  options?: Options<ListActivitySourcesV1ActivitySourcesGetData>,
) => createQueryKey("listActivitySourcesV1ActivitySourcesGet", options);

/**
 * List Activity Sources
 */
export const listActivitySourcesV1ActivitySourcesGetOptions = (
  options?: Options<ListActivitySourcesV1ActivitySourcesGetData>,
) =>
  queryOptions<
    ListActivitySourcesV1ActivitySourcesGetResponse,
    DefaultError,
    ListActivitySourcesV1ActivitySourcesGetResponse,
    ReturnType<typeof listActivitySourcesV1ActivitySourcesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listActivitySourcesV1ActivitySourcesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listActivitySourcesV1ActivitySourcesGetQueryKey(options),
  });

export const getActivitySummaryV1ActivitySummaryGetQueryKey = (
  options: Options<GetActivitySummaryV1ActivitySummaryGetData>,
) => createQueryKey("getActivitySummaryV1ActivitySummaryGet", options);

/**
 * Get Activity Summary
 */
export const getActivitySummaryV1ActivitySummaryGetOptions = (
  options: Options<GetActivitySummaryV1ActivitySummaryGetData>,
) =>
  queryOptions<
    GetActivitySummaryV1ActivitySummaryGetResponse,
    GetActivitySummaryV1ActivitySummaryGetError,
    GetActivitySummaryV1ActivitySummaryGetResponse,
    ReturnType<typeof getActivitySummaryV1ActivitySummaryGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getActivitySummaryV1ActivitySummaryGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getActivitySummaryV1ActivitySummaryGetQueryKey(options),
  });

export const getDailyActivityV1ActivityDailyGetQueryKey = (
  options: Options<GetDailyActivityV1ActivityDailyGetData>,
) => createQueryKey("getDailyActivityV1ActivityDailyGet", options);

/**
 * Get Daily Activity Totals
 */
export const getDailyActivityV1ActivityDailyGetOptions = (
  options: Options<GetDailyActivityV1ActivityDailyGetData>,
) =>
  queryOptions<
    GetDailyActivityV1ActivityDailyGetResponse,
    GetDailyActivityV1ActivityDailyGetError,
    GetDailyActivityV1ActivityDailyGetResponse,
    ReturnType<typeof getDailyActivityV1ActivityDailyGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDailyActivityV1ActivityDailyGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDailyActivityV1ActivityDailyGetQueryKey(options),
  });

export const getIntradayActivityV1ActivityIntradayGetQueryKey = (
  options: Options<GetIntradayActivityV1ActivityIntradayGetData>,
) => createQueryKey("getIntradayActivityV1ActivityIntradayGet", options);

/**
 * Get Intraday Activity
 */
export const getIntradayActivityV1ActivityIntradayGetOptions = (
  options: Options<GetIntradayActivityV1ActivityIntradayGetData>,
) =>
  queryOptions<
    GetIntradayActivityV1ActivityIntradayGetResponse,
    GetIntradayActivityV1ActivityIntradayGetError,
    GetIntradayActivityV1ActivityIntradayGetResponse,
    ReturnType<typeof getIntradayActivityV1ActivityIntradayGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIntradayActivityV1ActivityIntradayGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIntradayActivityV1ActivityIntradayGetQueryKey(options),
  });

export const listBankAccountsV1BankAccountsGetQueryKey = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
) => createQueryKey("listBankAccountsV1BankAccountsGet", options);

/**
 * List Bank Accounts
 *
 * List all bank accounts.
 */
export const listBankAccountsV1BankAccountsGetOptions = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
) =>
  queryOptions<
    ListBankAccountsV1BankAccountsGetResponse,
    ListBankAccountsV1BankAccountsGetError,
    ListBankAccountsV1BankAccountsGetResponse,
    ReturnType<typeof listBankAccountsV1BankAccountsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listBankAccountsV1BankAccountsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listBankAccountsV1BankAccountsGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listBankAccountsV1BankAccountsGetInfiniteQueryKey = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
): QueryKey<Options<ListBankAccountsV1BankAccountsGetData>> =>
  createQueryKey("listBankAccountsV1BankAccountsGet", options, true);

/**
 * List Bank Accounts
 *
 * List all bank accounts.
 */
export const listBankAccountsV1BankAccountsGetInfiniteOptions = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
) =>
  infiniteQueryOptions<
    ListBankAccountsV1BankAccountsGetResponse,
    ListBankAccountsV1BankAccountsGetError,
    InfiniteData<ListBankAccountsV1BankAccountsGetResponse>,
    QueryKey<Options<ListBankAccountsV1BankAccountsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListBankAccountsV1BankAccountsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListBankAccountsV1BankAccountsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listBankAccountsV1BankAccountsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listBankAccountsV1BankAccountsGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Bank Account
 *
 * Create a new bank account.
 */
export const createBankAccountV1BankAccountsPostMutation = (
  options?: Partial<Options<CreateBankAccountV1BankAccountsPostData>>,
): UseMutationOptions<
  CreateBankAccountV1BankAccountsPostResponse,
  CreateBankAccountV1BankAccountsPostError,
  Options<CreateBankAccountV1BankAccountsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBankAccountV1BankAccountsPostResponse,
    CreateBankAccountV1BankAccountsPostError,
    Options<CreateBankAccountV1BankAccountsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createBankAccountV1BankAccountsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Bank Account
 *
 * Delete a bank account and all its transactions.
 */
export const deleteBankAccountV1BankAccountsBankAccountIdDeleteMutation = (
  options?: Partial<
    Options<DeleteBankAccountV1BankAccountsBankAccountIdDeleteData>
  >,
): UseMutationOptions<
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteError,
  Options<DeleteBankAccountV1BankAccountsBankAccountIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse,
    DeleteBankAccountV1BankAccountsBankAccountIdDeleteError,
    Options<DeleteBankAccountV1BankAccountsBankAccountIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteBankAccountV1BankAccountsBankAccountIdDelete(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        },
      );
      return data;
    },
  };
  return mutationOptions;
};

export const getBankAccountV1BankAccountsBankAccountIdGetQueryKey = (
  options: Options<GetBankAccountV1BankAccountsBankAccountIdGetData>,
) => createQueryKey("getBankAccountV1BankAccountsBankAccountIdGet", options);

/**
 * Get Bank Account
 *
 * Get a bank account by ID.
 */
export const getBankAccountV1BankAccountsBankAccountIdGetOptions = (
  options: Options<GetBankAccountV1BankAccountsBankAccountIdGetData>,
) =>
  queryOptions<
    GetBankAccountV1BankAccountsBankAccountIdGetResponse,
    GetBankAccountV1BankAccountsBankAccountIdGetError,
    GetBankAccountV1BankAccountsBankAccountIdGetResponse,
    ReturnType<typeof getBankAccountV1BankAccountsBankAccountIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBankAccountV1BankAccountsBankAccountIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBankAccountV1BankAccountsBankAccountIdGetQueryKey(options),
  });

/**
 * Update Bank Account
 *
 * Update a bank account.
 */
export const updateBankAccountV1BankAccountsBankAccountIdPatchMutation = (
  options?: Partial<
    Options<UpdateBankAccountV1BankAccountsBankAccountIdPatchData>
  >,
): UseMutationOptions<
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchError,
  Options<UpdateBankAccountV1BankAccountsBankAccountIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
    UpdateBankAccountV1BankAccountsBankAccountIdPatchError,
    Options<UpdateBankAccountV1BankAccountsBankAccountIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateBankAccountV1BankAccountsBankAccountIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listCategoriesV1CategoriesGetQueryKey = (
  options?: Options<ListCategoriesV1CategoriesGetData>,
) => createQueryKey("listCategoriesV1CategoriesGet", options);

/**
 * List Categories
 *
 * List all categories.
 */
export const listCategoriesV1CategoriesGetOptions = (
  options?: Options<ListCategoriesV1CategoriesGetData>,
) =>
  queryOptions<
    ListCategoriesV1CategoriesGetResponse,
    ListCategoriesV1CategoriesGetError,
    ListCategoriesV1CategoriesGetResponse,
    ReturnType<typeof listCategoriesV1CategoriesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listCategoriesV1CategoriesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listCategoriesV1CategoriesGetQueryKey(options),
  });

export const listCategoriesV1CategoriesGetInfiniteQueryKey = (
  options?: Options<ListCategoriesV1CategoriesGetData>,
): QueryKey<Options<ListCategoriesV1CategoriesGetData>> =>
  createQueryKey("listCategoriesV1CategoriesGet", options, true);

/**
 * List Categories
 *
 * List all categories.
 */
export const listCategoriesV1CategoriesGetInfiniteOptions = (
  options?: Options<ListCategoriesV1CategoriesGetData>,
) =>
  infiniteQueryOptions<
    ListCategoriesV1CategoriesGetResponse,
    ListCategoriesV1CategoriesGetError,
    InfiniteData<ListCategoriesV1CategoriesGetResponse>,
    QueryKey<Options<ListCategoriesV1CategoriesGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListCategoriesV1CategoriesGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListCategoriesV1CategoriesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listCategoriesV1CategoriesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listCategoriesV1CategoriesGetInfiniteQueryKey(options),
    },
  );

export const listCountersV1CountersGetQueryKey = (
  options?: Options<ListCountersV1CountersGetData>,
) => createQueryKey("listCountersV1CountersGet", options);

/**
 * List Counters
 */
export const listCountersV1CountersGetOptions = (
  options?: Options<ListCountersV1CountersGetData>,
) =>
  queryOptions<
    ListCountersV1CountersGetResponse,
    DefaultError,
    ListCountersV1CountersGetResponse,
    ReturnType<typeof listCountersV1CountersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listCountersV1CountersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listCountersV1CountersGetQueryKey(options),
  });

/**
 * Create Counter
 */
export const createCounterV1CountersPostMutation = (
  options?: Partial<Options<CreateCounterV1CountersPostData>>,
): UseMutationOptions<
  CreateCounterV1CountersPostResponse,
  CreateCounterV1CountersPostError,
  Options<CreateCounterV1CountersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateCounterV1CountersPostResponse,
    CreateCounterV1CountersPostError,
    Options<CreateCounterV1CountersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCounterV1CountersPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Counter
 */
export const deleteCounterV1CountersCounterIdDeleteMutation = (
  options?: Partial<Options<DeleteCounterV1CountersCounterIdDeleteData>>,
): UseMutationOptions<
  DeleteCounterV1CountersCounterIdDeleteResponse,
  DeleteCounterV1CountersCounterIdDeleteError,
  Options<DeleteCounterV1CountersCounterIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteCounterV1CountersCounterIdDeleteResponse,
    DeleteCounterV1CountersCounterIdDeleteError,
    Options<DeleteCounterV1CountersCounterIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteCounterV1CountersCounterIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Counter
 */
export const updateCounterV1CountersCounterIdPatchMutation = (
  options?: Partial<Options<UpdateCounterV1CountersCounterIdPatchData>>,
): UseMutationOptions<
  UpdateCounterV1CountersCounterIdPatchResponse,
  UpdateCounterV1CountersCounterIdPatchError,
  Options<UpdateCounterV1CountersCounterIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateCounterV1CountersCounterIdPatchResponse,
    UpdateCounterV1CountersCounterIdPatchError,
    Options<UpdateCounterV1CountersCounterIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateCounterV1CountersCounterIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listResetsV1CountersCounterIdResetsGetQueryKey = (
  options: Options<ListResetsV1CountersCounterIdResetsGetData>,
) => createQueryKey("listResetsV1CountersCounterIdResetsGet", options);

/**
 * List Resets
 */
export const listResetsV1CountersCounterIdResetsGetOptions = (
  options: Options<ListResetsV1CountersCounterIdResetsGetData>,
) =>
  queryOptions<
    ListResetsV1CountersCounterIdResetsGetResponse,
    ListResetsV1CountersCounterIdResetsGetError,
    ListResetsV1CountersCounterIdResetsGetResponse,
    ReturnType<typeof listResetsV1CountersCounterIdResetsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listResetsV1CountersCounterIdResetsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listResetsV1CountersCounterIdResetsGetQueryKey(options),
  });

/**
 * Record Reset
 */
export const createResetV1CountersCounterIdResetsPostMutation = (
  options?: Partial<Options<CreateResetV1CountersCounterIdResetsPostData>>,
): UseMutationOptions<
  CreateResetV1CountersCounterIdResetsPostResponse,
  CreateResetV1CountersCounterIdResetsPostError,
  Options<CreateResetV1CountersCounterIdResetsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateResetV1CountersCounterIdResetsPostResponse,
    CreateResetV1CountersCounterIdResetsPostError,
    Options<CreateResetV1CountersCounterIdResetsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createResetV1CountersCounterIdResetsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Undo Reset
 */
export const undoResetV1CountersCounterIdResetsResetIdDeleteMutation = (
  options?: Partial<
    Options<UndoResetV1CountersCounterIdResetsResetIdDeleteData>
  >,
): UseMutationOptions<
  UndoResetV1CountersCounterIdResetsResetIdDeleteResponse,
  UndoResetV1CountersCounterIdResetsResetIdDeleteError,
  Options<UndoResetV1CountersCounterIdResetsResetIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    UndoResetV1CountersCounterIdResetsResetIdDeleteResponse,
    UndoResetV1CountersCounterIdResetsResetIdDeleteError,
    Options<UndoResetV1CountersCounterIdResetsResetIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await undoResetV1CountersCounterIdResetsResetIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listDevicesV1DevicesGetQueryKey = (
  options?: Options<ListDevicesV1DevicesGetData>,
) => createQueryKey("listDevicesV1DevicesGet", options);

/**
 * List Devices
 */
export const listDevicesV1DevicesGetOptions = (
  options?: Options<ListDevicesV1DevicesGetData>,
) =>
  queryOptions<
    ListDevicesV1DevicesGetResponse,
    DefaultError,
    ListDevicesV1DevicesGetResponse,
    ReturnType<typeof listDevicesV1DevicesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listDevicesV1DevicesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listDevicesV1DevicesGetQueryKey(options),
  });

/**
 * Delete Device
 */
export const deleteDeviceV1DevicesDeviceIdDeleteMutation = (
  options?: Partial<Options<DeleteDeviceV1DevicesDeviceIdDeleteData>>,
): UseMutationOptions<
  DeleteDeviceV1DevicesDeviceIdDeleteResponse,
  DeleteDeviceV1DevicesDeviceIdDeleteError,
  Options<DeleteDeviceV1DevicesDeviceIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteDeviceV1DevicesDeviceIdDeleteResponse,
    DeleteDeviceV1DevicesDeviceIdDeleteError,
    Options<DeleteDeviceV1DevicesDeviceIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteDeviceV1DevicesDeviceIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Rename Device
 */
export const updateDeviceV1DevicesDeviceIdPatchMutation = (
  options?: Partial<Options<UpdateDeviceV1DevicesDeviceIdPatchData>>,
): UseMutationOptions<
  UpdateDeviceV1DevicesDeviceIdPatchResponse,
  UpdateDeviceV1DevicesDeviceIdPatchError,
  Options<UpdateDeviceV1DevicesDeviceIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateDeviceV1DevicesDeviceIdPatchResponse,
    UpdateDeviceV1DevicesDeviceIdPatchError,
    Options<UpdateDeviceV1DevicesDeviceIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateDeviceV1DevicesDeviceIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Sync HealthKit Workouts
 */
export const syncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostMutation = (
  options?: Partial<
    Options<SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostData>
  >,
): UseMutationOptions<
  SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostResponse,
  SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostError,
  Options<SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostData>
> => {
  const mutationOptions: UseMutationOptions<
    SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostResponse,
    SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostError,
    Options<SyncHealthkitWorkoutsV1HealthkitWorkoutsSyncPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await syncHealthkitWorkoutsV1HealthkitWorkoutsSyncPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listHealthkitWorkoutsV1HealthkitWorkoutsGetQueryKey = (
  options?: Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>,
) => createQueryKey("listHealthkitWorkoutsV1HealthkitWorkoutsGet", options);

/**
 * List HealthKit Workouts
 */
export const listHealthkitWorkoutsV1HealthkitWorkoutsGetOptions = (
  options?: Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>,
) =>
  queryOptions<
    ListHealthkitWorkoutsV1HealthkitWorkoutsGetResponse,
    ListHealthkitWorkoutsV1HealthkitWorkoutsGetError,
    ListHealthkitWorkoutsV1HealthkitWorkoutsGetResponse,
    ReturnType<typeof listHealthkitWorkoutsV1HealthkitWorkoutsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listHealthkitWorkoutsV1HealthkitWorkoutsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listHealthkitWorkoutsV1HealthkitWorkoutsGetQueryKey(options),
  });

export const listHealthkitWorkoutsV1HealthkitWorkoutsGetInfiniteQueryKey = (
  options?: Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>,
): QueryKey<Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>> =>
  createQueryKey("listHealthkitWorkoutsV1HealthkitWorkoutsGet", options, true);

/**
 * List HealthKit Workouts
 */
export const listHealthkitWorkoutsV1HealthkitWorkoutsGetInfiniteOptions = (
  options?: Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>,
) =>
  infiniteQueryOptions<
    ListHealthkitWorkoutsV1HealthkitWorkoutsGetResponse,
    ListHealthkitWorkoutsV1HealthkitWorkoutsGetError,
    InfiniteData<ListHealthkitWorkoutsV1HealthkitWorkoutsGetResponse>,
    QueryKey<Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListHealthkitWorkoutsV1HealthkitWorkoutsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listHealthkitWorkoutsV1HealthkitWorkoutsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        listHealthkitWorkoutsV1HealthkitWorkoutsGetInfiniteQueryKey(options),
    },
  );

export const listSecuritiesV1InvestmentsSecuritiesGetQueryKey = (
  options?: Options<ListSecuritiesV1InvestmentsSecuritiesGetData>,
) => createQueryKey("listSecuritiesV1InvestmentsSecuritiesGet", options);

/**
 * List Securities
 */
export const listSecuritiesV1InvestmentsSecuritiesGetOptions = (
  options?: Options<ListSecuritiesV1InvestmentsSecuritiesGetData>,
) =>
  queryOptions<
    ListSecuritiesV1InvestmentsSecuritiesGetResponse,
    ListSecuritiesV1InvestmentsSecuritiesGetError,
    ListSecuritiesV1InvestmentsSecuritiesGetResponse,
    ReturnType<typeof listSecuritiesV1InvestmentsSecuritiesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSecuritiesV1InvestmentsSecuritiesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listSecuritiesV1InvestmentsSecuritiesGetQueryKey(options),
  });

export const listSecuritiesV1InvestmentsSecuritiesGetInfiniteQueryKey = (
  options?: Options<ListSecuritiesV1InvestmentsSecuritiesGetData>,
): QueryKey<Options<ListSecuritiesV1InvestmentsSecuritiesGetData>> =>
  createQueryKey("listSecuritiesV1InvestmentsSecuritiesGet", options, true);

/**
 * List Securities
 */
export const listSecuritiesV1InvestmentsSecuritiesGetInfiniteOptions = (
  options?: Options<ListSecuritiesV1InvestmentsSecuritiesGetData>,
) =>
  infiniteQueryOptions<
    ListSecuritiesV1InvestmentsSecuritiesGetResponse,
    ListSecuritiesV1InvestmentsSecuritiesGetError,
    InfiniteData<ListSecuritiesV1InvestmentsSecuritiesGetResponse>,
    QueryKey<Options<ListSecuritiesV1InvestmentsSecuritiesGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListSecuritiesV1InvestmentsSecuritiesGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListSecuritiesV1InvestmentsSecuritiesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listSecuritiesV1InvestmentsSecuritiesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        listSecuritiesV1InvestmentsSecuritiesGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Security
 */
export const createSecurityV1InvestmentsSecuritiesPostMutation = (
  options?: Partial<Options<CreateSecurityV1InvestmentsSecuritiesPostData>>,
): UseMutationOptions<
  CreateSecurityV1InvestmentsSecuritiesPostResponse,
  CreateSecurityV1InvestmentsSecuritiesPostError,
  Options<CreateSecurityV1InvestmentsSecuritiesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSecurityV1InvestmentsSecuritiesPostResponse,
    CreateSecurityV1InvestmentsSecuritiesPostError,
    Options<CreateSecurityV1InvestmentsSecuritiesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSecurityV1InvestmentsSecuritiesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Security
 */
export const deleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteMutation = (
  options?: Partial<
    Options<DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteData>
  >,
): UseMutationOptions<
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponse,
  DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteError,
  Options<DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteResponse,
    DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteError,
    Options<DeleteSecurityV1InvestmentsSecuritiesSecurityIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteSecurityV1InvestmentsSecuritiesSecurityIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Security
 */
export const updateSecurityV1InvestmentsSecuritiesSecurityIdPatchMutation = (
  options?: Partial<
    Options<UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchData>
  >,
): UseMutationOptions<
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponse,
  UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchError,
  Options<UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchResponse,
    UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchError,
    Options<UpdateSecurityV1InvestmentsSecuritiesSecurityIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await updateSecurityV1InvestmentsSecuritiesSecurityIdPatch({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

export const listTradesV1InvestmentsTradesGetQueryKey = (
  options?: Options<ListTradesV1InvestmentsTradesGetData>,
) => createQueryKey("listTradesV1InvestmentsTradesGet", options);

/**
 * List Trades
 */
export const listTradesV1InvestmentsTradesGetOptions = (
  options?: Options<ListTradesV1InvestmentsTradesGetData>,
) =>
  queryOptions<
    ListTradesV1InvestmentsTradesGetResponse,
    ListTradesV1InvestmentsTradesGetError,
    ListTradesV1InvestmentsTradesGetResponse,
    ReturnType<typeof listTradesV1InvestmentsTradesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTradesV1InvestmentsTradesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTradesV1InvestmentsTradesGetQueryKey(options),
  });

export const listTradesV1InvestmentsTradesGetInfiniteQueryKey = (
  options?: Options<ListTradesV1InvestmentsTradesGetData>,
): QueryKey<Options<ListTradesV1InvestmentsTradesGetData>> =>
  createQueryKey("listTradesV1InvestmentsTradesGet", options, true);

/**
 * List Trades
 */
export const listTradesV1InvestmentsTradesGetInfiniteOptions = (
  options?: Options<ListTradesV1InvestmentsTradesGetData>,
) =>
  infiniteQueryOptions<
    ListTradesV1InvestmentsTradesGetResponse,
    ListTradesV1InvestmentsTradesGetError,
    InfiniteData<ListTradesV1InvestmentsTradesGetResponse>,
    QueryKey<Options<ListTradesV1InvestmentsTradesGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListTradesV1InvestmentsTradesGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTradesV1InvestmentsTradesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listTradesV1InvestmentsTradesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listTradesV1InvestmentsTradesGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Trade
 */
export const createTradeV1InvestmentsTradesPostMutation = (
  options?: Partial<Options<CreateTradeV1InvestmentsTradesPostData>>,
): UseMutationOptions<
  CreateTradeV1InvestmentsTradesPostResponse,
  CreateTradeV1InvestmentsTradesPostError,
  Options<CreateTradeV1InvestmentsTradesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTradeV1InvestmentsTradesPostResponse,
    CreateTradeV1InvestmentsTradesPostError,
    Options<CreateTradeV1InvestmentsTradesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTradeV1InvestmentsTradesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Trade
 */
export const deleteTradeV1InvestmentsTradesTradeIdDeleteMutation = (
  options?: Partial<Options<DeleteTradeV1InvestmentsTradesTradeIdDeleteData>>,
): UseMutationOptions<
  DeleteTradeV1InvestmentsTradesTradeIdDeleteResponse,
  DeleteTradeV1InvestmentsTradesTradeIdDeleteError,
  Options<DeleteTradeV1InvestmentsTradesTradeIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTradeV1InvestmentsTradesTradeIdDeleteResponse,
    DeleteTradeV1InvestmentsTradesTradeIdDeleteError,
    Options<DeleteTradeV1InvestmentsTradesTradeIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTradeV1InvestmentsTradesTradeIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Trade
 */
export const updateTradeV1InvestmentsTradesTradeIdPatchMutation = (
  options?: Partial<Options<UpdateTradeV1InvestmentsTradesTradeIdPatchData>>,
): UseMutationOptions<
  UpdateTradeV1InvestmentsTradesTradeIdPatchResponse,
  UpdateTradeV1InvestmentsTradesTradeIdPatchError,
  Options<UpdateTradeV1InvestmentsTradesTradeIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTradeV1InvestmentsTradesTradeIdPatchResponse,
    UpdateTradeV1InvestmentsTradesTradeIdPatchError,
    Options<UpdateTradeV1InvestmentsTradesTradeIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTradeV1InvestmentsTradesTradeIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetQueryKey =
  (
    options: Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>,
  ) =>
    createQueryKey(
      "listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGet",
      options,
    );

/**
 * List Security Prices
 */
export const listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetOptions =
  (
    options: Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>,
  ) =>
    queryOptions<
      ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse,
      ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetError,
      ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse,
      ReturnType<
        typeof listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true,
          });
        return data;
      },
      queryKey:
        listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetQueryKey(
          options,
        ),
    });

export const listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetInfiniteQueryKey =
  (
    options: Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>,
  ): QueryKey<
    Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>
  > =>
    createQueryKey(
      "listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGet",
      options,
      true,
    );

/**
 * List Security Prices
 */
export const listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetInfiniteOptions =
  (
    options: Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>,
  ) =>
    infiniteQueryOptions<
      ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse,
      ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetError,
      InfiniteData<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetResponse>,
      QueryKey<
        Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>
      >,
      | number
      | Pick<
          QueryKey<
            Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>
          >[0],
          "body" | "headers" | "path" | "query"
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              Options<ListSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetData>
            >[0],
            "body" | "headers" | "path" | "query"
          > =
            typeof pageParam === "object"
              ? pageParam
              : {
                  query: {
                    page: pageParam,
                  },
                };
          const params = createInfiniteParams(queryKey, page);
          const { data } =
            await listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGet({
              ...options,
              ...params,
              signal,
              throwOnError: true,
            });
          return data;
        },
        queryKey:
          listSecurityPricesV1InvestmentsSecuritiesSecurityIdPricesGetInfiniteQueryKey(
            options,
          ),
      },
    );

/**
 * Add Security Price
 */
export const createSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostMutation =
  (
    options?: Partial<
      Options<CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostData>
    >,
  ): UseMutationOptions<
    CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponse,
    CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostError,
    Options<CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostResponse,
      CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostError,
      Options<CreateSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await createSecurityPriceV1InvestmentsSecuritiesSecurityIdPricesPost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

export const getHoldingsV1InvestmentsHoldingsGetQueryKey = (
  options?: Options<GetHoldingsV1InvestmentsHoldingsGetData>,
) => createQueryKey("getHoldingsV1InvestmentsHoldingsGet", options);

/**
 * Get Holdings
 */
export const getHoldingsV1InvestmentsHoldingsGetOptions = (
  options?: Options<GetHoldingsV1InvestmentsHoldingsGetData>,
) =>
  queryOptions<
    GetHoldingsV1InvestmentsHoldingsGetResponse,
    DefaultError,
    GetHoldingsV1InvestmentsHoldingsGetResponse,
    ReturnType<typeof getHoldingsV1InvestmentsHoldingsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHoldingsV1InvestmentsHoldingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHoldingsV1InvestmentsHoldingsGetQueryKey(options),
  });

export const getCryptoPriceV1InvestmentsCryptoPriceCoinIdGetQueryKey = (
  options: Options<GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetData>,
) => createQueryKey("getCryptoPriceV1InvestmentsCryptoPriceCoinIdGet", options);

/**
 * Get Crypto Price
 */
export const getCryptoPriceV1InvestmentsCryptoPriceCoinIdGetOptions = (
  options: Options<GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetData>,
) =>
  queryOptions<
    GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetResponse,
    GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetError,
    GetCryptoPriceV1InvestmentsCryptoPriceCoinIdGetResponse,
    ReturnType<typeof getCryptoPriceV1InvestmentsCryptoPriceCoinIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCryptoPriceV1InvestmentsCryptoPriceCoinIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCryptoPriceV1InvestmentsCryptoPriceCoinIdGetQueryKey(options),
  });

export const listNotificationsV1NotificationsGetQueryKey = (
  options?: Options<ListNotificationsV1NotificationsGetData>,
) => createQueryKey("listNotificationsV1NotificationsGet", options);

/**
 * List Notifications
 */
export const listNotificationsV1NotificationsGetOptions = (
  options?: Options<ListNotificationsV1NotificationsGetData>,
) =>
  queryOptions<
    ListNotificationsV1NotificationsGetResponse,
    DefaultError,
    ListNotificationsV1NotificationsGetResponse,
    ReturnType<typeof listNotificationsV1NotificationsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listNotificationsV1NotificationsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listNotificationsV1NotificationsGetQueryKey(options),
  });

/**
 * Create Notification
 */
export const createNotificationV1NotificationsPostMutation = (
  options?: Partial<Options<CreateNotificationV1NotificationsPostData>>,
): UseMutationOptions<
  CreateNotificationV1NotificationsPostResponse,
  CreateNotificationV1NotificationsPostError,
  Options<CreateNotificationV1NotificationsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateNotificationV1NotificationsPostResponse,
    CreateNotificationV1NotificationsPostError,
    Options<CreateNotificationV1NotificationsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createNotificationV1NotificationsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Mark Notification Read
 */
export const markNotificationReadV1NotificationsNotificationIdReadPostMutation =
  (
    options?: Partial<
      Options<MarkNotificationReadV1NotificationsNotificationIdReadPostData>
    >,
  ): UseMutationOptions<
    MarkNotificationReadV1NotificationsNotificationIdReadPostResponse,
    MarkNotificationReadV1NotificationsNotificationIdReadPostError,
    Options<MarkNotificationReadV1NotificationsNotificationIdReadPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      MarkNotificationReadV1NotificationsNotificationIdReadPostResponse,
      MarkNotificationReadV1NotificationsNotificationIdReadPostError,
      Options<MarkNotificationReadV1NotificationsNotificationIdReadPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await markNotificationReadV1NotificationsNotificationIdReadPost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * Mark All Notifications Read
 */
export const markAllNotificationsReadV1NotificationsReadAllPostMutation = (
  options?: Partial<
    Options<MarkAllNotificationsReadV1NotificationsReadAllPostData>
  >,
): UseMutationOptions<
  MarkAllNotificationsReadV1NotificationsReadAllPostResponse,
  DefaultError,
  Options<MarkAllNotificationsReadV1NotificationsReadAllPostData>
> => {
  const mutationOptions: UseMutationOptions<
    MarkAllNotificationsReadV1NotificationsReadAllPostResponse,
    DefaultError,
    Options<MarkAllNotificationsReadV1NotificationsReadAllPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await markAllNotificationsReadV1NotificationsReadAllPost(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        },
      );
      return data;
    },
  };
  return mutationOptions;
};

export const listPlacesV1PlacesGetQueryKey = (
  options?: Options<ListPlacesV1PlacesGetData>,
) => createQueryKey("listPlacesV1PlacesGet", options);

/**
 * List Places
 */
export const listPlacesV1PlacesGetOptions = (
  options?: Options<ListPlacesV1PlacesGetData>,
) =>
  queryOptions<
    ListPlacesV1PlacesGetResponse,
    ListPlacesV1PlacesGetError,
    ListPlacesV1PlacesGetResponse,
    ReturnType<typeof listPlacesV1PlacesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPlacesV1PlacesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listPlacesV1PlacesGetQueryKey(options),
  });

export const listPlacesV1PlacesGetInfiniteQueryKey = (
  options?: Options<ListPlacesV1PlacesGetData>,
): QueryKey<Options<ListPlacesV1PlacesGetData>> =>
  createQueryKey("listPlacesV1PlacesGet", options, true);

/**
 * List Places
 */
export const listPlacesV1PlacesGetInfiniteOptions = (
  options?: Options<ListPlacesV1PlacesGetData>,
) =>
  infiniteQueryOptions<
    ListPlacesV1PlacesGetResponse,
    ListPlacesV1PlacesGetError,
    InfiniteData<ListPlacesV1PlacesGetResponse>,
    QueryKey<Options<ListPlacesV1PlacesGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListPlacesV1PlacesGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListPlacesV1PlacesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listPlacesV1PlacesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listPlacesV1PlacesGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Place
 */
export const createPlaceV1PlacesPostMutation = (
  options?: Partial<Options<CreatePlaceV1PlacesPostData>>,
): UseMutationOptions<
  CreatePlaceV1PlacesPostResponse,
  CreatePlaceV1PlacesPostError,
  Options<CreatePlaceV1PlacesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreatePlaceV1PlacesPostResponse,
    CreatePlaceV1PlacesPostError,
    Options<CreatePlaceV1PlacesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPlaceV1PlacesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const searchGooglePlacesV1PlacesSearchGetQueryKey = (
  options: Options<SearchGooglePlacesV1PlacesSearchGetData>,
) => createQueryKey("searchGooglePlacesV1PlacesSearchGet", options);

/**
 * Search Google Places
 */
export const searchGooglePlacesV1PlacesSearchGetOptions = (
  options: Options<SearchGooglePlacesV1PlacesSearchGetData>,
) =>
  queryOptions<
    SearchGooglePlacesV1PlacesSearchGetResponse,
    SearchGooglePlacesV1PlacesSearchGetError,
    SearchGooglePlacesV1PlacesSearchGetResponse,
    ReturnType<typeof searchGooglePlacesV1PlacesSearchGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchGooglePlacesV1PlacesSearchGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchGooglePlacesV1PlacesSearchGetQueryKey(options),
  });

/**
 * Delete Place
 */
export const deletePlaceV1PlacesPlaceIdDeleteMutation = (
  options?: Partial<Options<DeletePlaceV1PlacesPlaceIdDeleteData>>,
): UseMutationOptions<
  DeletePlaceV1PlacesPlaceIdDeleteResponse,
  DeletePlaceV1PlacesPlaceIdDeleteError,
  Options<DeletePlaceV1PlacesPlaceIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeletePlaceV1PlacesPlaceIdDeleteResponse,
    DeletePlaceV1PlacesPlaceIdDeleteError,
    Options<DeletePlaceV1PlacesPlaceIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deletePlaceV1PlacesPlaceIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Place
 */
export const updatePlaceV1PlacesPlaceIdPatchMutation = (
  options?: Partial<Options<UpdatePlaceV1PlacesPlaceIdPatchData>>,
): UseMutationOptions<
  UpdatePlaceV1PlacesPlaceIdPatchResponse,
  UpdatePlaceV1PlacesPlaceIdPatchError,
  Options<UpdatePlaceV1PlacesPlaceIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePlaceV1PlacesPlaceIdPatchResponse,
    UpdatePlaceV1PlacesPlaceIdPatchError,
    Options<UpdatePlaceV1PlacesPlaceIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePlaceV1PlacesPlaceIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listProjectsV1ProjectsGetQueryKey = (
  options?: Options<ListProjectsV1ProjectsGetData>,
) => createQueryKey("listProjectsV1ProjectsGet", options);

/**
 * List Projects
 */
export const listProjectsV1ProjectsGetOptions = (
  options?: Options<ListProjectsV1ProjectsGetData>,
) =>
  queryOptions<
    ListProjectsV1ProjectsGetResponse,
    ListProjectsV1ProjectsGetError,
    ListProjectsV1ProjectsGetResponse,
    ReturnType<typeof listProjectsV1ProjectsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listProjectsV1ProjectsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listProjectsV1ProjectsGetQueryKey(options),
  });

/**
 * Create Project
 */
export const createProjectV1ProjectsPostMutation = (
  options?: Partial<Options<CreateProjectV1ProjectsPostData>>,
): UseMutationOptions<
  CreateProjectV1ProjectsPostResponse,
  CreateProjectV1ProjectsPostError,
  Options<CreateProjectV1ProjectsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateProjectV1ProjectsPostResponse,
    CreateProjectV1ProjectsPostError,
    Options<CreateProjectV1ProjectsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createProjectV1ProjectsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Project
 */
export const deleteProjectV1ProjectsProjectIdDeleteMutation = (
  options?: Partial<Options<DeleteProjectV1ProjectsProjectIdDeleteData>>,
): UseMutationOptions<
  DeleteProjectV1ProjectsProjectIdDeleteResponse,
  DeleteProjectV1ProjectsProjectIdDeleteError,
  Options<DeleteProjectV1ProjectsProjectIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteProjectV1ProjectsProjectIdDeleteResponse,
    DeleteProjectV1ProjectsProjectIdDeleteError,
    Options<DeleteProjectV1ProjectsProjectIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteProjectV1ProjectsProjectIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Project
 */
export const updateProjectV1ProjectsProjectIdPatchMutation = (
  options?: Partial<Options<UpdateProjectV1ProjectsProjectIdPatchData>>,
): UseMutationOptions<
  UpdateProjectV1ProjectsProjectIdPatchResponse,
  UpdateProjectV1ProjectsProjectIdPatchError,
  Options<UpdateProjectV1ProjectsProjectIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateProjectV1ProjectsProjectIdPatchResponse,
    UpdateProjectV1ProjectsProjectIdPatchError,
    Options<UpdateProjectV1ProjectsProjectIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateProjectV1ProjectsProjectIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set Project Location For This Device
 */
export const setProjectLocationV1ProjectsProjectIdLocationPutMutation = (
  options?: Partial<
    Options<SetProjectLocationV1ProjectsProjectIdLocationPutData>
  >,
): UseMutationOptions<
  SetProjectLocationV1ProjectsProjectIdLocationPutResponse,
  SetProjectLocationV1ProjectsProjectIdLocationPutError,
  Options<SetProjectLocationV1ProjectsProjectIdLocationPutData>
> => {
  const mutationOptions: UseMutationOptions<
    SetProjectLocationV1ProjectsProjectIdLocationPutResponse,
    SetProjectLocationV1ProjectsProjectIdLocationPutError,
    Options<SetProjectLocationV1ProjectsProjectIdLocationPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setProjectLocationV1ProjectsProjectIdLocationPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listRecipesV1RecipesGetQueryKey = (
  options?: Options<ListRecipesV1RecipesGetData>,
) => createQueryKey("listRecipesV1RecipesGet", options);

/**
 * List Recipes
 */
export const listRecipesV1RecipesGetOptions = (
  options?: Options<ListRecipesV1RecipesGetData>,
) =>
  queryOptions<
    ListRecipesV1RecipesGetResponse,
    ListRecipesV1RecipesGetError,
    ListRecipesV1RecipesGetResponse,
    ReturnType<typeof listRecipesV1RecipesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listRecipesV1RecipesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listRecipesV1RecipesGetQueryKey(options),
  });

export const listRecipesV1RecipesGetInfiniteQueryKey = (
  options?: Options<ListRecipesV1RecipesGetData>,
): QueryKey<Options<ListRecipesV1RecipesGetData>> =>
  createQueryKey("listRecipesV1RecipesGet", options, true);

/**
 * List Recipes
 */
export const listRecipesV1RecipesGetInfiniteOptions = (
  options?: Options<ListRecipesV1RecipesGetData>,
) =>
  infiniteQueryOptions<
    ListRecipesV1RecipesGetResponse,
    ListRecipesV1RecipesGetError,
    InfiniteData<ListRecipesV1RecipesGetResponse>,
    QueryKey<Options<ListRecipesV1RecipesGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListRecipesV1RecipesGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListRecipesV1RecipesGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listRecipesV1RecipesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listRecipesV1RecipesGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Recipe
 */
export const createRecipeV1RecipesPostMutation = (
  options?: Partial<Options<CreateRecipeV1RecipesPostData>>,
): UseMutationOptions<
  CreateRecipeV1RecipesPostResponse,
  CreateRecipeV1RecipesPostError,
  Options<CreateRecipeV1RecipesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRecipeV1RecipesPostResponse,
    CreateRecipeV1RecipesPostError,
    Options<CreateRecipeV1RecipesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRecipeV1RecipesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Recipe
 */
export const deleteRecipeV1RecipesRecipeIdDeleteMutation = (
  options?: Partial<Options<DeleteRecipeV1RecipesRecipeIdDeleteData>>,
): UseMutationOptions<
  DeleteRecipeV1RecipesRecipeIdDeleteResponse,
  DeleteRecipeV1RecipesRecipeIdDeleteError,
  Options<DeleteRecipeV1RecipesRecipeIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteRecipeV1RecipesRecipeIdDeleteResponse,
    DeleteRecipeV1RecipesRecipeIdDeleteError,
    Options<DeleteRecipeV1RecipesRecipeIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteRecipeV1RecipesRecipeIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRecipeV1RecipesRecipeIdGetQueryKey = (
  options: Options<GetRecipeV1RecipesRecipeIdGetData>,
) => createQueryKey("getRecipeV1RecipesRecipeIdGet", options);

/**
 * Get Recipe
 */
export const getRecipeV1RecipesRecipeIdGetOptions = (
  options: Options<GetRecipeV1RecipesRecipeIdGetData>,
) =>
  queryOptions<
    GetRecipeV1RecipesRecipeIdGetResponse,
    GetRecipeV1RecipesRecipeIdGetError,
    GetRecipeV1RecipesRecipeIdGetResponse,
    ReturnType<typeof getRecipeV1RecipesRecipeIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRecipeV1RecipesRecipeIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRecipeV1RecipesRecipeIdGetQueryKey(options),
  });

/**
 * Update Recipe
 */
export const updateRecipeV1RecipesRecipeIdPatchMutation = (
  options?: Partial<Options<UpdateRecipeV1RecipesRecipeIdPatchData>>,
): UseMutationOptions<
  UpdateRecipeV1RecipesRecipeIdPatchResponse,
  UpdateRecipeV1RecipesRecipeIdPatchError,
  Options<UpdateRecipeV1RecipesRecipeIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateRecipeV1RecipesRecipeIdPatchResponse,
    UpdateRecipeV1RecipesRecipeIdPatchError,
    Options<UpdateRecipeV1RecipesRecipeIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateRecipeV1RecipesRecipeIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listTasksV1TasksGetQueryKey = (
  options?: Options<ListTasksV1TasksGetData>,
) => createQueryKey("listTasksV1TasksGet", options);

/**
 * List Tasks
 */
export const listTasksV1TasksGetOptions = (
  options?: Options<ListTasksV1TasksGetData>,
) =>
  queryOptions<
    ListTasksV1TasksGetResponse,
    ListTasksV1TasksGetError,
    ListTasksV1TasksGetResponse,
    ReturnType<typeof listTasksV1TasksGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTasksV1TasksGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTasksV1TasksGetQueryKey(options),
  });

export const listTasksV1TasksGetInfiniteQueryKey = (
  options?: Options<ListTasksV1TasksGetData>,
): QueryKey<Options<ListTasksV1TasksGetData>> =>
  createQueryKey("listTasksV1TasksGet", options, true);

/**
 * List Tasks
 */
export const listTasksV1TasksGetInfiniteOptions = (
  options?: Options<ListTasksV1TasksGetData>,
) =>
  infiniteQueryOptions<
    ListTasksV1TasksGetResponse,
    ListTasksV1TasksGetError,
    InfiniteData<ListTasksV1TasksGetResponse>,
    QueryKey<Options<ListTasksV1TasksGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListTasksV1TasksGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTasksV1TasksGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listTasksV1TasksGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listTasksV1TasksGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Task
 */
export const createTaskV1TasksPostMutation = (
  options?: Partial<Options<CreateTaskV1TasksPostData>>,
): UseMutationOptions<
  CreateTaskV1TasksPostResponse,
  CreateTaskV1TasksPostError,
  Options<CreateTaskV1TasksPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTaskV1TasksPostResponse,
    CreateTaskV1TasksPostError,
    Options<CreateTaskV1TasksPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTaskV1TasksPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reorder Tasks
 */
export const reorderTasksV1TasksReorderPatchMutation = (
  options?: Partial<Options<ReorderTasksV1TasksReorderPatchData>>,
): UseMutationOptions<
  ReorderTasksV1TasksReorderPatchResponse,
  ReorderTasksV1TasksReorderPatchError,
  Options<ReorderTasksV1TasksReorderPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    ReorderTasksV1TasksReorderPatchResponse,
    ReorderTasksV1TasksReorderPatchError,
    Options<ReorderTasksV1TasksReorderPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await reorderTasksV1TasksReorderPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Task
 */
export const deleteTaskV1TasksTaskIdDeleteMutation = (
  options?: Partial<Options<DeleteTaskV1TasksTaskIdDeleteData>>,
): UseMutationOptions<
  DeleteTaskV1TasksTaskIdDeleteResponse,
  DeleteTaskV1TasksTaskIdDeleteError,
  Options<DeleteTaskV1TasksTaskIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTaskV1TasksTaskIdDeleteResponse,
    DeleteTaskV1TasksTaskIdDeleteError,
    Options<DeleteTaskV1TasksTaskIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTaskV1TasksTaskIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTaskV1TasksTaskIdGetQueryKey = (
  options: Options<GetTaskV1TasksTaskIdGetData>,
) => createQueryKey("getTaskV1TasksTaskIdGet", options);

/**
 * Get Task
 */
export const getTaskV1TasksTaskIdGetOptions = (
  options: Options<GetTaskV1TasksTaskIdGetData>,
) =>
  queryOptions<
    GetTaskV1TasksTaskIdGetResponse,
    GetTaskV1TasksTaskIdGetError,
    GetTaskV1TasksTaskIdGetResponse,
    ReturnType<typeof getTaskV1TasksTaskIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTaskV1TasksTaskIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTaskV1TasksTaskIdGetQueryKey(options),
  });

/**
 * Update Task
 */
export const updateTaskV1TasksTaskIdPatchMutation = (
  options?: Partial<Options<UpdateTaskV1TasksTaskIdPatchData>>,
): UseMutationOptions<
  UpdateTaskV1TasksTaskIdPatchResponse,
  UpdateTaskV1TasksTaskIdPatchError,
  Options<UpdateTaskV1TasksTaskIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTaskV1TasksTaskIdPatchResponse,
    UpdateTaskV1TasksTaskIdPatchError,
    Options<UpdateTaskV1TasksTaskIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTaskV1TasksTaskIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Complete Task
 */
export const completeTaskV1TasksTaskIdCompletePostMutation = (
  options?: Partial<Options<CompleteTaskV1TasksTaskIdCompletePostData>>,
): UseMutationOptions<
  CompleteTaskV1TasksTaskIdCompletePostResponse,
  CompleteTaskV1TasksTaskIdCompletePostError,
  Options<CompleteTaskV1TasksTaskIdCompletePostData>
> => {
  const mutationOptions: UseMutationOptions<
    CompleteTaskV1TasksTaskIdCompletePostResponse,
    CompleteTaskV1TasksTaskIdCompletePostError,
    Options<CompleteTaskV1TasksTaskIdCompletePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await completeTaskV1TasksTaskIdCompletePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reopen Task
 */
export const reopenTaskV1TasksTaskIdReopenPostMutation = (
  options?: Partial<Options<ReopenTaskV1TasksTaskIdReopenPostData>>,
): UseMutationOptions<
  ReopenTaskV1TasksTaskIdReopenPostResponse,
  ReopenTaskV1TasksTaskIdReopenPostError,
  Options<ReopenTaskV1TasksTaskIdReopenPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ReopenTaskV1TasksTaskIdReopenPostResponse,
    ReopenTaskV1TasksTaskIdReopenPostError,
    Options<ReopenTaskV1TasksTaskIdReopenPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await reopenTaskV1TasksTaskIdReopenPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listAreasV1TasksAreasGetQueryKey = (
  options?: Options<ListAreasV1TasksAreasGetData>,
) => createQueryKey("listAreasV1TasksAreasGet", options);

/**
 * List Areas
 */
export const listAreasV1TasksAreasGetOptions = (
  options?: Options<ListAreasV1TasksAreasGetData>,
) =>
  queryOptions<
    ListAreasV1TasksAreasGetResponse,
    DefaultError,
    ListAreasV1TasksAreasGetResponse,
    ReturnType<typeof listAreasV1TasksAreasGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAreasV1TasksAreasGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAreasV1TasksAreasGetQueryKey(options),
  });

/**
 * Delete Transactions
 *
 * Delete transactions by IDs.
 */
export const deleteTransactionsV1TransactionsDeleteMutation = (
  options?: Partial<Options<DeleteTransactionsV1TransactionsDeleteData>>,
): UseMutationOptions<
  DeleteTransactionsV1TransactionsDeleteResponse,
  DeleteTransactionsV1TransactionsDeleteError,
  Options<DeleteTransactionsV1TransactionsDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTransactionsV1TransactionsDeleteResponse,
    DeleteTransactionsV1TransactionsDeleteError,
    Options<DeleteTransactionsV1TransactionsDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTransactionsV1TransactionsDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listTransactionsV1TransactionsGetQueryKey = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
) => createQueryKey("listTransactionsV1TransactionsGet", options);

/**
 * List Transactions
 *
 * List transactions.
 */
export const listTransactionsV1TransactionsGetOptions = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
) =>
  queryOptions<
    ListTransactionsV1TransactionsGetResponse,
    ListTransactionsV1TransactionsGetError,
    ListTransactionsV1TransactionsGetResponse,
    ReturnType<typeof listTransactionsV1TransactionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTransactionsV1TransactionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTransactionsV1TransactionsGetQueryKey(options),
  });

export const listTransactionsV1TransactionsGetInfiniteQueryKey = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
): QueryKey<Options<ListTransactionsV1TransactionsGetData>> =>
  createQueryKey("listTransactionsV1TransactionsGet", options, true);

/**
 * List Transactions
 *
 * List transactions.
 */
export const listTransactionsV1TransactionsGetInfiniteOptions = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
) =>
  infiniteQueryOptions<
    ListTransactionsV1TransactionsGetResponse,
    ListTransactionsV1TransactionsGetError,
    InfiniteData<ListTransactionsV1TransactionsGetResponse>,
    QueryKey<Options<ListTransactionsV1TransactionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListTransactionsV1TransactionsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTransactionsV1TransactionsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listTransactionsV1TransactionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listTransactionsV1TransactionsGetInfiniteQueryKey(options),
    },
  );

/**
 * Import Transactions
 *
 * Import transactions from a bank export (CSV or XLSX).
 *
 * Duplicate transactions (by dedup hash) are automatically skipped.
 */
export const importTransactionsV1TransactionsImportPostMutation = (
  options?: Partial<Options<ImportTransactionsV1TransactionsImportPostData>>,
): UseMutationOptions<
  ImportTransactionsV1TransactionsImportPostResponse,
  ImportTransactionsV1TransactionsImportPostError,
  Options<ImportTransactionsV1TransactionsImportPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ImportTransactionsV1TransactionsImportPostResponse,
    ImportTransactionsV1TransactionsImportPostError,
    Options<ImportTransactionsV1TransactionsImportPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await importTransactionsV1TransactionsImportPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Bulk Update Transactions
 *
 * Update category for a list of transactions by ID.
 */
export const bulkUpdateTransactionsV1TransactionsBulkPatchMutation = (
  options?: Partial<Options<BulkUpdateTransactionsV1TransactionsBulkPatchData>>,
): UseMutationOptions<
  BulkUpdateTransactionsV1TransactionsBulkPatchResponse,
  BulkUpdateTransactionsV1TransactionsBulkPatchError,
  Options<BulkUpdateTransactionsV1TransactionsBulkPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    BulkUpdateTransactionsV1TransactionsBulkPatchResponse,
    BulkUpdateTransactionsV1TransactionsBulkPatchError,
    Options<BulkUpdateTransactionsV1TransactionsBulkPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await bulkUpdateTransactionsV1TransactionsBulkPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Transaction
 *
 * Update a transaction.
 */
export const updateTransactionV1TransactionsTransactionIdPatchMutation = (
  options?: Partial<
    Options<UpdateTransactionV1TransactionsTransactionIdPatchData>
  >,
): UseMutationOptions<
  UpdateTransactionV1TransactionsTransactionIdPatchResponse,
  UpdateTransactionV1TransactionsTransactionIdPatchError,
  Options<UpdateTransactionV1TransactionsTransactionIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTransactionV1TransactionsTransactionIdPatchResponse,
    UpdateTransactionV1TransactionsTransactionIdPatchError,
    Options<UpdateTransactionV1TransactionsTransactionIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTransactionV1TransactionsTransactionIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Bulk Categorize by Description
 *
 * Set category for all transactions matching the given description.
 */
export const categorizeByDescriptionV1TransactionsCategorizeByDescriptionPostMutation =
  (
    options?: Partial<
      Options<CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostData>
    >,
  ): UseMutationOptions<
    CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponse,
    CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostError,
    Options<CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostResponse,
      CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostError,
      Options<CategorizeByDescriptionV1TransactionsCategorizeByDescriptionPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await categorizeByDescriptionV1TransactionsCategorizeByDescriptionPost(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

export const spendingByCategoryV1TransactionsSpendingByCategoryGetQueryKey = (
  options: Options<SpendingByCategoryV1TransactionsSpendingByCategoryGetData>,
) =>
  createQueryKey(
    "spendingByCategoryV1TransactionsSpendingByCategoryGet",
    options,
  );

/**
 * Monthly Spending by Category
 *
 * Aggregate debit spending per category for a given month.
 */
export const spendingByCategoryV1TransactionsSpendingByCategoryGetOptions = (
  options: Options<SpendingByCategoryV1TransactionsSpendingByCategoryGetData>,
) =>
  queryOptions<
    SpendingByCategoryV1TransactionsSpendingByCategoryGetResponse,
    SpendingByCategoryV1TransactionsSpendingByCategoryGetError,
    SpendingByCategoryV1TransactionsSpendingByCategoryGetResponse,
    ReturnType<
      typeof spendingByCategoryV1TransactionsSpendingByCategoryGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await spendingByCategoryV1TransactionsSpendingByCategoryGet({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey:
      spendingByCategoryV1TransactionsSpendingByCategoryGetQueryKey(options),
  });

export const monthlyFlowV1TransactionsMonthlyFlowGetQueryKey = (
  options?: Options<MonthlyFlowV1TransactionsMonthlyFlowGetData>,
) => createQueryKey("monthlyFlowV1TransactionsMonthlyFlowGet", options);

/**
 * Monthly Income & Expenses
 *
 * Return income and expenses aggregated per month.
 */
export const monthlyFlowV1TransactionsMonthlyFlowGetOptions = (
  options?: Options<MonthlyFlowV1TransactionsMonthlyFlowGetData>,
) =>
  queryOptions<
    MonthlyFlowV1TransactionsMonthlyFlowGetResponse,
    MonthlyFlowV1TransactionsMonthlyFlowGetError,
    MonthlyFlowV1TransactionsMonthlyFlowGetResponse,
    ReturnType<typeof monthlyFlowV1TransactionsMonthlyFlowGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await monthlyFlowV1TransactionsMonthlyFlowGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: monthlyFlowV1TransactionsMonthlyFlowGetQueryKey(options),
  });

export const getWeatherForecastV1WeatherGetQueryKey = (
  options: Options<GetWeatherForecastV1WeatherGetData>,
) => createQueryKey("getWeatherForecastV1WeatherGet", options);

/**
 * Get Weather Forecast
 */
export const getWeatherForecastV1WeatherGetOptions = (
  options: Options<GetWeatherForecastV1WeatherGetData>,
) =>
  queryOptions<
    GetWeatherForecastV1WeatherGetResponse,
    GetWeatherForecastV1WeatherGetError,
    GetWeatherForecastV1WeatherGetResponse,
    ReturnType<typeof getWeatherForecastV1WeatherGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWeatherForecastV1WeatherGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWeatherForecastV1WeatherGetQueryKey(options),
  });

export const getKlarnaTransactionsV1KlarnaTransactionsGetQueryKey = (
  options: Options<GetKlarnaTransactionsV1KlarnaTransactionsGetData>,
) => createQueryKey("getKlarnaTransactionsV1KlarnaTransactionsGet", options);

/**
 * Get Klarna Transactions
 *
 * Fetch Klarna transactions and return raw GraphQL response.
 */
export const getKlarnaTransactionsV1KlarnaTransactionsGetOptions = (
  options: Options<GetKlarnaTransactionsV1KlarnaTransactionsGetData>,
) =>
  queryOptions<
    GetKlarnaTransactionsV1KlarnaTransactionsGetResponse,
    GetKlarnaTransactionsV1KlarnaTransactionsGetError,
    GetKlarnaTransactionsV1KlarnaTransactionsGetResponse,
    ReturnType<typeof getKlarnaTransactionsV1KlarnaTransactionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getKlarnaTransactionsV1KlarnaTransactionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getKlarnaTransactionsV1KlarnaTransactionsGetQueryKey(options),
  });

/**
 * Import Klarna Transactions
 *
 * Fetch Klarna transactions and import them into Bessel.
 * Skips rejected (isAmountLineThrough), pending, and duplicate transactions.
 */
export const importKlarnaTransactionsV1KlarnaImportPostMutation = (
  options?: Partial<Options<ImportKlarnaTransactionsV1KlarnaImportPostData>>,
): UseMutationOptions<
  ImportKlarnaTransactionsV1KlarnaImportPostResponse,
  ImportKlarnaTransactionsV1KlarnaImportPostError,
  Options<ImportKlarnaTransactionsV1KlarnaImportPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ImportKlarnaTransactionsV1KlarnaImportPostResponse,
    ImportKlarnaTransactionsV1KlarnaImportPostError,
    Options<ImportKlarnaTransactionsV1KlarnaImportPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await importKlarnaTransactionsV1KlarnaImportPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
