// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  getEmailV1UsersEmailTokenGet,
  getMeV1AuthMeGet,
  healthzHealthzGet,
  type Options,
  unsubscribeV1UsersUnsubscribeTokenGet,
} from "../sdk.gen";
import type {
  GetEmailV1UsersEmailTokenGetData,
  GetEmailV1UsersEmailTokenGetError,
  GetEmailV1UsersEmailTokenGetResponse,
  GetMeV1AuthMeGetData,
  GetMeV1AuthMeGetResponse,
  HealthzHealthzGetData,
  UnsubscribeV1UsersUnsubscribeTokenGetData,
  UnsubscribeV1UsersUnsubscribeTokenGetError,
  UnsubscribeV1UsersUnsubscribeTokenGetResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthzHealthzGetQueryKey = (
  options?: Options<HealthzHealthzGetData>,
) => createQueryKey("healthzHealthzGet", options);

/**
 * Healthz
 */
export const healthzHealthzGetOptions = (
  options?: Options<HealthzHealthzGetData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthzHealthzGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthzHealthzGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthzHealthzGetQueryKey(options),
  });

export const getMeV1AuthMeGetQueryKey = (
  options?: Options<GetMeV1AuthMeGetData>,
) => createQueryKey("getMeV1AuthMeGet", options);

/**
 * Get Current User
 *
 * Get information about the currently authenticated user.
 */
export const getMeV1AuthMeGetOptions = (
  options?: Options<GetMeV1AuthMeGetData>,
) =>
  queryOptions<
    GetMeV1AuthMeGetResponse,
    DefaultError,
    GetMeV1AuthMeGetResponse,
    ReturnType<typeof getMeV1AuthMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMeV1AuthMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMeV1AuthMeGetQueryKey(options),
  });

export const unsubscribeV1UsersUnsubscribeTokenGetQueryKey = (
  options: Options<UnsubscribeV1UsersUnsubscribeTokenGetData>,
) => createQueryKey("unsubscribeV1UsersUnsubscribeTokenGet", options);

/**
 * Unsubscribe from newsletter
 *
 * Unsubscribe a user from the newsletter using a signed token.
 *
 * The token contains the user ID and is verified using HMAC.
 * This endpoint is public and does not require authentication.
 */
export const unsubscribeV1UsersUnsubscribeTokenGetOptions = (
  options: Options<UnsubscribeV1UsersUnsubscribeTokenGetData>,
) =>
  queryOptions<
    UnsubscribeV1UsersUnsubscribeTokenGetResponse,
    UnsubscribeV1UsersUnsubscribeTokenGetError,
    UnsubscribeV1UsersUnsubscribeTokenGetResponse,
    ReturnType<typeof unsubscribeV1UsersUnsubscribeTokenGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await unsubscribeV1UsersUnsubscribeTokenGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: unsubscribeV1UsersUnsubscribeTokenGetQueryKey(options),
  });

export const getEmailV1UsersEmailTokenGetQueryKey = (
  options: Options<GetEmailV1UsersEmailTokenGetData>,
) => createQueryKey("getEmailV1UsersEmailTokenGet", options);

/**
 * Get user email from token
 *
 * Get the email address associated with a user token.
 *
 * The token is verified using HMAC before returning the email.
 * This endpoint is public and does not require authentication.
 */
export const getEmailV1UsersEmailTokenGetOptions = (
  options: Options<GetEmailV1UsersEmailTokenGetData>,
) =>
  queryOptions<
    GetEmailV1UsersEmailTokenGetResponse,
    GetEmailV1UsersEmailTokenGetError,
    GetEmailV1UsersEmailTokenGetResponse,
    ReturnType<typeof getEmailV1UsersEmailTokenGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEmailV1UsersEmailTokenGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEmailV1UsersEmailTokenGetQueryKey(options),
  });
