// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createBankAccountV1BankAccountsPost,
  deleteBankAccountV1BankAccountsBankAccountIdDelete,
  deleteTransactionsV1TransactionsDelete,
  getBankAccountV1BankAccountsBankAccountIdGet,
  healthzHealthzGet,
  importTransactionsV1TransactionsImportPost,
  listBankAccountsV1BankAccountsGet,
  listTransactionsV1TransactionsGet,
  type Options,
  updateBankAccountV1BankAccountsBankAccountIdPatch,
} from "../sdk.gen";
import type {
  CreateBankAccountV1BankAccountsPostData,
  CreateBankAccountV1BankAccountsPostError,
  CreateBankAccountV1BankAccountsPostResponse,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteData,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteError,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse,
  DeleteTransactionsV1TransactionsDeleteData,
  DeleteTransactionsV1TransactionsDeleteError,
  DeleteTransactionsV1TransactionsDeleteResponse,
  GetBankAccountV1BankAccountsBankAccountIdGetData,
  GetBankAccountV1BankAccountsBankAccountIdGetError,
  GetBankAccountV1BankAccountsBankAccountIdGetResponse,
  HealthzHealthzGetData,
  ImportTransactionsV1TransactionsImportPostData,
  ImportTransactionsV1TransactionsImportPostError,
  ImportTransactionsV1TransactionsImportPostResponse,
  ListBankAccountsV1BankAccountsGetData,
  ListBankAccountsV1BankAccountsGetError,
  ListBankAccountsV1BankAccountsGetResponse,
  ListTransactionsV1TransactionsGetData,
  ListTransactionsV1TransactionsGetError,
  ListTransactionsV1TransactionsGetResponse,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchData,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchError,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthzHealthzGetQueryKey = (
  options?: Options<HealthzHealthzGetData>,
) => createQueryKey("healthzHealthzGet", options);

/**
 * Healthz
 */
export const healthzHealthzGetOptions = (
  options?: Options<HealthzHealthzGetData>,
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthzHealthzGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthzHealthzGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthzHealthzGetQueryKey(options),
  });

export const listBankAccountsV1BankAccountsGetQueryKey = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
) => createQueryKey("listBankAccountsV1BankAccountsGet", options);

/**
 * List Bank Accounts
 *
 * List all bank accounts.
 */
export const listBankAccountsV1BankAccountsGetOptions = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
) =>
  queryOptions<
    ListBankAccountsV1BankAccountsGetResponse,
    ListBankAccountsV1BankAccountsGetError,
    ListBankAccountsV1BankAccountsGetResponse,
    ReturnType<typeof listBankAccountsV1BankAccountsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listBankAccountsV1BankAccountsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listBankAccountsV1BankAccountsGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listBankAccountsV1BankAccountsGetInfiniteQueryKey = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
): QueryKey<Options<ListBankAccountsV1BankAccountsGetData>> =>
  createQueryKey("listBankAccountsV1BankAccountsGet", options, true);

/**
 * List Bank Accounts
 *
 * List all bank accounts.
 */
export const listBankAccountsV1BankAccountsGetInfiniteOptions = (
  options?: Options<ListBankAccountsV1BankAccountsGetData>,
) =>
  infiniteQueryOptions<
    ListBankAccountsV1BankAccountsGetResponse,
    ListBankAccountsV1BankAccountsGetError,
    InfiniteData<ListBankAccountsV1BankAccountsGetResponse>,
    QueryKey<Options<ListBankAccountsV1BankAccountsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListBankAccountsV1BankAccountsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListBankAccountsV1BankAccountsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listBankAccountsV1BankAccountsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listBankAccountsV1BankAccountsGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Bank Account
 *
 * Create a new bank account.
 */
export const createBankAccountV1BankAccountsPostMutation = (
  options?: Partial<Options<CreateBankAccountV1BankAccountsPostData>>,
): UseMutationOptions<
  CreateBankAccountV1BankAccountsPostResponse,
  CreateBankAccountV1BankAccountsPostError,
  Options<CreateBankAccountV1BankAccountsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBankAccountV1BankAccountsPostResponse,
    CreateBankAccountV1BankAccountsPostError,
    Options<CreateBankAccountV1BankAccountsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createBankAccountV1BankAccountsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Bank Account
 *
 * Delete a bank account.
 */
export const deleteBankAccountV1BankAccountsBankAccountIdDeleteMutation = (
  options?: Partial<
    Options<DeleteBankAccountV1BankAccountsBankAccountIdDeleteData>
  >,
): UseMutationOptions<
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse,
  DeleteBankAccountV1BankAccountsBankAccountIdDeleteError,
  Options<DeleteBankAccountV1BankAccountsBankAccountIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteBankAccountV1BankAccountsBankAccountIdDeleteResponse,
    DeleteBankAccountV1BankAccountsBankAccountIdDeleteError,
    Options<DeleteBankAccountV1BankAccountsBankAccountIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteBankAccountV1BankAccountsBankAccountIdDelete(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        },
      );
      return data;
    },
  };
  return mutationOptions;
};

export const getBankAccountV1BankAccountsBankAccountIdGetQueryKey = (
  options: Options<GetBankAccountV1BankAccountsBankAccountIdGetData>,
) => createQueryKey("getBankAccountV1BankAccountsBankAccountIdGet", options);

/**
 * Get Bank Account
 *
 * Get a bank account by ID.
 */
export const getBankAccountV1BankAccountsBankAccountIdGetOptions = (
  options: Options<GetBankAccountV1BankAccountsBankAccountIdGetData>,
) =>
  queryOptions<
    GetBankAccountV1BankAccountsBankAccountIdGetResponse,
    GetBankAccountV1BankAccountsBankAccountIdGetError,
    GetBankAccountV1BankAccountsBankAccountIdGetResponse,
    ReturnType<typeof getBankAccountV1BankAccountsBankAccountIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBankAccountV1BankAccountsBankAccountIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBankAccountV1BankAccountsBankAccountIdGetQueryKey(options),
  });

/**
 * Update Bank Account
 *
 * Update a bank account.
 */
export const updateBankAccountV1BankAccountsBankAccountIdPatchMutation = (
  options?: Partial<
    Options<UpdateBankAccountV1BankAccountsBankAccountIdPatchData>
  >,
): UseMutationOptions<
  UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
  UpdateBankAccountV1BankAccountsBankAccountIdPatchError,
  Options<UpdateBankAccountV1BankAccountsBankAccountIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateBankAccountV1BankAccountsBankAccountIdPatchResponse,
    UpdateBankAccountV1BankAccountsBankAccountIdPatchError,
    Options<UpdateBankAccountV1BankAccountsBankAccountIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateBankAccountV1BankAccountsBankAccountIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Transactions
 *
 * Delete transactions by IDs.
 */
export const deleteTransactionsV1TransactionsDeleteMutation = (
  options?: Partial<Options<DeleteTransactionsV1TransactionsDeleteData>>,
): UseMutationOptions<
  DeleteTransactionsV1TransactionsDeleteResponse,
  DeleteTransactionsV1TransactionsDeleteError,
  Options<DeleteTransactionsV1TransactionsDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTransactionsV1TransactionsDeleteResponse,
    DeleteTransactionsV1TransactionsDeleteError,
    Options<DeleteTransactionsV1TransactionsDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTransactionsV1TransactionsDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listTransactionsV1TransactionsGetQueryKey = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
) => createQueryKey("listTransactionsV1TransactionsGet", options);

/**
 * List Transactions
 *
 * List transactions.
 */
export const listTransactionsV1TransactionsGetOptions = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
) =>
  queryOptions<
    ListTransactionsV1TransactionsGetResponse,
    ListTransactionsV1TransactionsGetError,
    ListTransactionsV1TransactionsGetResponse,
    ReturnType<typeof listTransactionsV1TransactionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTransactionsV1TransactionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTransactionsV1TransactionsGetQueryKey(options),
  });

export const listTransactionsV1TransactionsGetInfiniteQueryKey = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
): QueryKey<Options<ListTransactionsV1TransactionsGetData>> =>
  createQueryKey("listTransactionsV1TransactionsGet", options, true);

/**
 * List Transactions
 *
 * List transactions.
 */
export const listTransactionsV1TransactionsGetInfiniteOptions = (
  options?: Options<ListTransactionsV1TransactionsGetData>,
) =>
  infiniteQueryOptions<
    ListTransactionsV1TransactionsGetResponse,
    ListTransactionsV1TransactionsGetError,
    InfiniteData<ListTransactionsV1TransactionsGetResponse>,
    QueryKey<Options<ListTransactionsV1TransactionsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListTransactionsV1TransactionsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTransactionsV1TransactionsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listTransactionsV1TransactionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listTransactionsV1TransactionsGetInfiniteQueryKey(options),
    },
  );

/**
 * Import Transactions from CSV
 *
 * Import transactions from a bank CSV export.
 *
 * Duplicate transactions (by dedup hash) are automatically skipped.
 */
export const importTransactionsV1TransactionsImportPostMutation = (
  options?: Partial<Options<ImportTransactionsV1TransactionsImportPostData>>,
): UseMutationOptions<
  ImportTransactionsV1TransactionsImportPostResponse,
  ImportTransactionsV1TransactionsImportPostError,
  Options<ImportTransactionsV1TransactionsImportPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ImportTransactionsV1TransactionsImportPostResponse,
    ImportTransactionsV1TransactionsImportPostError,
    Options<ImportTransactionsV1TransactionsImportPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await importTransactionsV1TransactionsImportPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
