"""add activity events

Revision ID: e49ad6188599
Revises: 4ccff691fe61
Create Date: 2026-06-15 21:04:06.704153

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e49ad6188599'
down_revision: str | Sequence[str] | None = '4ccff691fe61'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'activity_events',
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('app_class', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('workspace', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_events_pkey')),
    sa.UniqueConstraint('source', 'local_id', name='activity_events_source_local_id_key'),
  )
  op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
  op.create_index(op.f('ix_activity_events_deleted_at'), 'activity_events', ['deleted_at'], unique=False)
  op.create_index('ix_activity_events_source_ts', 'activity_events', ['source', 'ts'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index('ix_activity_events_source_ts', table_name='activity_events')
  op.drop_index(op.f('ix_activity_events_deleted_at'), table_name='activity_events')
  op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
  op.drop_table('activity_events')
  # ### end Alembic commands ###
