"""add gym exercise muscles

Revision ID: 6c702792fd1b
Revises: b0237c6a3f1c
Create Date: 2026-10-09 19:49:42.200050

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c702792fd1b'
down_revision: str | Sequence[str] | None = 'b0237c6a3f1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('gym_exercises', sa.Column('muscles', postgresql.ARRAY(sa.String(length=20)), server_default='{}', nullable=False))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('gym_exercises', 'muscles')
  # ### end Alembic commands ###
