"""add_counters_tables

Revision ID: 7ee8bf1e4ee4
Revises: 205f982ea4b0
Create Date: 2026-06-22 22:59:13.831902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ee8bf1e4ee4'
down_revision: str | Sequence[str] | None = '205f982ea4b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'counters',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('counters_pkey')),
  )
  op.create_index(op.f('ix_counters_created_at'), 'counters', ['created_at'], unique=False)
  op.create_index(op.f('ix_counters_deleted_at'), 'counters', ['deleted_at'], unique=False)
  op.create_table(
    'counter_resets',
    sa.Column('counter_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counter_id'], ['counters.id'], name=op.f('counter_resets_counter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('counter_resets_pkey')),
  )
  op.create_index(op.f('ix_counter_resets_counter_id'), 'counter_resets', ['counter_id'], unique=False)
  op.create_index(op.f('ix_counter_resets_created_at'), 'counter_resets', ['created_at'], unique=False)
  op.create_index(op.f('ix_counter_resets_deleted_at'), 'counter_resets', ['deleted_at'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_counter_resets_deleted_at'), table_name='counter_resets')
  op.drop_index(op.f('ix_counter_resets_created_at'), table_name='counter_resets')
  op.drop_index(op.f('ix_counter_resets_counter_id'), table_name='counter_resets')
  op.drop_table('counter_resets')
  op.drop_index(op.f('ix_counters_deleted_at'), table_name='counters')
  op.drop_index(op.f('ix_counters_created_at'), table_name='counters')
  op.drop_table('counters')
  # ### end Alembic commands ###
