"""add calendar event details

Revision ID: c4721c5a1cc0
Revises: acc403c95510
Create Date: 2026-10-03 02:27:45.797482

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4721c5a1cc0'
down_revision: str | Sequence[str] | None = 'acc403c95510'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('calendar_events', sa.Column('description', sa.Text(), nullable=True))
  op.add_column('calendar_events', sa.Column('creator_name', sa.String(length=255), nullable=True))
  op.add_column('calendar_events', sa.Column('creator_email', sa.String(length=320), nullable=True))
  op.add_column('calendar_events', sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
  op.add_column('calendar_events', sa.Column('conference_url', sa.String(length=2048), nullable=True))
  op.add_column('calendar_events', sa.Column('html_link', sa.String(length=2048), nullable=True))
  op.add_column('calendar_events', sa.Column('busy', sa.Boolean(), server_default=sa.text('true'), nullable=False))
  op.add_column('calendar_events', sa.Column('recurring', sa.Boolean(), server_default=sa.text('false'), nullable=False))
  op.add_column('calendar_events', sa.Column('visibility', sa.String(length=32), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('calendar_events', 'visibility')
  op.drop_column('calendar_events', 'recurring')
  op.drop_column('calendar_events', 'busy')
  op.drop_column('calendar_events', 'html_link')
  op.drop_column('calendar_events', 'conference_url')
  op.drop_column('calendar_events', 'attendees')
  op.drop_column('calendar_events', 'creator_email')
  op.drop_column('calendar_events', 'creator_name')
  op.drop_column('calendar_events', 'description')
  # ### end Alembic commands ###
