"""add users table and user_id to domain models

Revision ID: ca60bd695ed2
Revises: 376c8a028e71
Create Date: 2026-06-25 19:17:19.216426

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca60bd695ed2'
down_revision: str | Sequence[str] | None = '376c8a028e71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'users',
    sa.Column('auth0_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
  )
  op.create_index(op.f('ix_users_auth0_sub'), 'users', ['auth0_sub'], unique=True)
  op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
  op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
  op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
  op.drop_index(op.f('ix_journal_entries_deleted_at'), table_name='journal_entries')
  op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
  op.drop_table('journal_entries')
  # workout_sets must be dropped before exercises and workout_logs (FK deps)
  op.drop_index(op.f('ix_workout_sets_created_at'), table_name='workout_sets')
  op.drop_index(op.f('ix_workout_sets_deleted_at'), table_name='workout_sets')
  op.drop_table('workout_sets')
  op.drop_index(op.f('ix_exercises_created_at'), table_name='exercises')
  op.drop_index(op.f('ix_exercises_deleted_at'), table_name='exercises')
  op.drop_table('exercises')
  op.drop_index(op.f('ix_workout_logs_created_at'), table_name='workout_logs')
  op.drop_index(op.f('ix_workout_logs_deleted_at'), table_name='workout_logs')
  op.drop_table('workout_logs')
  op.add_column('activity_events', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_activity_events_user_id'), 'activity_events', ['user_id'], unique=False)
  op.create_foreign_key(op.f('activity_events_user_id_fkey'), 'activity_events', 'users', ['user_id'], ['id'])
  op.add_column('bank_accounts', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
  op.create_foreign_key(op.f('bank_accounts_user_id_fkey'), 'bank_accounts', 'users', ['user_id'], ['id'])
  op.add_column('categories', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
  op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
  op.create_foreign_key(op.f('categories_user_id_fkey'), 'categories', 'users', ['user_id'], ['id'])
  op.add_column('counter_resets', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_counter_resets_user_id'), 'counter_resets', ['user_id'], unique=False)
  op.create_foreign_key(op.f('counter_resets_user_id_fkey'), 'counter_resets', 'users', ['user_id'], ['id'])
  op.add_column('counters', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_counters_user_id'), 'counters', ['user_id'], unique=False)
  op.create_foreign_key(op.f('counters_user_id_fkey'), 'counters', 'users', ['user_id'], ['id'])
  op.add_column('notifications', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
  op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
  op.add_column('places', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_places_user_id'), 'places', ['user_id'], unique=False)
  op.create_foreign_key(op.f('places_user_id_fkey'), 'places', 'users', ['user_id'], ['id'])
  op.add_column('projects', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.drop_constraint(op.f('projects_name_key'), 'projects', type_='unique')
  op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
  op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
  op.add_column('recipes', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
  op.create_foreign_key(op.f('recipes_user_id_fkey'), 'recipes', 'users', ['user_id'], ['id'])
  op.add_column('tasks', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
  op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'])
  op.add_column('trades', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
  op.create_foreign_key(op.f('trades_user_id_fkey'), 'trades', 'users', ['user_id'], ['id'])
  op.add_column('transactions', sa.Column('user_id', sa.Uuid(), nullable=True))
  op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
  op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
  op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
  op.drop_column('transactions', 'user_id')
  op.drop_constraint(op.f('trades_user_id_fkey'), 'trades', type_='foreignkey')
  op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
  op.drop_column('trades', 'user_id')
  op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
  op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
  op.drop_column('tasks', 'user_id')
  op.drop_constraint(op.f('recipes_user_id_fkey'), 'recipes', type_='foreignkey')
  op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
  op.drop_column('recipes', 'user_id')
  op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
  op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
  op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
  op.drop_column('projects', 'user_id')
  op.drop_constraint(op.f('places_user_id_fkey'), 'places', type_='foreignkey')
  op.drop_index(op.f('ix_places_user_id'), table_name='places')
  op.drop_column('places', 'user_id')
  op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
  op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
  op.drop_column('notifications', 'user_id')
  op.drop_constraint(op.f('counters_user_id_fkey'), 'counters', type_='foreignkey')
  op.drop_index(op.f('ix_counters_user_id'), table_name='counters')
  op.drop_column('counters', 'user_id')
  op.drop_constraint(op.f('counter_resets_user_id_fkey'), 'counter_resets', type_='foreignkey')
  op.drop_index(op.f('ix_counter_resets_user_id'), table_name='counter_resets')
  op.drop_column('counter_resets', 'user_id')
  op.drop_constraint(op.f('categories_user_id_fkey'), 'categories', type_='foreignkey')
  op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
  op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
  op.drop_column('categories', 'user_id')
  op.drop_constraint(op.f('bank_accounts_user_id_fkey'), 'bank_accounts', type_='foreignkey')
  op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
  op.drop_column('bank_accounts', 'user_id')
  op.drop_constraint(op.f('activity_events_user_id_fkey'), 'activity_events', type_='foreignkey')
  op.drop_index(op.f('ix_activity_events_user_id'), table_name='activity_events')
  op.drop_column('activity_events', 'user_id')
  op.create_table(
    'workout_logs',
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_logs_pkey')),
  )
  op.create_index(op.f('ix_workout_logs_deleted_at'), 'workout_logs', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_workout_logs_created_at'), 'workout_logs', ['created_at'], unique=False)
  op.create_table(
    'workout_sets',
    sa.Column('workout_log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('set_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('weight_unit', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('rpe', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_pr', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rir', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('set_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('e1rm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('workout_sets_exercise_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], name=op.f('workout_sets_workout_log_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_sets_pkey')),
  )
  op.create_index(op.f('ix_workout_sets_deleted_at'), 'workout_sets', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_workout_sets_created_at'), 'workout_sets', ['created_at'], unique=False)
  op.create_table(
    'exercises',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column(
      'category',
      postgresql.ENUM(
        'chest',
        'back',
        'shoulders',
        'biceps',
        'triceps',
        'forearms',
        'core',
        'quads',
        'hamstrings',
        'glutes',
        'calves',
        'cardio',
        'olympic',
        'other',
        name='musclecategory',
      ),
      autoincrement=False,
      nullable=False,
    ),
    sa.Column(
      'equipment',
      postgresql.ENUM('barbell', 'dumbbell', 'cable', 'machine', 'bodyweight', 'kettlebell', 'band', 'other', name='equipment'),
      autoincrement=False,
      nullable=False,
    ),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey')),
  )
  op.create_index(op.f('ix_exercises_deleted_at'), 'exercises', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_exercises_created_at'), 'exercises', ['created_at'], unique=False)
  op.create_table(
    'journal_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('friction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gratitude_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gratitude_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gratitude_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('morning_committed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('captures', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scorecard', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority_done', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('insight', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entries_pkey')),
  )
  op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=True)
  op.create_index(op.f('ix_journal_entries_deleted_at'), 'journal_entries', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
  op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
  op.drop_index(op.f('ix_users_created_at'), table_name='users')
  op.drop_index(op.f('ix_users_auth0_sub'), table_name='users')
  op.drop_table('users')
  # ### end Alembic commands ###
