"""add_agent_usage_tables

Revision ID: 939153e37033
Revises: 8f100978d9be
Create Date: 2026-08-16 18:30:29.785992

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '939153e37033'
down_revision: str | Sequence[str] | None = '8f100978d9be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'agent_usage_daily',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_creation_tokens', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_usage_daily_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_usage_daily_pkey')),
    sa.UniqueConstraint('device', 'agent', 'date', 'model', name=op.f('agent_usage_daily_device_agent_date_model_key')),
  )
  op.create_index(op.f('ix_agent_usage_daily_created_at'), 'agent_usage_daily', ['created_at'], unique=False)
  op.create_index(op.f('ix_agent_usage_daily_date'), 'agent_usage_daily', ['date'], unique=False)
  op.create_index(op.f('ix_agent_usage_daily_deleted_at'), 'agent_usage_daily', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_agent_usage_daily_user_id'), 'agent_usage_daily', ['user_id'], unique=False)
  op.create_table(
    'agent_usage_status',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('window_label', sa.String(length=50), nullable=False),
    sa.Column('utilization_pct', sa.Float(), nullable=False),
    sa.Column('resets_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('observed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('agent_usage_status_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_usage_status_pkey')),
    sa.UniqueConstraint('device', 'agent', 'window_label', name=op.f('agent_usage_status_device_agent_window_label_key')),
  )
  op.create_index(op.f('ix_agent_usage_status_created_at'), 'agent_usage_status', ['created_at'], unique=False)
  op.create_index(op.f('ix_agent_usage_status_deleted_at'), 'agent_usage_status', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_agent_usage_status_user_id'), 'agent_usage_status', ['user_id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_agent_usage_status_user_id'), table_name='agent_usage_status')
  op.drop_index(op.f('ix_agent_usage_status_deleted_at'), table_name='agent_usage_status')
  op.drop_index(op.f('ix_agent_usage_status_created_at'), table_name='agent_usage_status')
  op.drop_table('agent_usage_status')
  op.drop_index(op.f('ix_agent_usage_daily_user_id'), table_name='agent_usage_daily')
  op.drop_index(op.f('ix_agent_usage_daily_deleted_at'), table_name='agent_usage_daily')
  op.drop_index(op.f('ix_agent_usage_daily_date'), table_name='agent_usage_daily')
  op.drop_index(op.f('ix_agent_usage_daily_created_at'), table_name='agent_usage_daily')
  op.drop_table('agent_usage_daily')
  # ### end Alembic commands ###
