"""add healthkit daily metrics

Revision ID: d59cd5ef17b2
Revises: 7c3e9a1d5b42
Create Date: 2026-10-08 02:26:58.494078

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd59cd5ef17b2'
down_revision: str | Sequence[str] | None = '7c3e9a1d5b42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'healthkit_daily_metrics',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_energy_kcal', sa.Float(), nullable=True),
    sa.Column('exercise_minutes', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('healthkit_daily_metrics_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('healthkit_daily_metrics_pkey')),
    sa.UniqueConstraint('user_id', 'date', name='healthkit_daily_metrics_user_id_date_key'),
  )
  op.create_index(op.f('ix_healthkit_daily_metrics_created_at'), 'healthkit_daily_metrics', ['created_at'], unique=False)
  op.create_index(op.f('ix_healthkit_daily_metrics_deleted_at'), 'healthkit_daily_metrics', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_healthkit_daily_metrics_user_id'), 'healthkit_daily_metrics', ['user_id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_healthkit_daily_metrics_user_id'), table_name='healthkit_daily_metrics')
  op.drop_index(op.f('ix_healthkit_daily_metrics_deleted_at'), table_name='healthkit_daily_metrics')
  op.drop_index(op.f('ix_healthkit_daily_metrics_created_at'), table_name='healthkit_daily_metrics')
  op.drop_table('healthkit_daily_metrics')
  # ### end Alembic commands ###
