"""add path to projects

Revision ID: 81b97aaf32fe
Revises: b3e91c7d4a20
Create Date: 2026-06-26 02:42:48.823476

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '81b97aaf32fe'
down_revision: str | Sequence[str] | None = 'b3e91c7d4a20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('projects', sa.Column('path', sa.String(length=500), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('projects', 'path')
  # ### end Alembic commands ###
