"""add workout tables

Revision ID: 15f656f863dd
Revises: p6q7r8s9t0u1
Create Date: 2026-03-21 14:36:48.484981

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15f656f863dd'
down_revision: str | Sequence[str] | None = 'p6q7r8s9t0u1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'exercises',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column(
      'category',
      sa.Enum(
        'chest',
        'back',
        'shoulders',
        'biceps',
        'triceps',
        'forearms',
        'core',
        'quads',
        'hamstrings',
        'glutes',
        'calves',
        'cardio',
        'olympic',
        'other',
        name='musclecategory',
      ),
      nullable=False,
    ),
    sa.Column('equipment', sa.Enum('barbell', 'dumbbell', 'cable', 'machine', 'bodyweight', 'kettlebell', 'band', 'other', name='equipment'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey')),
  )
  op.create_index(op.f('ix_exercises_created_at'), 'exercises', ['created_at'], unique=False)
  op.create_index(op.f('ix_exercises_deleted_at'), 'exercises', ['deleted_at'], unique=False)
  op.create_table(
    'workout_logs',
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_logs_pkey')),
  )
  op.create_index(op.f('ix_workout_logs_created_at'), 'workout_logs', ['created_at'], unique=False)
  op.create_index(op.f('ix_workout_logs_deleted_at'), 'workout_logs', ['deleted_at'], unique=False)
  op.create_table(
    'workout_sets',
    sa.Column('workout_log_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weight_unit', sa.String(length=3), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('workout_sets_exercise_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], name=op.f('workout_sets_workout_log_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workout_sets_pkey')),
  )
  op.create_index(op.f('ix_workout_sets_created_at'), 'workout_sets', ['created_at'], unique=False)
  op.create_index(op.f('ix_workout_sets_deleted_at'), 'workout_sets', ['deleted_at'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_workout_sets_deleted_at'), table_name='workout_sets')
  op.drop_index(op.f('ix_workout_sets_created_at'), table_name='workout_sets')
  op.drop_table('workout_sets')
  op.drop_index(op.f('ix_workout_logs_deleted_at'), table_name='workout_logs')
  op.drop_index(op.f('ix_workout_logs_created_at'), table_name='workout_logs')
  op.drop_table('workout_logs')
  op.drop_index(op.f('ix_exercises_deleted_at'), table_name='exercises')
  op.drop_index(op.f('ix_exercises_created_at'), table_name='exercises')
  op.drop_table('exercises')
  # ### end Alembic commands ###
