"""add calendar editing fields

Revision ID: 13858e318146
Revises: c4721c5a1cc0
Create Date: 2026-10-03 03:12:51.374537

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13858e318146'
down_revision: str | Sequence[str] | None = 'c4721c5a1cc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('calendar_accounts', sa.Column('can_write', sa.Boolean(), server_default=sa.text('false'), nullable=False))
  op.add_column('calendar_events', sa.Column('editable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
  op.add_column('calendar_events', sa.Column('series_id', sa.String(length=1024), nullable=True))
  op.add_column('calendar_events', sa.Column('original_start', sa.String(length=64), nullable=True))
  op.add_column('calendar_events', sa.Column('etag', sa.String(length=255), nullable=True))
  op.add_column('calendar_events', sa.Column('resource_href', sa.String(length=2048), nullable=True))
  op.add_column('calendar_events', sa.Column('rrule', sa.String(length=1024), nullable=True))
  op.add_column('calendars', sa.Column('writable', sa.Boolean(), server_default=sa.text('false'), nullable=False))
  op.add_column('calendars', sa.Column('primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
  # ### end Alembic commands ###
  # An app-specific password already allows writing; only Google grants were read-only.
  op.execute("UPDATE calendar_accounts SET can_write = true WHERE provider = 'icloud'")


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('calendars', 'primary')
  op.drop_column('calendars', 'writable')
  op.drop_column('calendar_events', 'rrule')
  op.drop_column('calendar_events', 'resource_href')
  op.drop_column('calendar_events', 'etag')
  op.drop_column('calendar_events', 'original_start')
  op.drop_column('calendar_events', 'series_id')
  op.drop_column('calendar_events', 'editable')
  op.drop_column('calendar_accounts', 'can_write')
  # ### end Alembic commands ###
