"""add_healthkit_workouts_table

Revision ID: 3ed794c4c4a6
Revises: 076fe4199632
Create Date: 2026-07-13 22:07:19.019044

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ed794c4c4a6'
down_revision: str | Sequence[str] | None = '076fe4199632'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    'healthkit_workouts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('healthkit_uuid', sa.Uuid(), nullable=False),
    sa.Column('workout_activity_type', sa.Integer(), nullable=False),
    sa.Column('workout_activity_type_name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('total_energy_burned', sa.Float(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_bundle_id', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('workout_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('healthkit_workouts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('healthkit_workouts_pkey')),
    sa.UniqueConstraint('user_id', 'healthkit_uuid', name='healthkit_workouts_user_id_healthkit_uuid_key'),
  )
  op.create_index(op.f('ix_healthkit_workouts_created_at'), 'healthkit_workouts', ['created_at'], unique=False)
  op.create_index(op.f('ix_healthkit_workouts_deleted_at'), 'healthkit_workouts', ['deleted_at'], unique=False)
  op.create_index(op.f('ix_healthkit_workouts_user_id'), 'healthkit_workouts', ['user_id'], unique=False)
  op.create_index('ix_healthkit_workouts_user_id_start_date', 'healthkit_workouts', ['user_id', 'start_date'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index('ix_healthkit_workouts_user_id_start_date', table_name='healthkit_workouts')
  op.drop_index(op.f('ix_healthkit_workouts_user_id'), table_name='healthkit_workouts')
  op.drop_index(op.f('ix_healthkit_workouts_deleted_at'), table_name='healthkit_workouts')
  op.drop_index(op.f('ix_healthkit_workouts_created_at'), table_name='healthkit_workouts')
  op.drop_table('healthkit_workouts')
  # ### end Alembic commands ###
