"""add is_business to transactions

Revision ID: 4ccff691fe61
Revises: 49159e3e930f
Create Date: 2026-05-14 01:05:28.515076

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ccff691fe61'
down_revision: str | Sequence[str] | None = '49159e3e930f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(op.f('journal_entries_entry_date_key'), 'journal_entries', type_='unique')
  op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
  op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=True)
  op.create_index(op.f('ix_securities_created_at'), 'securities', ['created_at'], unique=False)
  op.drop_index(op.f('ix_security_prices_security_id'), table_name='security_prices')
  op.create_index(op.f('ix_security_prices_created_at'), 'security_prices', ['created_at'], unique=False)
  op.drop_index(op.f('ix_trades_bank_account_id'), table_name='trades')
  op.drop_index(op.f('ix_trades_security_id'), table_name='trades')
  op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
  op.add_column('transactions', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('transactions', 'is_business')
  op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
  op.create_index(op.f('ix_trades_security_id'), 'trades', ['security_id'], unique=False)
  op.create_index(op.f('ix_trades_bank_account_id'), 'trades', ['bank_account_id'], unique=False)
  op.drop_index(op.f('ix_security_prices_created_at'), table_name='security_prices')
  op.create_index(op.f('ix_security_prices_security_id'), 'security_prices', ['security_id'], unique=False)
  op.drop_index(op.f('ix_securities_created_at'), table_name='securities')
  op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
  op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
  op.create_unique_constraint(op.f('journal_entries_entry_date_key'), 'journal_entries', ['entry_date'], postgresql_nulls_not_distinct=False)
  # ### end Alembic commands ###
