"""make healthkit sleep sample user_id nullable

Revision ID: 8f100978d9be
Revises: f1cb4bb3130f
Create Date: 2026-07-14 18:16:02.046247

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f100978d9be'
down_revision: str | Sequence[str] | None = 'f1cb4bb3130f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('healthkit_sleep_samples', 'user_id', existing_type=sa.UUID(), nullable=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('healthkit_sleep_samples', 'user_id', existing_type=sa.UUID(), nullable=False)
  # ### end Alembic commands ###
